# -*- coding: utf-8 -*-
"""應用領域：螢光粉用在哪裡、用的是哪些材料、關鍵數字與主要玩家。"""

APPLICATIONS = {
    "lead": "同一種「把藍光換成別的顏色」的能力，放在不同場合就長出完全不同的產業：照明要效率與顯色、顯示要色純度、雷射要耐熱、農業要特定波長、醫療要把 X 光變可見光。以下按應用整理。",
    "items": [
        {"id": "lighting", "name": "一般照明", "icon": "💡",
         "lead": "白光 LED 的顏色品質、效率與壽命有一大半由螢光粉決定。藍光晶片加 YAG:Ce 做冷白，加綠粉與紅粉做高顯色暖白。",
         "numbers": ["商用白光 LED > 200 lm/W", "實驗室 303 lm/W（Cree 2014）", "Ra 80 → 95 約損失 20–25% 光效", "美國 2035 年可年省 4.8 quads"],
         "points": [
             "顯色與效率的取捨：要 R9 高就得補深紅光，但深紅光人眼不敏感；窄頻紅粉（KSF、SLA、SALON）的價值就是縮小這個差距。",
             "美國能源部估計 pc-LED 封裝光效可從 160 提升到 255 lm/W，窄頻紅色轉換材料是主要槓桿之一。",
             "全光譜／人因照明用紫光晶片或補青色螢光粉，讓光譜接近日光；日亞 Optisolis 做到 Ra 99、Rf 98。",
             "歐盟 2023 年起淘汰含汞螢光燈管，照明螢光粉的重心已幾乎全部轉到 LED。"],
         "materials": ["YAG:Ce", "LuAG:Ce", "SCASN／CASN", "KSF", "青色粉"],
         "players": ["Nichia", "ams OSRAM", "Lumileds", "Samsung LED", "首爾半導體", "Bridgelux", "億光", "木林森"],
         "srcs": [{"url": "https://www.energy.gov/cmei/ssl/ssl-forecast-report", "name": "DOE SSL 節能預測"}, {"url": "https://www.osti.gov/servlets/purl/1862626", "name": "DOE 2022 SSL R&D Opportunities"}]},
        {"id": "display", "name": "顯示器背光與量子點之爭", "icon": "📺",
         "lead": "LCD 的藍光背光需要色轉換材料做出紅與綠。KSF 紅粉加 β-SiAlON 綠粉是十年來最普及、最便宜的廣色域方案；量子點以更窄的譜線搶攻高階。",
         "numbers": ["KSF 方案 ≈ 95% DCI-P3、70–88% Rec.2020", "量子點膜 80–91% Rec.2020", "KSF LED 累計出貨 > 1,000 億顆（2014–2025）", "2025 年 Mini LED 電視 1,156 萬台（TrendForce）"],
         "points": [
             "SID 2025 展場實測近 80 台 LCD 中超過一半含 KSF，車用 LCD 展品更有七成以上採用（KSF 專利方陣營統計）。",
             "歐盟含鎘量子點的顯示用豁免於 2025 年 11 月到期，只保留封裝內量子點到 2027 年底，產業加速轉向 InP 與鈣鈦礦。",
             "「假 QLED」爭議：2025 年檢測發現部分標榜量子點的電視未驗出銦或鎘，可能只靠 KSF 達到廣色域；Samsung 在德國對 TCL 勝訴。",
             "RGB Mini LED 電視（Hisense、TCL、Samsung Micro RGB）直接用三色晶片當背光，不需螢光粉或量子點，是高階背光「去色轉換化」的訊號。",
             "Micro LED 畫素小於 10–20 µm 時傳統螢光粉吸收不足，量子點與次微米螢光粉（Edison／Current Chemicals 的 KSF 墨水）成為主戰場。"],
         "materials": ["KSF", "β-SiAlON:Eu", "SCASN", "InP／CdSe 量子點", "鈣鈦礦量子點"],
         "players": ["Nichia", "Denka", "Edison Innovations", "Samsung Display", "Nanosys／昭榮化學", "TCL", "群創", "錼創", "友達"],
         "srcs": [{"url": "https://sid.onlinelibrary.wiley.com/doi/10.1002/msid.70057", "name": "SID Information Display 2026（KSF 十年）"}, {"url": "https://www.tuv.com/regulations-and-standards/en/eu-exemptions-on-the-use-of-cadmium-in-quantum-dots-in-led-lighting-and-displays.html", "name": "TÜV Rheinland（RoHS 鎘豁免）"}, {"url": "https://www.ledinside.com/intelligence/2026/8/2026_08_24_05", "name": "LEDinside／TrendForce 2026-08"}]},
        {"id": "laser", "name": "雷射照明、投影與雷射電視", "icon": "🔦",
         "lead": "藍光雷射把數瓦的光集中在不到 1 mm² 的點上，矽膠會黃化碳化，因此必須用螢光玻璃、螢光陶瓷或單晶等全無機轉換器。",
         "numbers": ["矽膠導熱 ≈ 0.2 W/(m·K)", "螢光玻璃 ≈ 3", "YAG:Ce 陶瓷 5–10", "Al₂O₃ 複合陶瓷 12–37 W/(m·K)", "白光雷射封裝亮度 1000–1300 cd/mm²"],
         "points": [
             "2014 年 BMW i8 與 Audi R8 LMX 讓雷射頭燈量產（OSRAM 供應模組），但 2024 年 BMW 已無後續計畫：美國法規限制射程優勢，矩陣 LED 更便宜。",
             "Nichia 2025 年推出 GigaWhite 白光雷射封裝，亮度約為 LED 的 10 倍，並內建感測器偵測螢光體破裂以防雷射外洩。",
             "雷射投影機與雷射電視用旋轉的螢光粉輪散熱；Appotronics 的 ALPD 技術掌握中國七到八成的電影雷射放映機，Hisense 2025 年雷射電視全球市占 70.3%。",
             "研究前沿是高導熱複合陶瓷與螢光玻璃薄膜：2025 年核殼式 YAG:Ce@Al₂O₃ 陶瓷達 3,900 lm/mm²，透明陶瓷@藍寶石達 36.9 W/(m·K)；紅光轉換器仍是短板。"],
         "materials": ["YAG:Ce 陶瓷／單晶", "LuAG:Ce 陶瓷", "螢光玻璃（PiG）", "CASN 紅光薄膜"],
         "players": ["Nichia", "ams OSRAM", "Lumileds（Lumiramic）", "SCHOTT", "日本電氣硝子", "Kyocera SLD Laser", "Appotronics", "Barco", "Hisense"],
         "srcs": [{"url": "https://pubs.aip.org/aip/apl/article/118/21/210503/1061193/Phosphor-converters-for-laser-driven-light-sources", "name": "Applied Physics Letters 2021（綜述）"}, {"url": "https://led-ld.nichia.co.jp/en/product/ld_gigawhite.html", "name": "Nichia GigaWhite"}, {"url": "https://www.forbes.com/sites/michaeltaylor/2024/08/14/laser-headlamps-are-disappearing-heres-why/", "name": "Forbes 2024（雷射頭燈退場）"}]},
        {"id": "auto", "name": "車用照明與車用顯示", "icon": "🚗",
         "lead": "頭燈需要高亮度與耐高溫的轉換器，座艙顯示需要車規等級的色彩與可靠度，兩者都是螢光粉的高價值市場。",
         "numbers": ["日本電氣硝子螢光玻璃耐熱 > 500 °C、85/85 測試 5,000 小時", "2030 年車用 Mini LED 滲透率潛力 4.3%"],
         "points": [
             "螢光玻璃（PiG）長期用於車用 LED 頭燈，不黃化、耐高溫，是矽膠之外最成熟的方案。",
             "KSF 方案在車用 LCD 展品中占七成以上；2026 年 Edison Innovations 把 KSF 授權給億光、富采等廠，明確鎖定車用中控與抬頭顯示。",
             "京東方 2025 年展出 6.2 吋 RGB Micro LED 抬頭顯示器（30,000 nits），走的是不靠色轉換的三色晶片路線。"],
         "materials": ["YAG:Ce 螢光玻璃", "螢光陶瓷", "KSF", "β-SiAlON"],
         "players": ["ams OSRAM", "Nichia", "Lumileds", "HELLA", "日本電氣硝子", "京東方"],
         "srcs": [{"url": "https://www.neg.co.jp/product/ep/lumiphous", "name": "日本電氣硝子 Lumiphous"}, {"url": "https://www.ledinside.com/interview/2026/8/2026_08_31_01", "name": "LEDinside 2026-08（Edison 專訪）"}]},
        {"id": "hcl", "name": "健康照明與全光譜", "icon": "🌤️",
         "lead": "用螢光粉配方調整光譜形狀，補上青色缺口、去掉藍光尖峰，讓光更接近日光並配合人體生理節律。",
         "numbers": ["日亞 Optisolis Ra 99、Rf 98／Rg 99", "Bridgelux Thrive 與日光光譜差 3–7%", "紫光方案效率約 120 lm/W 以上"],
         "points": [
             "首爾半導體 SunLike（2017）：紫光晶片激發東芝材料 TRI-R 三色螢光粉，光譜沒有 450 nm 尖峰。",
             "日亞 Vitasolis（2019）：以螢光粉增加青色成分，因為青色波段對晝夜節律影響最大；Optisolis 則用 420 nm 晶片做到超高顯色。",
             "CIE S 026 定義的黑視素等效日光照度（melanopic EDI）是評估光線生理效應的標準指標。",
             "代價是效率：紫光全轉換多一層斯托克斯損失，且高顯色本身就會損失兩成左右光效。"],
         "materials": ["BAM 藍粉", "青色粉", "LuAG／β-SiAlON", "SCASN／KSF"],
         "players": ["首爾半導體", "東芝材料", "Nichia", "Bridgelux", "Samsung LED", "Lumileds"],
         "srcs": [{"url": "https://www.ledinside.com/news/2017/6/seoul_semiconductor_and_toshiba_materials_co_develop_sunlike_solution_friendly_to_human_eyes", "name": "LEDinside 2017（SunLike）"}, {"url": "https://www.nichia.co.jp/en/newsroom/2019/2019_051701.html", "name": "Nichia 2019（Vitasolis）"}]},
        {"id": "nir", "name": "近紅外感測與生醫", "icon": "🔬",
         "lead": "藍光晶片加 Cr³⁺ 螢光粉就是一顆迷你寬頻近紅外光源，可裝進手機大小的裝置做光譜分析。",
         "numbers": ["OSRAM SFH 4737（2020）：650–1050 nm、74 mW @ 350 mA、18 mW/sr、1.6×1.6×0.9 mm", "2025 年論文級材料：峰值 785–866 nm、發光可達 1250 nm"],
         "points": [
             "用途：水果糖度與成熟度、食品含水量與脂肪、藥物真偽、皮膚血氧與生醫影像、夜視。",
             "2016 年 OSRAM 提出藍光激發螢光粉的近紅外 pc-LED 概念後，Cr³⁺ 石榴石、硼酸鹽、磷酸鹽成為熱門研究題目；近年也有近零熱猝滅與 Cr³⁺/Yb³⁺ 共摻雜材料。",
             "台灣（臺大劉如熹）、中國（華南理工夏志國、廈門大學）團隊在這個領域發表量大。"],
         "materials": ["Cr³⁺ 石榴石", "ScBO₃:Cr³⁺", "Cr³⁺/Yb³⁺ 共摻雜"],
         "players": ["ams OSRAM", "Lumileds", "臺灣大學", "華南理工大學"],
         "srcs": [{"url": "https://www.led-professional.com/products-services/osram-presents-the-worlds-smallest-broadband-ir-led-for-spectroscopy-applications", "name": "LED professional（OSRAM SFH 4737）"}]},
        {"id": "horti", "name": "園藝與農業照明", "icon": "🌱",
         "lead": "植物主要吸收藍光與紅光，遠紅光（730 nm）影響開花與株型；園藝 LED 用深紅與遠紅光螢光粉補足光譜。",
         "numbers": ["深紅 660 nm、遠紅 730 nm 為兩個關鍵波段"],
         "points": [
             "Mn⁴⁺ 氧化物深紅粉（650–660 nm）不怕水、不含稀土，適合植物燈；遠紅光可用 Cr³⁺ 或 Mn⁴⁺ 螢光粉或直接用遠紅光晶片。",
             "溫室的光轉換農膜把紫外或綠光轉成紅光，是螢光粉在農業的另一種用法。",
             "白光加補光（而非純紅藍「紫光」）已成主流，因為工作人員需要看得清楚植物狀態。"],
         "materials": ["Mn⁴⁺ 氧化物", "遠紅光 Cr³⁺ 粉", "SCASN", "YAG:Ce"],
         "players": ["ams OSRAM", "Signify", "Fluence", "Samsung LED"],
         "srcs": [{"url": "https://www.nature.com/articles/s41377-018-0013-1", "name": "Light: Science & Applications 2018（Mn⁴⁺ 氧化物）"}]},
        {"id": "glow", "name": "夜光、安全與防偽", "icon": "🌙",
         "lead": "長餘輝螢光粉在關燈後仍能持續發光數小時，用於逃生標示、手錶與道路標線；上轉換材料則是難以仿造的防偽油墨。",
         "numbers": ["SrAl₂O₄:Eu,Dy 比 ZnS:Cu,Co 亮約 10 倍，餘輝十幾小時", "安全標示門檻 0.32 mcd/m²（DIN 67510）", "理想陷阱深度約 0.6–0.7 eV"],
         "points": [
             "1993 年根本特殊化學為取代含鐳夜光塗料發明 LumiNova，1996 年發表論文後帶動整個領域。",
             "近紅外長餘輝材料（如 ZnGa₂O₄:Cr³⁺）可先充光再注入體內成像，避免生物組織自體螢光干擾。",
             "應力發光材料（SrAl₂O₄:Eu、ZnS:Mn）受力時發光，可「看見」結構受力分布。"],
         "materials": ["SrAl₂O₄:Eu,Dy", "Sr₄Al₁₄O₂₅:Eu,Dy", "NaYF₄:Yb,Er", "ZnGa₂O₄:Cr"],
         "players": ["根本特殊化學", "大連路明", "多家特用化學公司"],
         "srcs": [{"url": "https://iopscience.iop.org/article/10.1149/1.1837067", "name": "J. Electrochem. Soc. 1996（Matsuzawa）"}, {"url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC5445854/", "name": "Materials 2010 綜述"}]},
        {"id": "medical", "name": "醫療影像與輻射偵測（閃爍體）", "icon": "🩻",
         "lead": "閃爍體把 X 光、γ 射線轉成可見光，是數位 X 光平板、電腦斷層、正子造影與安檢的核心，本質上也是螢光材料。",
         "numbers": ["醫療平板主流：柱狀 CsI:Tl 與 Gd₂O₂S:Tb"],
         "points": [
             "CsI:Tl 以蒸鍍做成柱狀晶體，可做厚而保持解析度；Gd₂O₂S:Tb 粉末塗布成本低。",
             "正子造影用 LYSO:Ce 單晶，GAGG:Ce 石榴石陶瓷是近年高能物理與安檢的新材料。",
             "鈣鈦礦與奈米閃爍體是 2020 年代的研究熱點，目標是更便宜、更靈敏的 X 光成像。"],
         "materials": ["CsI:Tl", "Gd₂O₂S:Tb", "LYSO:Ce", "GAGG:Ce", "BGO"],
         "players": ["Luxium（原 Saint-Gobain）", "濱松", "CRYTUR", "上海矽酸鹽研究所"],
         "srcs": [{"url": "https://aapm.onlinelibrary.wiley.com/doi/abs/10.1002/mp.13791", "name": "Medical Physics 2019"}]},
    ],
}
