# -*- coding: utf-8 -*-
"""應用領域：螢光粉用在哪裡、用的是哪些材料、關鍵數字與主要玩家。
2026-09 依應用專題研究（人因照明、園藝、車用、紫外、近紅外、能源、消費者問答）改寫為 11 項。"""

APPLICATIONS = {
    "lead": "同一種「把藍光換成別的顏色」的能力，放在不同場合就長出完全不同的產業：照明要效率與顯色、顯示要色純度、雷射要耐熱、農業要特定波長、醫療要把 X 光變可見光、感測要看不見的近紅外。以下按應用整理，每項附關鍵數字、主要材料與玩家。數字多來自廠商規格或論文摘要，條件（電流、色溫、顯色）不同時不能直接比較。",
    "items": [
        {"id": "lighting", "name": "一般照明", "icon": "💡",
         "lead": "白光 LED 的顏色品質、效率與壽命有一大半由螢光粉決定。藍光晶片加 YAG:Ce 做冷白，加綠粉與紅粉做高顯色暖白。照明約占 2024 年全球用電 8%（約 2,200 TWh），LED 普及讓家庭照明用電在 2010–2022 年間減少近 30%。",
         "numbers": ["量產中功率 LED 220–240 lm/W（低電流、低 CRI 條件）", "實驗室 303 lm/W（Cree 2014）", "Ra 80 → 95 約損失 20–25% 光效", "DOE：達成研發目標則 2035 年年省 569 TWh", "Signify 2024 年 LED 產品占銷售 93%"],
         "points": [
             "顯色與效率的取捨：要 R9 高就得補深紅光，但深紅光人眼不敏感；窄頻紅粉（KSF、SLA、SALON、Eu³⁺ 奈米工程粉）的價值就是縮小這個差距。美國能源部估計 pc-LED 封裝光效可從 160 提升到 255 lm/W。",
             "效率里程碑：Samsung LM301B EVO 235 lm/W（2021，規格書典型值 230）、首爾半導體 WICOP 系統 240 lm/W（2024）、Cree XP-G4 220 lm/W、Bridgelux 2835 221 lm/W、Lumileds 5050 HE Plus 199 lm/W（2024）；高 CRI 暖白產品通常低 10–30%。",
             "法規推力：歐盟 2023 年起淘汰含汞螢光燈管；美國 DLC SSL V6.0（2026 年受理）把平均光效門檻提高 14%；歐盟生態設計 2024 年 9 月起 SVM ≤ 0.4；ANSI C78.377-2024 新增 1800K／2000K 色度，讓模擬高壓鈉燈色的低色溫 LED 有標準可循。",
             "壽命怎麼算：LM-80 至少量測 6,000 小時，TM-21 最多外推到測試時間的 6 倍（6,000 小時只能宣稱 36,000 小時）。光衰主因多是矽膠黃化、螢光粉層剝離與濕氣，而非晶片。",
             "市場現實：通用照明已成熟，Signify 2026 年裁員 900 人、日亞連續三期減益、三星退出 LED；成長點轉向車用、Mini LED 背光、雷射與近紅外。"],
         "materials": ["YAG:Ce", "LuAG:Ce", "SCASN／CASN", "KSF", "青色粉"],
         "players": ["Nichia", "ams OSRAM", "Lumileds", "首爾半導體", "Bridgelux", "億光", "木林森", "Signify"],
         "srcs": [{"url": "https://www.iea.org/commentaries/the-next-wave-of-led-lighting-smarter-circular-and-more-efficient", "name": "IEA：The next wave of LED lighting"}, {"url": "https://www.energy.gov/eere/ssl/articles/us-department-energy-publishes-new-energy-savings-forecast-solid-state-lighting", "name": "DOE SSL 節能預測（2019）"}, {"url": "https://www.osti.gov/servlets/purl/1862626", "name": "DOE 2022 SSL R&D Opportunities"}, {"url": "https://blog.ansi.org/ansi/ansi-ies-lm-80-21-measuring-led-output/", "name": "ANSI Blog：LM-80-21"}]},
        {"id": "display", "name": "顯示器背光與量子點之爭", "icon": "📺",
         "lead": "LCD 的藍光背光需要色轉換材料做出紅與綠。KSF 紅粉加 β-SiAlON 綠粉是十年來最普及、最便宜的廣色域方案；量子點以更窄的譜線搶攻高階；2025–2026 年又出現不需任何色轉換的 RGB Mini LED 與 Micro RGB 背光。",
         "numbers": ["KSF 方案 ≈ 95% DCI-P3、70–88% Rec.2020", "量子點膜 80–91% Rec.2020", "KSF LED 累計出貨 > 1,000 億顆（2014–2025，授權方統計）", "2024 年含量子點 LCD 電視 2,440 萬台、量子點膜營收 +42%（Counterpoint）", "2025 年 Mini LED 電視 1,156 萬台（TrendForce）"],
         "points": [
             "KSF 授權方統計：Display Week 2025 近 80 台 LCD 中超過一半含 KSF，車用 LCD 展品逾七成；美國展廳車用顯示器逾四成。資料來自 Edison Innovations／Murphy，具利益關係。",
             "KSF 的弱點：Mn⁴⁺ 自旋禁制躍遷使衰減時間超過 5 ms，在 120 Hz 以上或閃爍式背光會出現紅色拖影，這是研究者開發 Rb₂MoO₂F₄:Mn⁴⁺ 等「快響應」紅粉的動機；對車用儀表反而有助降低 PWM 調光閃爍。",
             "歐盟含鎘量子點的顯示用豁免於 2025-11-21 到期，只保留晶片上量子點到 2027 年底，產業加速轉向 InP（Nanosys／昭榮 521–640 nm 全波段可量產）與鈣鈦礦（TCL 與致晶科技試產綠色鈣鈦礦膜；Nature Electronics 2025 論述鈣鈦礦半高寬 ≤ 20 nm）。",
             "路線之爭：Hisense 116UX（2025-07）與 Samsung Micro RGB（CES 2026 擴至 55–130 吋）用三色晶片當背光，不需螢光粉或量子點；TCL 反向強化 SQD 超級量子點；日亞以綠光晶片取代綠粉（NS2W806H-B2）。2026 年 RGB Mini LED 電視預估 170–200 萬台。",
             "Micro LED 畫素小於 10–20 µm 時傳統螢光粉吸收不足，量子點、次微米 KSF 墨水（Edison／Current Chemicals）與鈣鈦礦薄膜（CEA-Leti 2026 晶圓級製程）成為主戰場；Samsung Display 的電致發光量子點原型（18 吋 500 nits）則是更長期的替代者。"],
         "materials": ["KSF", "β-SiAlON:Eu", "SCASN", "InP／CdSe 量子點", "鈣鈦礦量子點"],
         "players": ["Nichia", "Denka", "Edison Innovations", "Samsung Display", "Nanosys／昭榮化學", "TCL", "Hisense", "群創", "錼創", "友達"],
         "srcs": [{"url": "https://sid.onlinelibrary.wiley.com/doi/10.1002/msid.70057", "name": "SID Information Display 2026（KSF 十年）"}, {"url": "https://counterpointresearch.com/en/insights/increased-quantum-dot-adoption-in-displays-drives-double-digit-revenue-growth-in-2024", "name": "Counterpoint Research 2024"}, {"url": "https://www.sciencedirect.com/science/article/abs/pii/S1385894721005672", "name": "Chemical Engineering Journal 2021（KSF 衰減時間）"}, {"url": "https://www.ledinside.com/intelligence/2026/8/2026_08_24_05", "name": "LEDinside／TrendForce 2026-08"}]},
        {"id": "laser", "name": "雷射照明、投影與雷射電視", "icon": "🔦",
         "lead": "藍光雷射把數瓦的光集中在不到 1 mm² 的點上，矽膠會黃化碳化，因此必須用螢光玻璃、螢光陶瓷或單晶等全無機轉換器。",
         "numbers": ["矽膠導熱 ≈ 0.2 W/(m·K)", "螢光玻璃 ≈ 3", "YAG:Ce 陶瓷 5–10", "Al₂O₃ 複合陶瓷 12–37 W/(m·K)", "白光雷射封裝亮度 1,000–1,300 cd/mm²", "雙螢光粉陶瓷 782.5 lm/mm²（LPR 2025）"],
         "points": [
             "2014 年 BMW i8 與 Audi R8 讓雷射頭燈量產（OSRAM 供應模組），但 2024 年 BMW 與 Audi 都表明不再發展：美國 FMVSS 108 把頭燈光強限制在 150,000 cd，雷射遠光的有效距離從約 600 m 降到約 250 m，矩陣 LED 已追上。",
             "雷射白光光源仍在推進：Nichia 2025 年推出 GigaWhite（亮度約 LED 的 10 倍，內建感測器偵測螢光體破裂）、Kyocera SLD Laser 的 LaserLight SMD；Sony、大阪大學與岩崎電氣 2026 年展出藍光 VCSEL 陣列激發螢光體的分割式照明。",
             "雷射投影機與雷射電視用旋轉的螢光粉輪散熱；光峰科技的 ALPD 技術在中國雷射投影光源市占曾達 98.6%（2019），Hisense 2025 年雷射電視全球市占 70.3%；SCHOTT 供應陶瓷轉換輪，Barco 2015 年推出首台 18,000 流明雷射螢光影院投影機。",
             "研究前沿是高導熱複合陶瓷與快速燒結：2025 年 Ca-α-SiAlON:Eu＋YAG:Ce 雙螢光粉陶瓷做出 2278 K 暖白光（熱導率 > 17.6 W/(m·K)），2026 年 Nature Communications 以 10 秒級快速燒結製得緻密且細晶的 LuAG:Ce 陶瓷並展示可見光通訊；紅光轉換器仍是短板。"],
         "materials": ["YAG:Ce 陶瓷／單晶", "LuAG:Ce 陶瓷", "螢光玻璃（PiG）", "CASN 紅光薄膜", "α-SiAlON 陶瓷"],
         "players": ["Nichia", "ams OSRAM", "Lumileds（Lumiramic）", "SCHOTT", "日本電氣硝子", "Kyocera SLD Laser", "光峰科技", "Barco", "Hisense"],
         "srcs": [{"url": "https://pubs.aip.org/aip/apl/article/118/21/210503/1061193/Phosphor-converters-for-laser-driven-light-sources", "name": "Applied Physics Letters 2021（綜述）"}, {"url": "https://www.lightnowblog.com/2025/01/nichia-releases-gigawhite-white-laser-smd/", "name": "LightNOW 2025（GigaWhite）"}, {"url": "https://www.bmwblog.com/2024/07/29/bmw-rules-out-new-cars-laser-headlights/", "name": "BMWBLOG 2024（雷射頭燈退場）"}, {"url": "https://onlinelibrary.wiley.com/doi/abs/10.1002/lpor.202402144", "name": "Laser & Photonics Reviews 2025（雙螢光粉陶瓷）"}]},
        {"id": "auto", "name": "車用照明與車用顯示", "icon": "🚗",
         "lead": "頭燈需要高亮度與耐高溫的轉換器，座艙顯示需要車規等級的色彩與可靠度，兩者都是螢光粉的高價值市場；畫素化頭燈把螢光片的幾何精度推到新高。",
         "numbers": ["日本電氣硝子螢光玻璃耐熱 > 500 °C、85/85 測試 5,000 小時", "AEC-Q102：高溫工作壽命以接面溫度 125 °C 為條件", "EVIYOS 2.0：25,600 畫素、40 µm 間距（2023）", "µPLS：16,384 畫素（Nichia＋Infineon 2023）", "2026 年車用 LED 市場 34.51 億美元（TrendForce）"],
         "points": [
             "轉換體從矽膠混粉走向玻璃螢光片（PiG，約 750 °C 即可製作、比陶瓷便宜）與陶瓷螢光片（導熱好，Lumileds Lumiramic 貼合薄膜覆晶晶片，白點精準落在黑體曲線、大幅減少分 bin）。",
             "自適應遠光燈（ADB）在美國 2022-02-22 起獲 FMVSS 108 開放；ams OSRAM EVIYOS 2.0 已用於 VW Touareg、Nio ET9 等車款，Nichia 2025 年推出板上螢光粉的 DominoPLS 與 µPLS Mini，Lumileds 2025 年 Altilon SMD-A 發光區間距縮到 70 µm。",
             "車用 LCD 背光：KSF 授權方稱美國展廳車用顯示器逾四成、Display Week 2025 車用 LCD 逾七成採用 KSF，BMW、VW、Porsche、Audi、Mercedes、Volvo 採用率 85–100%；2026 年 Edison Innovations 把 KSF 授權給億光、富采、Lumens 等廠，明確鎖定車用中控與抬頭顯示。BOE 2025 年展出 44.8 吋 2,850 分區 7,000 nits 的 Mini LED 抬頭顯示器，歐美車廠多用友達與群創的 Mini LED 模組。",
             "無鎘量子點 2025 年取得首家大型車廠設計案（Nanosys／昭榮）；歐盟含鎘量子點豁免到期後，車用顯示的紅光選項是 KSF 或 InP 量子點。"],
         "materials": ["YAG:Ce 螢光玻璃", "(Y,Gd)AG:Ce 陶瓷", "KSF", "β-SiAlON", "InP 量子點"],
         "players": ["ams OSRAM", "Nichia", "Lumileds", "HELLA／Marelli", "日本電氣硝子", "大周電子材料", "BOE", "友達", "群創"],
         "srcs": [{"url": "https://www.neg.co.jp/product/ep/lumiphous", "name": "日本電氣硝子 Lumiphous"}, {"url": "https://ams-osram.com/news/press-releases/ams-osram-eviyos-2.0-led", "name": "ams OSRAM EVIYOS 2.0（2023）"}, {"url": "https://www.ledinside.com/interview/2026/8/2026_08_31_01", "name": "LEDinside 2026-08（Edison 專訪）"}, {"url": "http://www.aecouncil.com/Documents/AEC-Q102_Rev_A.pdf", "name": "AEC-Q102 Rev A"}]},
        {"id": "hcl", "name": "健康照明與全光譜", "icon": "🌤️",
         "lead": "用螢光粉配方調整光譜形狀，補上青色缺口、去掉藍光尖峰，讓光更接近日光並配合人體生理節律。共同語言是 CIE S 026 的黑視素等效日光照度（melanopic EDI），黑視素感光峰值約在 490 nm 的青色。",
         "numbers": ["WELL v2：melanopic EDI ≥ 136 lux（第一級）／≥ 250 lux（第二級）", "IES RP-46-25：白天眼高 ≥ 250 lux mel-EDI", "典型 LED 的 m-DER：2700K 約 0.45、4000K 約 0.75、6500K 約 1.18", "日亞 Optisolis Ra 99、Rf 98／Rg 99", "SunLike CRI 97、Rf 96–97", "Bridgelux Thrive 98 R9 > 90", "紫光方案效率約 80–120 lm/W"],
         "points": [
             "首爾半導體 SunLike（2017）：紫光晶片激發 Niterra Materials（原東芝材料）TRI-R 三色螢光粉，光譜沒有 450 nm 尖峰；2025 年公司仍以「照明新典範」推廣，健康效益宣稱未逐一查證。Soraa（2008 年中村修二創立）的紫光 VP3 三螢光粉是更早的先例，2020 年資產由 Ecosense 收購。",
             "日亞 Vitasolis（2019）以螢光粉增加 470–520 nm 青光比例，相同照度下黑視素照度高約 10%；Samsung LM302N（2020）以 DAY／NITE 兩種光譜調整 M/P 比；Bridgelux Thrive 用寬頻藍光晶片填補 480 nm 缺口（Rf 96–98）。",
             "藍光安全：IEC 62471 把一般照明多歸為 RG0／RG1，歐盟 SCHEER 2018 認為正常使用的 LED 對一般健康人群無直接危害證據，法國 ANSES 2019 則建議家用選暖白光、限制兒童睡前螢幕；台灣 CNS 15592 自 2014 年起要求 LED 球泡檢驗光生物安全。",
             "代價是效率：紫光全轉換多一層斯托克斯損失，且高顯色本身就會損失兩成左右光效；紫光方案與藍光方案在相同 CRI 下的實測差距，2025–2026 年缺乏第三方公開比較。",
             "閃爍不是螢光粉能解決的：YAG 類螢光粉衰減僅奈秒級，濾不掉驅動器的閃爍；IEEE 1789 建議調變頻率 > 1,250 Hz，歐盟 2019/2020 要求 Pst LM ≤ 1.0、SVM ≤ 0.4。"],
         "materials": ["BAM 藍粉", "青色粉", "LuAG／β-SiAlON", "SCASN／KSF", "TRI-R 三色粉"],
         "players": ["首爾半導體", "Niterra Materials", "Nichia", "Bridgelux", "Samsung LED", "Lumileds"],
         "srcs": [{"url": "https://standard.wellcertified.com/v2/light/circadian-lighting-design", "name": "WELL v2 L03"}, {"url": "https://health.ec.europa.eu/publications/potential-risks-human-health-light-emitting-diodes-leds_en", "name": "歐盟 SCHEER 2018"}, {"url": "https://www.anses.fr/en/content/leds-ansess-recommendations-limiting-exposure-blue-light", "name": "法國 ANSES 2019"}, {"url": "https://www.nichia.co.jp/en/newsroom/2019/2019_051701.html", "name": "Nichia 2019（Vitasolis）"}, {"url": "https://www.bridgelux.com/blog/bridgelux-releases-thrive-93-delivering-lighting-s-closest-match-natural-light-while-saving", "name": "Bridgelux Thrive"}]},
        {"id": "horti", "name": "園藝與農業照明", "icon": "🌱",
         "lead": "植物 400–700 nm 都能用（McCree 曲線，量子產率雙峰在 620 與 440 nm），紅光 660 nm 與遠紅光 730 nm 切換光敏素控制開花與伸長。園藝燈以每焦耳光子數（µmol/J）計量，純紅光多靠 AlGaInP 晶片直接發光，白光部分才靠螢光粉。",
         "numbers": ["ams OSRAM Hyper Red 660 nm：4.32 µmol/J @700 mA、電光效率 78.8%（直接發光）", "Samsung LM301H EVO 白光（螢光粉）：3.14 µmol/J", "Signify GreenPower toplighting：4.0–4.3 µmol/J", "Fluence VYPR 4：2.7–3.6 µmol/J", "園藝照明市場 2024 年估 46–88 億美元"],
         "points": [
             "主流方案是「白光 LED（螢光粉）＋ 660 nm 紅光晶片」，因為工作人員需要看得清楚植物狀態；Nichia Hortisolis 把藍、綠、紅、遠紅光都包進一顆螢光粉封裝。Signify 2025 年推出紅／藍／白／遠紅四通道 GreenPower。",
             "深紅與遠紅螢光粉主要仍在研究階段：1950 年代的氟鍺酸鎂:Mn⁴⁺（660 nm）是經典；Cr³⁺ 遠紅粉如 GAO:Cr³⁺ 內量子效率 98.3%、250 °C 零熱猝滅，LaAlO₃–Al₂O₃:Cr³⁺ 峰值 735 nm，GAGG:Cr³⁺ pc-LED 電光轉換效率 20.6%；是否已被主要園藝 LED 廠量產，搜尋未能確認。",
             "光譜轉換農膜與溫室玻璃：Eu³⁺ 錯合物農膜把紫外轉紅光（植物高度 1.2 倍、生物量 1.4 倍，Sci. Rep. 2022）；UbiQD 量子點溫室玻璃在 USDA 資助的 UC Davis 冬季萵苣試驗鮮重 +37.8%；但 2026 年研究指出效果「依季節與品種而定」，缺乏跨地區長期試驗。",
             "2024 年 McCree 曲線更新指出 700–750 nm 遠紅光可透過 Emerson 增強效應驅動光合作用，因此有人提出 ePAR（400–750 nm）。"],
         "materials": ["Mn⁴⁺ 氧化物（660 nm）", "Cr³⁺ 遠紅光粉（730 nm）", "SCASN", "YAG:Ce", "Eu³⁺ 農膜", "量子點農膜"],
         "players": ["ams OSRAM", "Signify", "Fluence", "Samsung LED", "Nichia", "Cree LED", "UbiQD"],
         "srcs": [{"url": "https://www.sciencedirect.com/science/article/pii/S101113442400229X", "name": "McCree 曲線更新（2024）"}, {"url": "https://ams-osram.com/news/press-releases/oslon-square-hyper-red-led", "name": "ams OSRAM Hyper Red（2023）"}, {"url": "https://samsung.com/led/about-us/news-events/news/news-detail-65", "name": "Samsung LM301H EVO"}, {"url": "https://www.sciencedirect.com/science/article/abs/pii/S0022286025002534", "name": "J. Mol. Struct. 2025（Cr³⁺ 植物燈綜述）"}, {"url": "https://www.prnewswire.com/news-releases/ubiqd-quantum-dot-glass-boosts-crop-yield-efficiency-and-sustainability-in-usda-funded-study-302575489.html", "name": "UbiQD 2025"}]},
        {"id": "nir", "name": "近紅外感測", "icon": "🔬",
         "lead": "藍光晶片加 Cr³⁺ 螢光粉就是一顆迷你寬頻近紅外光源，可裝進手機大小的裝置做光譜分析；2024–2026 年是螢光粉領域論文成長最快的方向。",
         "numbers": ["OSRAM SFH 4735（2016）：全球首顆藍光激發螢光粉的寬頻紅外 LED，650–1050 nm", "SFH 4737（2020）：74 mW @350 mA、1.6×1.6×0.9 mm", "Lumileds IR ONYX（2019）：650–1100 nm 平坦光譜", "Ca₃Sc₂Si₃O₁₂:Cr³⁺ IQE 92.3%、150 °C 保持 97.4%、109.9 mW @520 mA（LSA 2020）", "GSGG:Cr³⁺ IQE 98.6% 但吸收效率僅 23.3%"],
         "points": [
             "用途：水果糖度與成熟度（Felix F-750、SCiO 等手持儀在 740–1070 nm 評估）、食品含水量與脂肪、藥物真偽、皮膚血氧與生醫影像、夜視、防偽。",
             "材料主線是 Cr³⁺ 石榴石（CSSG、GSGG、Ca₂YHf₂Ga₃O₁₂ 794 nm）、硼酸鹽（ScBO₃ 800 nm、半高寬 120 nm）、磷酸鹽（LiInP₂O₇ 860 nm，共摻 Yb³⁺ 拓寬至 225 nm）；「量子效率高不等於出光多」，外量子效率受藍光吸收限制。",
             "NIR-II／III（1000–1850 nm）靠 Cr³⁺→Ni²⁺ 能量傳遞（Ca₃Ga₂Ge₃O₁₂ 峰值 1470 nm，EQE 13.3%）、Fe³⁺ 鹵化物（PLQY 17.29%）與 Er³⁺（臺大 MgGa₂O₄:Cr,Er 1547 nm，IQE 68.8%），效率仍偏低但進展快；2026 年機器學習引導的 Mo⁴⁺ 鹵化物在 920 nm 達 IQE 92.4%。",
             "衍生應用：比率式發光測溫（Mn⁴⁺ 靈敏度高於 Cr³⁺，YAG:Mn⁴⁺,Eu³⁺ 達 5.06 %/K）；ZnGa₂O₄:Cr³⁺ 700 nm 近紅外長餘輝可在體內用紅光重複充能做無背景成像。",
             "台灣（臺大劉如熹、臺師大胡淑芬、北科大林群哲）、中國（華南理工、廈門大學）團隊在這個領域發表量大；ams OSRAM 是否有 SFH 4737 之後的新一代產品，搜尋未能確認。"],
         "materials": ["Cr³⁺ 石榴石", "ScBO₃:Cr³⁺", "Cr³⁺/Yb³⁺ 共摻雜", "Cr³⁺/Ni²⁺（NIR-II）", "MgGa₂O₄:Cr,Er（NIR-III）"],
         "players": ["ams OSRAM", "Lumileds", "臺灣大學", "華南理工大學", "廈門大學"],
         "srcs": [{"url": "https://ams-osram.com/products/leds/ir-leds/osram-oslon-p1616-sfh-4737", "name": "ams OSRAM SFH 4737"}, {"url": "https://www.nature.com/articles/s41377-020-0326-8", "name": "Light: Science & Applications 2020（CSSG）"}, {"url": "https://lumileds.com/lumileds-announces-luxeon-ir-onyx-a-broadband-infrared-emitter-for-hyperspectral-imaging-applications/", "name": "Lumileds IR ONYX（2019）"}, {"url": "https://onlinelibrary.wiley.com/doi/10.1002/lpor.202400447", "name": "Laser & Photonics Reviews 2024（NIR-II）"}]},
        {"id": "uv", "name": "紫外光：光療、消毒與防偽", "icon": "🟣",
         "lead": "螢光粉也能「往短波走」：Gd³⁺ 發 311 nm 窄帶 UVB 是乾癬、白斑光療燈的核心；Pr³⁺、Bi³⁺ 的 UVC／UVB 螢光粉是研究前沿；但商用消毒仍以 AlGaN UVC LED 與 222 nm KrCl 準分子燈直接發光為主。",
         "numbers": ["Gd³⁺ 311–313 nm（皮膚紅斑敏感峰值約 297 nm）", "Nichia NCSU434D 280 nm UVC LED 電光效率 7.4%（2024-12 量產）", "市售 UVC LED 電光效率多在 3–10%", "ACGIH 2022：222 nm 眼睛 161 mJ/cm²、皮膚 479 mJ/cm²", "BaSc₂Ge₃O₁₀:Bi³⁺ IQE 81%、EQE 49%（2023）"],
         "points": [
             "光療：傳統 UVB 燈管用 LaPO₄:Ce³⁺,Gd³⁺，近年 Sr₃Gd₂Si₆O₁₈:Pr³⁺、Ca₂MgSi₂O₇:Gd³⁺ 等新粉可與商用粉比擬（2024 年有專門綜述）；308 nm UVB LED 與準分子雷射／燈療效相當（2023 年半身隨機試驗）。",
             "消毒：Pr³⁺ 的 4f5d 躍遷可發 220–260 nm，Y₂SiO₅:Pr³⁺ 在 460 nm 雷射下以上轉換發 247／258 nm，Sr₂P₂O₇:Pr³⁺ 經 X 光充能可持續發 222 nm 餘輝超過 24 小時（2023）；但上轉換效率遠低於 UVC LED，仍屬研究階段。2026 年 Light: Science & Applications 發表金屬離子摻雜無機紫外螢光粉綜述。",
             "防偽：鈔票與證件用只在紫外燈下可見的螢光，Eu³⁺ 錯合物 612 nm 紅光、CaMoO₄:Tb³⁺ 544 nm 綠光，混入 SrAl₂O₄:Eu,Dy 產生餘輝，或以 254／365 nm 雙波長呈不同顏色；歐洲的 LWB 是這類防偽螢光粉的專業供應商。",
             "紫外「提醒」：美國專利 11788886 在可見光感測器上方放 UV 螢光粉，把紫外轉成可見光讓一般環境光感測器讀紫外劑量。"],
         "materials": ["LaPO₄:Ce,Gd", "Pr³⁺ 矽酸鹽／磷酸鹽", "Bi³⁺ 鍺酸鹽", "Eu³⁺／Tb³⁺ 防偽墨"],
         "players": ["Nichia（UVC LED）", "Crystal IS", "Far UV Technologies", "LWB"],
         "srcs": [{"url": "https://pubmed.ncbi.nlm.nih.gov/39157368/", "name": "Gd³⁺ 光療燈螢光粉綜述（2024）"}, {"url": "https://www.nichia.co.jp/en/newsroom/2025/2025_012901.html", "name": "Nichia NCSU434D（2025-01）"}, {"url": "https://pubs.rsc.org/en/content/articlelanding/2023/qi/d3qi01253k", "name": "Inorg. Chem. Front. 2023（Pr³⁺ UVC）"}, {"url": "https://onlinelibrary.wiley.com/doi/full/10.1002/agt2.15", "name": "Aggregate 2021（防偽發光綜述）"}]},
        {"id": "glow", "name": "夜光、安全與應力發光", "icon": "🌙",
         "lead": "長餘輝螢光粉在關燈後仍能持續發光數小時，用於逃生標示、手錶與道路標線；應力發光材料受力時發光，可「看見」結構受力分布。",
         "numbers": ["SrAl₂O₄:Eu,Dy 比 ZnS:Cu,Co 亮約 10 倍，餘輝可達十幾到 30 小時（廠商標示）", "安全標示門檻 0.32 mcd/m²（DIN 67510／ISO 17398）", "理想陷阱深度約 0.6–0.7 eV", "Nemoto 蓄光顏料全球市占約七至八成（維基百科）", "中國 2023 年長餘輝粉產量 240 噸"],
         "points": [
             "1993 年根本特殊化學為取代含鐳夜光塗料發明 LumiNova（1994 年專利，1996 年 Matsuzawa 論文），1998 年與瑞士 RC Tritec 合資推出 Super-LumiNova，2000 年起瑞士錶廠陸續由氚轉用；大連路明是中國稀土蓄光材料的開拓者。",
             "根特大學 LumiLab 把長餘輝材料視為「光學電池」，以陷阱深度分布預測餘輝時間；Dorenbos 的 VRBE 圖是設計陷阱深度的標準工具。",
             "近紅外長餘輝材料（如 ZnGa₂O₄:Cr³⁺）可先充光再注入體內成像，避免生物組織自體螢光干擾；2025 年用它標記水蚤體內的奈米塑膠。",
             "光激勵發光（photostimulated）材料是資訊儲存與生醫成像的新方向，中科院福建物構所 2026 年發表綜述；長春應化所開發餘輝壽命與交流頻率匹配的 AC-LED 螢光粉補償閃爍。"],
         "materials": ["SrAl₂O₄:Eu,Dy", "Sr₄Al₁₄O₂₅:Eu,Dy", "CaAl₂O₄:Eu,Nd", "ZnGa₂O₄:Cr", "ZnS:Mn（應力發光）"],
         "players": ["根本特殊化學", "RC Tritec", "大連路明", "LWB", "弘大貿易（台灣代理）"],
         "srcs": [{"url": "https://www.nemoto.co.jp/en/luminouspigment/", "name": "Nemoto 官網"}, {"url": "https://iopscience.iop.org/article/10.1149/1.1837067", "name": "J. Electrochem. Soc. 1996（Matsuzawa）"}, {"url": "https://pubs.aip.org/aip/jap/article/128/24/240903/1061711/Persistent-phosphors-for-the-future-Fit-for-the", "name": "J. Appl. Phys. 2020（Smet）"}, {"url": "https://pubs.rsc.org/en/content/articlelanding/2017/nr/c7nr01209h", "name": "Nanoscale 2017（ZnGa₂O₄:Cr）"}]},
        {"id": "medical", "name": "醫療影像與輻射偵測（閃爍體）", "icon": "🩻",
         "lead": "閃爍體把 X 光、γ 射線轉成可見光，是數位 X 光平板、電腦斷層、正子造影與安檢的核心，本質上也是螢光材料；市場由濱松、日立金屬、Luxium（原 Saint-Gobain）三強主導。",
         "numbers": ["無機閃爍體市場 2025 年約 6.4 億美元，前三大約 44%（Research and Markets）", "LaBr₃:Ce：662 keV 能量解析度 2.85%、61,000 光子/MeV（Delft 2001）", "奈米光子閃爍體光產率提高 6 倍（Nat. Commun. 2025）"],
         "points": [
             "醫療平板主流：CsI:Tl 以蒸鍍做成柱狀晶體，可做厚而保持解析度；Gd₂O₂S:Tb 粉末塗布成本低。正子造影用 LYSO:Ce 單晶，GAGG:Ce 石榴石是近年高能物理與安檢的新材料。",
             "鈣鈦礦與奈米閃爍體是 2020 年代的研究熱點：2025 年硫屬玻璃光子晶體自組裝閃爍體使光產率提高 6 倍，銅鹵化物鈣鈦礦奈米晶玻璃纖維陣列實現 5 公尺遠距高解析 X 光成像。",
             "閃爍體用到的釓、鎦、鋱在 2025 年中國稀土管制名單內，是醫療影像供應鏈少被討論的風險。"],
         "materials": ["CsI:Tl", "Gd₂O₂S:Tb", "LYSO:Ce", "GAGG:Ce", "BGO", "LaBr₃:Ce"],
         "players": ["Luxium（原 Saint-Gobain）", "濱松", "日立金屬", "CRYTUR", "上海矽酸鹽研究所"],
         "srcs": [{"url": "https://aapm.onlinelibrary.wiley.com/doi/abs/10.1002/mp.13791", "name": "Medical Physics 2019"}, {"url": "https://www.researchandmarkets.com/report/inorganic-scintillators", "name": "Research and Markets（無機閃爍體）"}, {"url": "https://www.nature.com/articles/s41467-025-60953-5", "name": "Nature Communications 2025（奈米光子閃爍體）"}]},
        {"id": "bio", "name": "生醫與上轉換", "icon": "🧬",
         "lead": "把近紅外光「往上」轉成可見光的上轉換奈米粒子（NaYF₄:Yb,Er 等）是生物影像、光遺傳與防偽的工具；長餘輝奈米探針與發光測溫則把螢光粉帶進活體。",
         "numbers": ["ZnGa₂O₄:Cr³⁺ 奈米探針對 avidin 偵測極限約 150 pM", "KIST 上轉換單粒子 RGB：色域 NTSC 94.2%", "Rb₃Y(PO₄)₂:Eu²⁺ 高摻雜仍高效（LSA 2025）"],
         "points": [
             "上轉換材料靠 Yb³⁺ 吸收 980 nm 再傳給 Er³⁺／Tm³⁺ 發可見光，激發光穿透深、無自體螢光；新加坡國立大學劉曉剛 2021 年在 Nature Photonics 報導表面重構誘發的上轉換增強，KIST 以多層核殼粒子做出單粒子 RGB 上轉換與 3D 體積顯示概念。",
             "近紅外長餘輝探針（ZnGa₂O₄:Cr³⁺）可先充光再注入體內，用低於帶隙的紅光在體內重複充能；2025 年用於標記水蚤體內奈米塑膠。",
             "發光測溫：Mn⁴⁺ 與 Cr³⁺ 同為 d³ 組態，Mn⁴⁺ 相對靈敏度較高（YAG:Mn⁴⁺,Eu³⁺ 5.06 %/K），Cr³⁺ 低溫不確定度更小（20 K 時 0.1 K）。",
             "生醫用的近紅外 pc-LED（皮膚血氧、組織成像）與 NIR-II／III 窗口螢光粉共用同一批材料，見「近紅外感測」。"],
         "materials": ["NaYF₄:Yb,Er／Tm", "ZnGa₂O₄:Cr³⁺", "YAG:Mn⁴⁺,Eu³⁺（測溫）"],
         "players": ["新加坡國立大學", "KIST", "雪梨科技大學", "根特大學"],
         "srcs": [{"url": "https://pubs.rsc.org/en/content/articlelanding/2017/nr/c7nr01209h", "name": "Nanoscale 2017（ZnGa₂O₄:Cr 探針）"}, {"url": "https://www.sciencedirect.com/science/article/abs/pii/S0025540821005055", "name": "Materials Research Bulletin 2021（發光測溫）"}, {"url": "https://www.sciencetimes.co.kr/nscvrg/view/menu/250?searchCategory=222&nscvrgSn=260109", "name": "Science Times（KIST 上轉換）"}]},
    ],
}
