# -*- coding: utf-8 -*-
"""研究前沿：2024–2026 年最活躍的題目，說明為什麼難、為什麼重要。"""

FRONTIER = {
    "lead": "螢光粉研究的核心矛盾只有幾個：要窄又要穩、要紅又要亮、要小又要吸得住光、要耐熱又要便宜。下面是全球團隊正在攻的九個方向。",
    "items": [
        {"id": "narrow-red", "title": "窄頻紅粉：把紅光集中在人眼看得到的地方",
         "lead": "傳統氮化物紅粉譜帶 90 nm 以上，能量浪費在深紅區；SLA（650 nm／50 nm）、SALON（614 nm／48 nm）與 UCr₄C₄ 型家族把半高寬壓到 50 nm 以下。",
         "why": "同樣的顯色品質可以少耗一到兩成的電，是 DOE 點名的最大槓桿；但這類剛性結構普遍怕水、合成困難，量產與商用進度仍不透明。",
         "points": ["2025 年 Laser & Photonics Reviews 綜述總結 UCr₄C₄ 型材料十年進展與耐濕弱點", "2026 年 NIMS 以單顆粒診斷法發現雙窄帶的 SrLi₃AlO₄:Eu²⁺", "2025 年浸水 25 天不衰的氯硼酸鹽 NaBa₄Al₂B₈O₁₈Cl₃:Eu²⁺ 直接回應怕水問題"],
         "groups": ["LMU 慕尼黑 Schnick", "Lumileds", "ams OSRAM", "華南理工 夏志國", "NIMS"],
         "srcs": [{"url": "https://onlinelibrary.wiley.com/doi/10.1002/lpor.202500740", "name": "Laser & Photonics Reviews 2025"}, {"url": "https://doi.org/10.1080/14686996.2026.2650843", "name": "STAM 2026（SrLi3AlO4:Eu）"}]},
        {"id": "ksf-stability", "title": "讓 KSF 不怕水、衰減更快",
         "lead": "KSF 的 [MnF₆]²⁻ 基團遇水會水解，Mn⁴⁺ 的自旋禁制躍遷又讓衰減長達約 8 毫秒。核殼、表面重構與新氟氧化物是解方。",
         "why": "KSF 已是廣色域背光的基礎設施（累計出貨逾 1,000 億顆），可靠度每提升一點就是車用與高刷新率顯示的新市場。",
         "points": ["2024 年 H₂NbF₇ 兩步表面重構：IQE 98.9%，85 °C／85% RH 六天幾乎不衰", "2024 年 NaClO 一步處理長出 <5 nm 複合殼層，60 天保有 86%", "GE 新一代 TriGain 衰減時間縮短 30%、顆粒縮小 10 倍；學界開發 Rb₂MoO₂F₄:Mn⁴⁺ 等快衰減替代物"],
         "groups": ["GE／Edison Innovations", "多所中國大學", "臺灣大學"],
         "srcs": [{"url": "https://pubs.acs.org/doi/10.1021/acsami.4c12727", "name": "ACS AMI 2024"}, {"url": "https://advanced.onlinelibrary.wiley.com/doi/10.1002/adom.202401498", "name": "Advanced Optical Materials 2024"}]},
        {"id": "laser-ceramic", "title": "雷射等級的螢光陶瓷與螢光玻璃薄膜",
         "lead": "雷射把數十 W/mm² 的藍光打在螢光體上，導熱率決定一切：Al₂O₃ 複合陶瓷、透明陶瓷@藍寶石、核殼式陶瓷晶圓、秒級快速燒結輪番登場。",
         "why": "車燈、投影、可見光通訊都需要「小而亮」的光源；紅光轉換器仍是短板，紅光氮化物很難燒成緻密陶瓷。",
         "points": ["2025 年透明陶瓷@藍寶石達 36.9 W/(m·K)、5,902 lm", "2025 年核殼式 YAG:Ce@Al₂O₃ 晶圓亮度 3,900 lm/mm²", "2026 年 Nature Communications：機器學習加脈衝快速燒結 10 秒燒成 LuAG:Ce 陶瓷，效率 +31%", "2025 年高顯色雷射白光 CRI 95.4、220 lm/W"],
         "groups": ["廈門大學 謝榮軍", "浙江大學 邱建榮", "溫州大學", "華南理工", "Fraunhofer", "SCHOTT"],
         "srcs": [{"url": "https://advanced.onlinelibrary.wiley.com/doi/10.1002/advs.202505232", "name": "Advanced Science 2025"}, {"url": "https://www.nature.com/articles/s41467-026-74741-2", "name": "Nature Communications 2026"}]},
        {"id": "microled", "title": "Micro LED 色轉換：把螢光粉做小",
         "lead": "畫素小於 10–20 µm 時，傳統十幾微米的螢光粉顆粒塞不進去、吸收也不夠，量子點光阻與噴墨成為主流；螢光粉陣營則開發次微米高吸收 KSF 墨水。",
         "why": "Micro LED 是台灣顯示產業押注最深的技術之一（群創、錼創、友達、工研院都走藍光加量子點路線），色轉換層的效率與壽命直接決定產品競爭力。",
         "points": ["2025 年量子點微球 Micro LED 綠光 EQE 40.8%、紅光 22.1%", "藍光漏光靠 TiO₂ 等散射粒子拉長光程解決", "Edison 與 Current Chemicals 開發次微米 KSF 墨水與發光彩色濾光片"],
         "groups": ["錼創", "群創", "工研院", "Edison Innovations", "多所中國大學"],
         "srcs": [{"url": "https://www.nature.com/articles/s41377-020-0268-1", "name": "Light: Science & Applications 2020"}, {"url": "https://pubs.rsc.org/en/content/articlelanding/2025/nr/d4nr03925d", "name": "Nanoscale 2025"}]},
        {"id": "ai", "title": "AI 與資料驅動的材料發現",
         "lead": "從 2018 年機器學習篩選高熱穩定基質，到 2023 年 GNoME 預測數十萬種新晶體，再到 2025 年直接用機器學習找到半高寬 44 nm 的窄頻綠粉。",
         "why": "螢光粉的組成空間太大，靠試誤合成一年只能做幾十種；資料庫加模型可以先把候選縮到幾個，再交給實驗室驗證。",
         "points": ["2025 年 Chemical Engineering Journal：機器學習發現 CsRbKNa(Li₃SiO₄)₄:Eu²⁺（530 nm、44 nm）", "NIMS 單顆粒診斷法：從混相粉末挑單顆晶粒直接分析，2014 年提出至今仍在產出新材料", "2026 年 Nature Communications 用機器學習優化陶瓷燒結參數"],
         "groups": ["休士頓大學 Brgoch", "華南理工 夏志國", "NIMS", "Google DeepMind", "Materials Project"],
         "srcs": [{"url": "https://www.sciencedirect.com/science/article/abs/pii/S138589472506557X", "name": "Chemical Engineering Journal 2025"}]},
        {"id": "cyan", "title": "青色缺口與全光譜",
         "lead": "藍光晶片（450 nm）與 YAG（550 nm）之間的 480–500 nm 是白光 LED 的凹陷。Ce³⁺ 硼酸鹽、石榴石與 Eu²⁺ 矽酸鹽陶瓷正在填補。",
         "why": "顯色指標 R12、人因照明的黑視素刺激都落在這段；補上它才能宣稱「接近日光」。",
         "points": ["Ba₂Y₅B₅O₁₇:Ce³⁺ 外部量子產率 70%", "2026 年 AFM：青色 Li₂CaSiO₄:Eu²⁺ 陶瓷（482 nm、30 nm）讓紫光雷射全光譜照明達 Ra 96.5", "產品面：Nichia Vitasolis／Optisolis、Bridgelux Thrive、首爾 SunLike"],
         "groups": ["多所中國大學", "Nichia", "Bridgelux"],
         "srcs": [{"url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC10616965/", "name": "PMC 2023 綜述"}, {"url": "https://advanced.onlinelibrary.wiley.com/doi/10.1002/adfm.202515542", "name": "Advanced Functional Materials 2026"}]},
        {"id": "nir", "title": "近紅外螢光粉：更亮、更寬、更耐熱",
         "lead": "Cr³⁺ 螢光粉讓 LED 變成光譜儀光源，研究目標是提高輸出功率（目前商品約 74 mW）、拓寬到 1000 nm 以上（Ni²⁺、Fe³⁺、Yb³⁺）、並降低熱猝滅。",
         "why": "手機、穿戴裝置與農業檢測都想要不需要鹵素燈的小型近紅外光源；這也是不依賴稀土的路線。",
         "points": ["2025 年：RbAl₃P₆O₂₀:Cr³⁺ 峰值 785 nm、IQE 60%、150 °C 保留 90%，封裝後 120 mA 輸出 27.9 mW", "2025 年：MgTiO₃:Cr³⁺ 峰值 866 nm、半高寬超過 200 nm；SrGe₄O₉:Cr³⁺ 發光橫跨 650–1250 nm、量子產率 66.9%", "Cr³⁺/Yb³⁺ 共摻石榴石把光譜延伸到 1000 nm；AlF₃:Cr³⁺ 等氟化物主打高溫不衰減", "台灣與中國團隊在此領域發表量居全球前列"],
         "groups": ["臺灣大學 劉如熹", "華南理工 夏志國", "廈門大學", "ams OSRAM"],
         "srcs": [{"url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC10142842/", "name": "PMC 綜述（近紅外螢光粉）"}]},
        {"id": "zero-tq", "title": "零熱猝滅與高溫穩定",
         "lead": "LED 與雷射工作時螢光粉可超過 150 °C。SLA 在 300–600 K 幾乎不衰減，2017 年 Nature Materials 提出用缺陷能階補償的「零熱猝滅」概念。",
         "why": "同時具備高量子效率、窄頻與零熱猝滅的材料仍未出現，是材料設計的聖杯之一。",
         "points": ["2020 年 Chem. Mater. 把交叉弛豫與熱游離兩種猝滅機制統一成可預測模型", "2024 年低熱膨脹的 Al₂(WO₄)₃:Eu,Tb 也達零熱猝滅"],
         "groups": ["多所韓國、中國、德國大學"],
         "srcs": [{"url": "https://pubs.acs.org/doi/10.1021/acs.chemmater.0c02231", "name": "Chemistry of Materials 2020"}]},
        {"id": "rare-earth-free", "title": "少稀土、無稀土與供應鏈韌性",
         "lead": "KSF（錳）、Cr³⁺ 近紅外粉、Mn⁴⁺ 氧化物都不含稀土；螢光燈退場也讓鋱、銪的需求結構改變。",
         "why": "中國掌握絕大多數稀土精煉，2023 年起的出口管制讓各國重新檢視 LED 供應鏈；每顆 LED 的稀土用量雖小，但釔、鈰、銪、鎦缺一不可。",
         "points": ["日本、歐盟、美國推動稀土回收與替代材料計畫", "Mn²⁺／Bi³⁺ 等非稀土活化劑的研究持續增加"],
         "groups": ["各國政府與研究機構"],
         "srcs": [{"url": "https://www.iea.org/commentaries/the-next-wave-of-led-lighting-smarter-circular-and-more-efficient", "name": "IEA（LED 下一波）"}]},
    ],
}
