# -*- coding: utf-8 -*-
"""名詞解釋：一般讀者在本站會遇到的術語，用白話說明。"""

GLOSSARY = [
    {"term": "Phosphor", "zh": "螢光粉", "explain": "吸收某種光（通常是藍光或紫外光）後放出另一種顏色光的無機粉末。注意它跟化學元素「磷（phosphorus）」無關，中文也常稱「螢光體」。"},
    {"term": "Host", "zh": "基質", "explain": "螢光粉的「骨架」晶體，例如釔鋁石榴石（YAG）、氮化物、氟化物。基質決定活化劑周圍的環境，也就決定了發光顏色與穩定性。"},
    {"term": "Activator", "zh": "活化劑", "explain": "摻在基質裡真正負責發光的離子，通常只占百分之幾。常見的有 Ce³⁺（黃、綠）、Eu²⁺（藍到紅）、Eu³⁺（紅）、Mn⁴⁺（深紅）、Cr³⁺（近紅外）。"},
    {"term": "Sensitizer", "zh": "敏化劑", "explain": "幫忙吸收能量再傳給活化劑的離子，例如上轉換材料中的 Yb³⁺。"},
    {"term": "pc-LED", "zh": "螢光粉轉換型 LED", "explain": "phosphor-converted LED：用藍光或紫光晶片激發螢光粉來產生白光的 LED，今天絕大多數白光 LED 都是這種。"},
    {"term": "Down-conversion", "zh": "下轉換", "explain": "把高能量（短波長）的光轉成低能量（長波長）的光，例如藍光變黃光。多數螢光粉做的是這件事。"},
    {"term": "Stokes shift", "zh": "斯托克斯位移", "explain": "吸收波長與發光波長之間的差距。差距越大，損失成熱的能量越多，這是螢光粉轉換效率的物理上限之一。"},
    {"term": "Stokes loss", "zh": "斯托克斯損失", "explain": "藍光轉成紅光時，一個光子的能量約損失三成，這部分變成熱。窄頻紅粉把紅光集中在人眼敏感的波段，就是為了少浪費一點。"},
    {"term": "YAG", "zh": "釔鋁石榴石", "explain": "Y₃Al₅O₁₂，摻鈰後（YAG:Ce）是最經典的黃色螢光粉。1967 年由飛利浦的 Blasse 與 Bril 報導其發光，1996 年被日亞用來做出白光 LED。"},
    {"term": "Garnet", "zh": "石榴石", "explain": "一大類結構相同的氧化物（YAG、LuAG、GAGG…），可以透過換元素微調發光顏色，是螢光粉與閃爍體最重要的基質家族之一。"},
    {"term": "Nitride phosphor", "zh": "氮化物螢光粉", "explain": "以氮化矽、氮化鋁為骨架的螢光粉（CASN、SCASN、Sr₂Si₅N₈、SLA…），化學鍵強、熱穩定性好，是紅色螢光粉的主力，但要在高溫高壓的氮氣下合成。"},
    {"term": "SiAlON", "zh": "賽隆（矽鋁氧氮）", "explain": "由 Si、Al、O、N 組成的陶瓷，摻 Eu²⁺ 後 β 型發綠光（窄頻，背光用）、α 型發橙黃光。由日本 NIMS 開發，Denka 量產。"},
    {"term": "CASN / SCASN", "zh": "氮化物紅粉", "explain": "CaAlSiN₃:Eu²⁺ 與 (Sr,Ca)AlSiN₃:Eu²⁺ 的簡稱。高顯色暖白 LED 的紅色來源，由 NIMS 與三菱化學於 2000 年代中期推出。"},
    {"term": "KSF / PFS", "zh": "氟矽酸鉀紅粉", "explain": "K₂SiF₆:Mn⁴⁺，發出多條約 5 nm 寬的紅色細線（主峰 631 nm）。GE 以 TriGain 商標推廣，是廣色域背光與高顯色照明的重要紅粉；弱點是怕水氣。"},
    {"term": "SLA / SALON", "zh": "窄頻氮化物紅粉", "explain": "Sr[LiAl₃N₄]:Eu²⁺（2014 年）與 Sr[Li₂Al₂O₂N₂]:Eu²⁺（2019 年），半高寬約 50 nm 的新一代紅粉，由慕尼黑大學 Schnick 團隊與 Lumileds／OSRAM 合作開發。"},
    {"term": "LuAG", "zh": "鎦鋁石榴石", "explain": "Lu₃Al₅O₁₂:Ce³⁺，發綠光，熱穩定性比 YAG 更好，常用於高顯色配方、雷射照明與閃爍體。"},
    {"term": "Ce³⁺", "zh": "三價鈰離子", "explain": "5d→4f 躍遷，發光壽命極短（奈秒級），譜帶寬、可被藍光有效激發，是 YAG、LuAG 的活化劑。"},
    {"term": "Eu²⁺", "zh": "二價銪離子", "explain": "同樣是 5d→4f 躍遷，發光顏色隨基質從藍到紅都有；氮化物紅粉、β-SiAlON 綠粉、夜光粉都靠它。"},
    {"term": "Eu³⁺", "zh": "三價銪離子", "explain": "4f→4f 躍遷，發出 611–620 nm 的紅色細線，是彩色映像管與螢光燈管的紅色來源；但藍光激發效率低，所以 LED 上不常用。"},
    {"term": "Mn⁴⁺", "zh": "四價錳離子", "explain": "在氟化物中發出 630 nm 附近的紅色細線（KSF），在氧化物中則偏深紅（650–660 nm）。不含稀土是它的優點之一。"},
    {"term": "Cr³⁺", "zh": "三價鉻離子", "explain": "在較弱的晶體場中發出 700–1000 nm 的寬頻近紅外光，是近紅外 pc-LED 的核心活化劑。"},
    {"term": "Rare earth", "zh": "稀土元素", "explain": "包含釔與 15 個鑭系元素。螢光粉常用釔（Y）、鈰（Ce）、銪（Eu）、鋱（Tb）、鎦（Lu）、釓（Gd）。中國掌握大部分的精煉產能。"},
    {"term": "QE / IQE / EQE", "zh": "量子效率", "explain": "放出光子數除以吸收（IQE）或入射（EQE）光子數。商用螢光粉 IQE 多在 90% 以上，論文中低於 70% 的材料通常離實用還遠。"},
    {"term": "FWHM", "zh": "半高寬", "explain": "發光譜帶在強度一半處的寬度。窄＝顏色純（顯示器要的），寬＝光譜平滑（照明顯色好）。"},
    {"term": "CRI / Ra", "zh": "顯色指數（演色性）", "explain": "光源讓物體顏色「看起來正常」的程度，0–100。Ra 是 8 個色樣的平均，一般 LED 80，高品質 90 以上。台灣 LED 業界也常稱「演色性」或「演色指數」。"},
    {"term": "R9", "zh": "飽和紅顯色指數", "explain": "CRI 延伸色樣中的飽和紅色。缺紅光的 LED 可以 Ra 80 但 R9 接近 0，肉類與膚色會顯得灰。"},
    {"term": "TM-30", "zh": "IES TM-30 顯色評估", "explain": "美國照明工程學會提出的新方法，用 99 個色樣算出保真度 Rf 與色域指數 Rg，比 CRI 更能反映真實感受。"},
    {"term": "CCT", "zh": "相關色溫", "explain": "白光偏黃或偏藍的指標（K）。2700 K 暖白、4000 K 中性白、6500 K 冷白。靠螢光粉配方調整。"},
    {"term": "Luminous efficacy", "zh": "發光效率", "explain": "每瓦電力產生多少流明（lm/W）。白熾燈約 15，螢光燈 60–100，商用白光 LED 已超過 200，實驗室更高。"},
    {"term": "Thermal quenching", "zh": "熱猝滅", "explain": "溫度升高時螢光粉發光變弱、甚至永久劣化的現象。常以「150 °C 保留室溫亮度的百分比」評估。"},
    {"term": "Color gamut", "zh": "色域", "explain": "顯示器能呈現的顏色範圍。常見標準：NTSC（1953）、DCI-P3（電影）、Rec.2020（超高畫質電視）。"},
    {"term": "Cyan gap", "zh": "青色缺口", "explain": "傳統白光 LED 光譜在 480–520 nm 之間的凹陷。近年出現專門補這段的青色螢光粉與青光 LED，讓光譜更接近日光。"},
    {"term": "Phosphor-in-glass (PiG)", "zh": "螢光玻璃", "explain": "把螢光粉燒進玻璃裡，取代會黃化的矽膠，耐熱耐光，用於高功率與雷射照明。"},
    {"term": "Phosphor ceramic", "zh": "螢光陶瓷", "explain": "把螢光粉燒結成緻密陶瓷片（如 Lumileds 的 Lumiramic、OSRAM 的 Ceramos），導熱好，可承受雷射等級的光功率，是車頭燈與投影機的關鍵元件。"},
    {"term": "Remote phosphor", "zh": "遠端螢光粉", "explain": "把螢光粉做成獨立的板或蓋，和晶片保持距離，可降低螢光粉溫度、讓光更均勻。"},
    {"term": "Laser lighting", "zh": "雷射照明", "explain": "用藍光雷射二極體取代 LED 激發螢光粉，亮度密度可高出一個數量級，用於車頭燈、投影機、探照燈。"},
    {"term": "Phosphor wheel", "zh": "螢光粉色輪", "explain": "雷射投影機裡高速旋轉的螢光粉圓盤，藍光雷射打在上面依序產生黃、綠、紅光；旋轉是為了散熱。"},
    {"term": "Quantum dot (QD)", "zh": "量子點", "explain": "奈米尺寸的半導體晶體（CdSe、InP、鈣鈦礦），發光顏色由粒徑決定，譜帶窄（20–40 nm）。是廣色域顯示中螢光粉的主要競爭者，但穩定性與含鎘問題仍待解決。"},
    {"term": "Perovskite", "zh": "鈣鈦礦", "explain": "CsPbX₃ 一類的鹵化物材料，發光極窄、成本低，但含鉛且怕水怕熱，目前多在研究與試量產階段。"},
    {"term": "Micro LED", "zh": "微發光二極體", "explain": "尺寸小於 50–100 µm 的 LED 直接做成畫素的顯示技術。全彩化的做法之一是用藍光 Micro LED 加量子點或奈米螢光粉做色轉換。"},
    {"term": "Color conversion", "zh": "色轉換", "explain": "用螢光粉或量子點把藍光轉成其他顏色，是 pc-LED、Mini／Micro LED 與 QD 顯示的共同原理。"},
    {"term": "Persistent luminescence", "zh": "長餘輝／夜光", "explain": "材料在光照停止後仍持續發光數分鐘到數小時的現象，靠晶體裡的「陷阱」慢慢釋放儲存的電子。代表材料 SrAl₂O₄:Eu²⁺,Dy³⁺。"},
    {"term": "Upconversion", "zh": "上轉換", "explain": "吸收兩個以上低能量的近紅外光子，放出一個可見光子。代表材料 NaYF₄:Yb³⁺,Er³⁺，用於防偽、生醫影像。"},
    {"term": "Scintillator", "zh": "閃爍體", "explain": "把 X 光、γ 射線等高能輻射轉成可見光的材料（CsI:Tl、LYSO:Ce、GAGG:Ce），本質上也是螢光材料，是醫療影像與安檢的核心。"},
    {"term": "Mechanoluminescence", "zh": "應力發光", "explain": "材料受到摩擦、擠壓或拉伸時發光，可用來「看見」結構的受力分布。"},
    {"term": "NIR", "zh": "近紅外光", "explain": "700–2500 nm 的不可見光。近紅外螢光粉 LED 可作為小型光譜儀光源，用於食品檢測、生醫監測。"},
    {"term": "Melanopic EDI", "zh": "黑視素等效日光照度", "explain": "CIE S 026 定義的指標，衡量光線對人體生理時鐘（透過視網膜的黑視素細胞）的刺激強度。以人為本照明會依時段調整。"},
    {"term": "Human-centric lighting", "zh": "以人為本照明", "explain": "依照人體生理節律調整光的色溫與強度的照明設計；全光譜螢光粉配方是實現手段之一。"},
    {"term": "Full-spectrum LED", "zh": "全光譜 LED", "explain": "光譜連續、接近日光的 LED，常用紫光晶片加多種螢光粉做成，減少 450 nm 附近的藍光尖峰。"},
    {"term": "Blue light hazard", "zh": "藍光危害", "explain": "IEC 62471 定義的光生物安全等級。一般照明用白光 LED 多屬無風險或低風險組（RG0／RG1），與螢光燈相當。"},
    {"term": "Halophosphate", "zh": "鹵磷酸鹽螢光粉", "explain": "Ca₅(PO₄)₃(F,Cl):Sb³⁺,Mn²⁺，1940 年代起用於螢光燈管的經典螢光粉，便宜但顯色差。"},
    {"term": "Tri-band phosphor", "zh": "三基色螢光粉", "explain": "1970 年代飛利浦推出的稀土螢光燈配方（BAM 藍、LAP／CAT 綠、YOX 紅），顯色與效率大幅提升，是稀土進入照明的起點。"},
    {"term": "DFT", "zh": "密度泛函理論", "explain": "用量子力學計算材料性質的方法，可預測螢光粉的能隙、結構穩定性，加速新材料篩選。"},
    {"term": "Materials Project", "zh": "材料計畫資料庫", "explain": "美國勞倫斯柏克萊實驗室主持的開放材料計算資料庫，是機器學習篩選螢光粉基質的常用資料來源。"},
    {"term": "GNoME", "zh": "Google DeepMind 材料探索模型", "explain": "2023 年發表的圖神經網路，預測出數十萬種新穩定晶體，被視為 AI 加速材料發現的里程碑，也影響螢光粉研究方法。"},
    {"term": "Single-particle diagnosis", "zh": "單顆粒診斷法", "explain": "NIMS 發展的方法：從混合粉體中挑出單顆發光晶粒直接做結構與光譜分析，大幅加快新螢光粉的發現。"},
    {"term": "Trap depth", "zh": "陷阱深度", "explain": "長餘輝材料中儲存電子的能量位置深淺。太淺幾分鐘就放完（亮但短），太深室溫放不出來（暗但久）；要在室溫亮好幾個小時，深度約 0.6–0.7 eV。"},
    {"term": "Thermoluminescence", "zh": "熱釋光", "explain": "把充過光的材料慢慢加熱、記錄各溫度下的發光量，就能反推陷阱的深度與數量，是研究夜光機制的主要工具。"},
    {"term": "mcd/m²", "zh": "毫燭光每平方公尺", "explain": "夜光亮度單位。廠商說「可亮 20 小時」通常指亮度降到 0.32 mcd/m²（DIN 67510 等安全標示規範的門檻，約為暗適應人眼極限的 100 倍）所需的時間。"},
    {"term": "Radiant intensity", "zh": "輻射強度（mW/sr）", "explain": "光源朝某方向每單位立體角送出的功率，近紅外 LED 常用此規格；數字越高感測器收到的訊號越強。"},
    {"term": "LM-80 / TM-21", "zh": "LED 光衰測試與壽命推估", "explain": "LM-80 是量測 LED 元件光通量隨時間衰減的標準方法，TM-21 用這些資料推估壽命（例如 L70：光衰到 70% 的時間）；螢光粉與封裝材料的劣化都會反映在這裡。"},
    {"term": "ITRI", "zh": "工業技術研究院", "explain": "台灣的工研院，長期投入 LED、Micro LED 與光電材料研發。"},
    {"term": "NIMS", "zh": "日本物質材料研究機構", "explain": "National Institute for Materials Science，SiAlON 與 CASN 等氮化物螢光粉的發源地。"},
]
