# -*- coding: utf-8 -*-
"""全球版圖：各地區的主要企業、研究團隊與角色；市場規模估計；專利地圖。
（第一版：以日本、美國、歐洲、中國、韓國、台灣六區整理，產業／台灣專題研究回來後再補。）"""

LANDSCAPE = {
    "lead": "螢光粉是一個「日本發明、德國與美國定義規格、中國量產、台灣與韓國封裝成產品」的產業。專利集中在少數幾家手上（日亞、三菱化學／NIMS、Denka、GE／Edison、Lumileds／LMU），生產與研究發表量則以中國為最大。點選地區查看。",
    "regions": [
        {"id": "jp", "name": "日本",
         "lead": "白光 LED 與幾乎所有主流螢光粉家族的發源地：日亞化學（YAG 白光 LED、KSF 供應）、三菱化學與 NIMS（CASN／SCASN）、Denka（SiAlON）、根本特殊化學（夜光粉）、日本電氣硝子（螢光玻璃）、東芝材料（TRI-R 全光譜）。專利與授權策略嚴密，是全球產業的規則制定者。",
         "stats": [{"n": "1996", "l": "日亞做出第一顆白光 LED"}, {"n": "2005–2006", "l": "NIMS 發表 β-SiAlON 與 CASN"}, {"n": "2020", "l": "日亞成為 GE TriGain 第一家授權商"}],
         "companies": [
             {"name": "日亞化學", "en": "Nichia", "note": "全球最大 LED 廠，1956 年創立時即為螢光粉製造商。YAG 專利已到期，但仍是 KSF（TriGain）主要供應商，並推出 Optisolis、Vitasolis、GigaWhite 白光雷射。", "products": ["YAG:Ce", "KSF", "Optisolis", "GigaWhite"], "src": "https://www.nichia.co.jp/en/about_nichia/history.html", "srcName": "Nichia 公司歷史"},
             {"name": "三菱化學", "en": "Mitsubishi Chemical", "note": "與 NIMS 共同開發並量產 CASN／SCASN 氮化物紅粉（BR-101/J 646 nm、BR-102/D 620 nm），在中、美、韓多次專利勝訴；2015 年與日亞交互授權。", "products": ["CASN／SCASN", "GYAG", "β-SiAlON"], "src": "https://www.nichia.co.jp/en/newsroom/2015/2015_010701.html", "srcName": "Nichia 2015（交互授權）"},
             {"name": "Denka（電氣化學）", "en": "Denka", "note": "NIMS 授權的 SiAlON 製造商，ALONBRIGHT 品牌涵蓋 β-SiAlON 綠粉（GR-MW540K 等）與 α-SiAlON 橙黃粉，也生產 CASN 系紅粉。", "products": ["β-SiAlON", "α-SiAlON", "CASN"], "src": "https://www.denka.co.jp/eng/product/detail_00031/", "srcName": "Denka 官網"},
             {"name": "物質・材料研究機構", "en": "NIMS", "note": "廣崎尚登、謝榮軍等人發明 β-SiAlON、CASN，發展單顆粒診斷法；持有的紅粉專利 2018 年起拆成製造與應用兩類授權，2026 年在中國專利訴訟中全勝。", "products": ["專利授權", "單顆粒診斷法"], "src": "https://www.nims.go.jp/eng/press/2026/05/202605130.html", "srcName": "NIMS 2026"},
             {"name": "根本特殊化學", "en": "Nemoto & Co.", "note": "1993 年發明鋁酸鍶夜光粉 LumiNova 取代含鐳塗料，1996 年 Matsuzawa 等人的論文開啟長餘輝研究熱潮。", "products": ["LumiNova"], "src": "https://iopscience.iop.org/article/10.1149/1.1837067", "srcName": "J. Electrochem. Soc. 1996"},
             {"name": "日本電氣硝子", "en": "NEG", "note": "螢光玻璃 Lumiphous 耐熱超過 500 °C，通過 85 °C／85% RH 5,000 小時測試，長期用於車用 LED 頭燈。", "products": ["Lumiphous 螢光玻璃"], "src": "https://www.neg.co.jp/product/ep/lumiphous", "srcName": "NEG 產品頁"},
             {"name": "東芝材料", "en": "Toshiba Materials", "note": "TRI-R 三色螢光粉是首爾半導體 SunLike 的核心；東芝 2022 年另發表可溶於樹脂的透明銪錯合物螢光材料。", "products": ["TRI-R"], "src": "https://www.ledinside.com/news/2017/6/seoul_semiconductor_and_toshiba_materials_co_develop_sunlike_solution_friendly_to_human_eyes", "srcName": "LEDinside 2017"},
             {"name": "昭榮化學", "en": "Shoei Chemical", "note": "2023 年 9 月收購 Nanosys 量子點事業（逾 800 件專利），把全球最重要的量子點智財之一納入日本材料廠。", "products": ["Nanosys 量子點"], "src": "https://www.businesswire.com/news/home/20230907824277/en/Shoei-Chemical-Acquires-Quantum-Dot-Business-from-Nanosys", "srcName": "Business Wire 2023"},
         ],
         "research": [
             {"name": "NIMS 廣崎尚登、武田隆史", "org": "物質・材料研究機構", "note": "氮化物／氮氧化物螢光粉與單顆粒診斷法的發源團隊，2026 年仍以此法發現 SrLi₃AlO₄:Eu²⁺。", "src": "https://doi.org/10.1080/14686996.2026.2650843", "srcName": "STAM 2026"},
         ],
         "notes": ["日本的優勢在「材料＋專利＋量產」三者合一；弱點是稀土原料幾乎全數仰賴進口。"]},
        {"id": "us", "name": "美國",
         "lead": "規格與專利的定義者：GE 發明並商品化 KSF（TriGain），2025 年專利組合轉到 Edison Innovations；Lumileds 與 LMU 合作推出 SLA 窄頻紅粉並有 Lumiramic 陶瓷；Intematix 的石榴石（GAL）與矽酸鹽；能源部 SSL 計畫長期設定光效目標並資助研究。",
         "stats": [{"n": "1938", "l": "GE 讓日光燈商業化"}, {"n": "2015", "l": "GE TriGain（KSF）上市"}, {"n": "255 lm/W", "l": "DOE 估計 pc-LED 封裝光效可達的近期目標"}],
         "companies": [
             {"name": "GE／Edison Innovations", "en": "GE Current, Edison Innovations", "note": "Setlur 等人 2008–2012 年解決 KSF 抗濕問題，2015 年以 TriGain 商品化；2025 年初約 2,500 件 GE 專利轉到 Edison Innovations，2026 年密集授權台、中、韓、美封裝廠。", "products": ["KSF／TriGain", "次微米 KSF 墨水"], "src": "https://www.ledinside.com/interview/2026/8/2026_08_31_01", "srcName": "LEDinside 2026"},
             {"name": "Lumileds", "en": "Lumileds", "note": "原飛利浦 LED 部門；2008 年 Lumiramic 陶瓷螢光板量產，2014 年與 LMU 發表 SLA，2016 年窄頻紅粉白皮書並導入 LUXEON 中功率產品，2018 年推出封裝內量子點 LED。", "products": ["Lumiramic", "SLA 窄頻紅粉", "LUXEON"], "src": "https://www.nature.com/articles/nmat4012", "srcName": "Nature Materials 2014"},
             {"name": "Intematix", "en": "Intematix", "note": "石榴石 GAL 系列（LuAG 基，516–560 nm）、矽酸鹽與紅粉；曾因氮化物紅粉專利與三菱化學涉訟。", "products": ["GAL 石榴石", "矽酸鹽"], "src": "https://image-ppubs.uspto.gov/dirsearch-public/print/downloadPdf/11901492", "srcName": "USPTO US11901492"},
             {"name": "Bridgelux", "en": "Bridgelux", "note": "Thrive 93／98 用寬頻藍光晶片加特殊螢光粉配方填補青色缺口；2026 年取得 Edison 的 KSF 授權。", "products": ["Thrive 全光譜"], "src": "https://www.bridgelux.com/blog/bridgelux-releases-thrive-93-delivering-lighting-s-closest-match-natural-light-while-saving", "srcName": "Bridgelux 2021"},
             {"name": "Kyocera SLD Laser", "en": "Kyocera SLD Laser", "note": "前身 SoraaLaser，LaserLight SMD 白光雷射封裝亮度 1,000–1,300 cd/mm²、450–1,000 lm。", "products": ["LaserLight SMD"], "src": "https://www.allaboutcircuits.com/new-industry-products/kyocera-sld-laser-laserlight-smds-new-product-brief/", "srcName": "All About Circuits"},
             {"name": "美國能源部 SSL 計畫", "en": "DOE SSL", "note": "定期發布固態照明研發機會與節能預測：2035 年可年省 4.8 quads、LED 占裝置 84%；點名窄頻紅粉為光效槓桿。", "products": ["研發路線圖", "節能預測"], "src": "https://www.energy.gov/cmei/ssl/ssl-forecast-report", "srcName": "DOE SSL Forecast"},
         ],
         "research": [
             {"name": "Jakoah Brgoch", "org": "休士頓大學", "note": "2018 年起以機器學習篩選高熱穩定性螢光粉基質，是資料驅動螢光粉發現的代表。", "src": "https://www.sciencedirect.com/science/article/abs/pii/S138589472506557X", "srcName": "（相關：CEJ 2025 機器學習綠粉）"},
             {"name": "Anant Setlur 團隊", "org": "GE Research", "note": "KSF 抗濕與色穩定專利（US 8,057,706、US 8,252,613）的發明團隊。", "src": "https://sid.onlinelibrary.wiley.com/doi/10.1002/sdtp.10406", "srcName": "SID 2015"},
         ],
         "notes": ["美國的螢光粉「製造」規模不大，但握有 KSF 專利、DOE 路線圖與 Materials Project 等關鍵資源。"]},
        {"id": "eu", "name": "歐洲",
         "lead": "基礎科學與高階轉換器的重鎮：慕尼黑大學 Schnick 團隊開創氮化物螢光粉並發表 SLA、SALON；ams OSRAM（德國／奧地利）在雷射照明（LARP）、近紅外 LED 與封裝內量子點上領先；SCHOTT 供應陶瓷雷射轉換器；飛利浦（荷蘭）是三基色與 YAG:Ce 的歷史起點。",
         "stats": [{"n": "1967", "l": "飛利浦 Blasse 與 Bril 發現 YAG:Ce 發光"}, {"n": "2014", "l": "SLA 發表；BMW i8 雷射頭燈量產"}, {"n": "2025-11", "l": "歐盟含鎘量子點顯示用豁免到期"}],
         "companies": [
             {"name": "ams OSRAM", "en": "ams OSRAM", "note": "雷射激發遠端螢光體（LARP）陶瓷轉換器與 BMW i8 雷射頭燈模組；2016 年提出近紅外 pc-LED（OSLON P1616 SFH 4737）；2021 年首款 2835 封裝量子點 LED 超過 200 lm/W；SALON 的產業端開發者。", "products": ["LARP", "近紅外 LED", "Osconiq QD", "258 氮化物"], "src": "https://www.led-professional.com/products-services/osram-presents-the-worlds-smallest-broadband-ir-led-for-spectroscopy-applications", "srcName": "LED professional"},
             {"name": "SCHOTT", "en": "SCHOTT", "note": "純無機陶瓷雷射螢光轉換器，分靜態與動態（螢光粉輪環）兩類，用於商用與影院雷射投影機。", "products": ["陶瓷雷射轉換器"], "src": "https://www.schott.com/en-us/products/ceramic-laser-phosphor-converter", "srcName": "SCHOTT 產品頁"},
             {"name": "Signify（原飛利浦照明）", "en": "Signify", "note": "全球最大照明廠，三基色螢光燈與 YAG:Ce 的歷史源頭；今日主要是螢光粉的使用者而非製造者。", "products": ["照明系統"], "src": "https://www.sciencedirect.com/science/article/abs/pii/0254058487901039", "srcName": "Phosphors based on rare-earths（1987）"},
             {"name": "Barco", "en": "Barco", "note": "2015 年推出首台 18,000 流明雷射螢光影院投影機；Regal 2030 年前換裝 4,000 廳。", "products": ["雷射螢光投影機"], "src": "https://www.barco.com/it/News/Press-releases/Barco-first-to-launch-18000-lumen-laser-phosphor-projector-for-cinema.aspx", "srcName": "Barco 新聞稿"},
             {"name": "Fraunhofer AWZ／IKTS", "en": "Fraunhofer", "note": "Soest 的無機螢光體應用中心開發硼酸鹽螢光玻璃與玻璃陶瓷轉換器並曾與 HELLA 合作雷射車燈；IKTS 開發氧化物、氟化物與氮化物螢光陶瓷。", "products": ["螢光玻璃陶瓷", "螢光陶瓷"], "src": "https://www.imws.fraunhofer.de/en/kompetenzfelder/leuchtstoffe.html", "srcName": "Fraunhofer IMWS"},
         ],
         "research": [
             {"name": "Wolfgang Schnick", "org": "慕尼黑大學（LMU）", "note": "氮化物螢光粉的開創者：258 型氮化物（2000）、SLA（2014）、SALON（2019）、UCr₄C₄ 型結構家族。", "src": "https://www.nature.com/articles/nmat4012", "srcName": "Nature Materials 2014"},
             {"name": "Philippe Smet、Dirk Poelman", "org": "根特大學", "note": "長餘輝與應力發光機制的代表性團隊，發表多篇長餘輝綜述。", "src": "https://pmc.ncbi.nlm.nih.gov/articles/PMC5445854/", "srcName": "Materials 2010 綜述"},
         ],
         "notes": ["歐盟法規（RoHS 淘汰含汞燈管、限制含鎘量子點）直接塑造全球色轉換材料的技術路線。"]},
        {"id": "cn", "name": "中國",
         "lead": "最大的生產基地與論文產出國：有研稀土、煙台希爾德、江蘇博睿、北京宇極等螢光粉廠，木林森、瑞豐、聚飛等封裝廠透過授權使用 KSF；華南理工夏志國、廈門大學謝榮軍、浙江大學邱建榮等團隊在窄頻材料、近紅外與雷射陶瓷上發表量居全球之冠。同時掌握絕大多數稀土精煉能力，2023 年起的出口管制影響全球供應鏈。",
         "stats": [{"n": "70.3%", "l": "Hisense 2025 年雷射電視全球市占"}, {"n": "70–80%", "l": "Appotronics 在中國電影雷射放映機的市占"}, {"n": "2016", "l": "瑞豐成為中國首家 GE KSF 授權封裝廠"}],
         "companies": [
             {"name": "有研稀土", "en": "Grirem Advanced Materials", "note": "國家級稀土材料公司，供應 YAG、氮化物與氟化物紅粉，宣稱是唯一能批量供應鍺基氟化物（KGF）紅粉的廠商。", "products": ["YAG", "氮化物", "KGF"], "src": "https://lighting.ofweek.com/2018-09/ART-34002-8420-30268628.html", "srcName": "OFweek 2018"},
             {"name": "煙台希爾德", "en": "Yantai Shield", "note": "中國主要 LED 螢光粉廠之一，曾因氮化物紅粉專利遭三菱化學提告敗訴。", "products": ["YAG", "氮化物"], "src": "https://www.nims.go.jp/eng/press/2026/05/202605130.html", "srcName": "NIMS 2026（提及訴訟）"},
             {"name": "江蘇博睿光電", "en": "Jiangsu Bree Optronics", "note": "2019 年起多次對 NIMS 的 CASN 中國專利提出無效請求，2025 年底最高人民法院判決後撤回。", "products": ["氮化物紅粉"], "src": "https://www.nims.go.jp/eng/press/2026/05/202605130.html", "srcName": "NIMS 2026"},
             {"name": "光峰科技", "en": "Appotronics", "note": "2007 年創立，ALPD 雷射螢光顯示技術掌握螢光粉輪與熱管理智財，2024 年影院營收人民幣 24.19 億元，車用光學 6.38 億元。", "products": ["ALPD 螢光粉輪"], "src": "https://www.appotronics.com/uploads/soft/20251103/Appotronics%20Corporation%20Limited%20Annual%20Report%202024-1762158157.pdf", "srcName": "Appotronics 2024 年報"},
             {"name": "瑞豐光電、聚飛光電、穗晶光電、木林森", "en": "封裝廠", "note": "自 2016 年起陸續取得 GE 的 KSF 應用授權（瑞豐 2024 年續簽全球背光授權；木林森 2026 年取得 Edison 授權）。", "products": ["KSF 背光 LED"], "src": "https://lights.ofweek.com/2024-06/ART-8100-2200-30637247.html", "srcName": "OFweek 2024-06"},
             {"name": "致晶科技", "en": "Zhijing Nanotech", "note": "與 TCL 合作以綠色鈣鈦礦量子點膜試產 500 台 75 吋電視，是鈣鈦礦量子點膜首次商用。", "products": ["鈣鈦礦量子點膜"], "src": "https://www.oled-info.com/tcl-brings-perovskite-qds-enhanced-lcds-market-pilot-project", "srcName": "OLED-Info"},
         ],
         "research": [
             {"name": "夏志國", "org": "華南理工大學", "note": "UCr₄C₄ 型窄頻螢光粉、礦物啟發的材料設計、機器學習發現與雷射顯示用窄帶螢光玻璃膜。", "src": "https://www2.scut.edu.cn/skllmd/2025/0617/c24800a594377/page.htm", "srcName": "華南理工 2025 工作簡報"},
             {"name": "謝榮軍", "org": "廈門大學（前 NIMS）", "note": "β-SiAlON 共同發明人；2016 年提出 Al₂O₃–YAG:Ce 複合陶瓷奠定雷射照明高導熱路線；2024 年與 NIMS 合成新型 α-SiAlON。", "src": "https://pubs.rsc.org/en/content/articlelanding/2016/tc/c6tc03215j", "srcName": "J. Mater. Chem. C 2016"},
             {"name": "邱建榮", "org": "浙江大學", "note": "螢光玻璃薄膜、透明螢光粉—石英玻璃轉換器；2026 年 Nature Communications 秒級快速燒結螢光陶瓷。", "src": "https://www.nature.com/articles/s41467-026-74741-2", "srcName": "Nature Communications 2026"},
         ],
         "notes": ["中國在「量」上領先，但主流材料的核心專利多在日、美手上；2025 年 4 月起釔、鋱、鎦、釓等稀土納入出口管制，反過來成為它的槓桿。"]},
        {"id": "kr", "name": "韓國",
         "lead": "以應用端見長：首爾半導體的 SunLike 全光譜 LED、Samsung Display 的 QD-OLED 與電致發光量子點、首爾大學的鈣鈦礦奈米晶；LG Innotek 已淡出 LED，螢光粉本身多向日、中採購。",
         "stats": [{"n": "2017", "l": "首爾半導體 SunLike 上市"}, {"n": "500 萬片", "l": "Samsung Display QD-OLED 螢幕面板累計出貨（2026-04）"}],
         "companies": [
             {"name": "首爾半導體", "en": "Seoul Semiconductor", "note": "SunLike 以紫光晶片激發東芝材料 TRI-R 三色螢光粉，去除藍光尖峰，用於美術館與時裝週照明。", "products": ["SunLike"], "src": "https://www.ledinside.com/news/2017/6/seoul_semiconductor_and_toshiba_materials_co_develop_sunlike_solution_friendly_to_human_eyes", "srcName": "LEDinside 2017"},
             {"name": "Samsung Display", "en": "Samsung Display", "note": "QD-OLED 以噴墨列印 InP 量子點做色轉換層，2025 年出貨 250 萬片螢幕面板；2026 年展出無鎘電致發光量子點原型。", "products": ["QD-OLED", "EL-QD"], "src": "https://global.samsungdisplay.com/31450", "srcName": "Samsung Display 2026"},
             {"name": "Samsung Electronics", "en": "Samsung", "note": "Micro RGB 電視以三色 LED 當背光，不需螢光粉或量子點；QLED 電視則用量子點膜（部分機種搭配 KSF）。", "products": ["Micro RGB", "QLED"], "src": "https://news.samsung.com/us/samsung-expands-premium-micro-rgb-tv-lineup-2026-new-sizes-advanced-features", "srcName": "Samsung Newsroom 2026"},
             {"name": "Lumens", "en": "Lumens", "note": "2026 年取得 Edison Innovations 的 KSF 授權，用於車用顯示背光。", "products": ["KSF 背光"], "src": "https://www.ledinside.com/interview/2026/8/2026_08_31_01", "srcName": "LEDinside 2026"},
         ],
         "research": [
             {"name": "李泰雨（Tae-Woo Lee）", "org": "首爾大學", "note": "2026 年《Nature》發表可量產、100% 量子產率的鈣鈦礦奈米晶冷注入合成法，衍生新創 SN Display。", "src": "https://www.nature.com/articles/s41586-026-10117-2", "srcName": "Nature 2026"},
         ],
         "notes": ["韓國的重心在顯示面板與量子點；螢光粉是被使用的材料，而非本土優勢產業。"]},
        {"id": "tw", "name": "台灣",
         "lead": "台灣的強項是 LED 晶片、封裝與 Micro LED 產業鏈（富采／晶電、隆達、億光、光寶、群創、友達、錼創），螢光粉本身多向日本、中國、美國採購，但學術上有全球級的研究團隊：臺大化學系劉如熹團隊長期在氮化物、氟化物、近紅外與窄頻螢光粉發表大量成果，報導稱其掌握全台近半的螢光粉專利並授權國內公司。",
         "stats": [{"n": "2015", "l": "億光在美國讓日亞 YAG 專利被判無效"}, {"n": "2026", "l": "億光、富采取得 Edison 的 KSF 授權"}, {"n": "2022", "l": "劉如熹團隊綜述登上 Chemical Reviews"}],
         "companies": [
             {"name": "億光電子", "en": "Everlight", "note": "台灣最大 LED 封裝廠，2012 年在美國對日亞 YAG 專利提起確認無效訴訟並於 2015 年勝訴；2026 年取得 Edison 的 KSF 授權。", "products": ["LED 封裝", "KSF 背光"], "src": "https://en.everlight.com/pr_20221125/", "srcName": "Everlight 新聞稿"},
             {"name": "富采投控（晶電、隆達）", "en": "Ennostar", "note": "LED 晶片與封裝集團；官網虛擬專利標示載明產品使用授權自 Edison Innovations 的 K₂SiF₆:Mn⁴⁺ 技術。", "products": ["LED 晶片", "Mini LED 背光"], "src": "https://www.ledinside.com/interview/2026/8/2026_08_31_01", "srcName": "LEDinside 2026"},
             {"name": "群創、友達", "en": "Innolux, AUO", "note": "面板廠的 Micro LED 全以藍光晶片搭配量子點色轉換；友達 2025 年底供應 Garmin Micro LED 手錶模組。", "products": ["Micro LED"], "src": "https://www.trendforce.com/news/2025/04/25/insight-touch-taiwan-2025-promising-potential-for-micro-led-displays-and-optical-communication/", "srcName": "TrendForce 2025"},
             {"name": "錼創科技", "en": "PlayNitride", "note": "Micro LED 先驅，2025 年與 Lumus 展示量子點轉色的單晶片全彩微投影機，用於 AR 眼鏡。", "products": ["Micro LED", "AR 微投影"], "src": "https://www.trendforce.com/news/2025/04/25/insight-touch-taiwan-2025-promising-potential-for-micro-led-displays-and-optical-communication/", "srcName": "TrendForce 2025"},
             {"name": "工業技術研究院", "en": "ITRI", "note": "投入 Micro LED 全彩微顯示模組（結合量子點）與光電材料研發。", "products": ["Micro LED 模組"], "src": "https://www.trendforce.com/news/2025/04/25/insight-touch-taiwan-2025-promising-potential-for-micro-led-displays-and-optical-communication/", "srcName": "TrendForce 2025"},
         ],
         "research": [
             {"name": "劉如熹", "org": "國立臺灣大學化學系", "note": "LED 光轉換材料的國際級研究者：氮化物、Mn⁴⁺ 氟化物、近紅外 Cr³⁺、窄頻與雙發光螢光粉、玻璃包覆鈣鈦礦量子點；2022 年綜述登上 Chemical Reviews、2024 年於 Progress in Materials Science 發表回顧。", "src": "https://www.ntu.edu.tw/spotlight/2022/2074_20220622.html", "srcName": "臺大焦點新聞 2022"},
         ],
         "notes": ["台灣沒有大型螢光粉製造商，但在「怎麼用螢光粉」（封裝、Micro LED 色轉換）與「發明新螢光粉」（臺大）兩端都有位置。"]},
    ],
    "market": {
        "lead": "「LED 螢光粉市場有多大」沒有標準答案：各研究機構的口徑（是否含量子點、是否含 LED 內含螢光粉的價值、是否含閃爍體與夜光）差異極大，2025 年的估計從 5 億到近 80 億美元都有。下圖把公開摘要並列，只能當量級參考。",
        "estimates": [
            {"source": "Research and Markets／Mordor", "label": "2025 年", "value": 0.52, "display": "US$ 0.52 B", "scope": "LED 螢光粉；2031 年 10.2 億，CAGR 10.8%；氮化物占 40%", "forecast": "US$ 1.02 B（2031）", "cagr": "10.8%"},
            {"source": "Verified Market Research", "label": "2023 年", "value": 0.63, "display": "US$ 0.63 B", "scope": "LED 螢光粉；2030 年 12.9 億", "forecast": "US$ 1.29 B（2030）", "cagr": "約 11%"},
            {"source": "Mordor Intelligence（另一版本）", "label": "2025 年", "value": 0.67, "display": "US$ 0.67 B", "scope": "LED 螢光粉；2030 年 16.7 億，CAGR 20%", "forecast": "US$ 1.67 B（2030）", "cagr": "20%"},
            {"source": "Straits Research", "label": "2025 年", "value": 1.79, "display": "US$ 1.79 B", "scope": "LED 螢光粉（較寬口徑）", "forecast": "—", "cagr": "—"},
            {"source": "Reanin", "label": "2025 年", "value": 1.94, "display": "US$ 1.94 B", "scope": "LED 螢光粉（較寬口徑）", "forecast": "—", "cagr": "—"},
            {"source": "另一份市場報告", "label": "2026 年", "value": 2.03, "display": "US$ 2.03 B", "scope": "含更廣的螢光材料；2035 年 61.6 億，亞太占 51%", "forecast": "US$ 6.16 B（2035）", "cagr": "13.1%"},
            {"source": "Market Research Future", "label": "2025 年", "value": 7.96, "display": "US$ 7.96 B", "scope": "極寬口徑（疑含所有發光材料），視為離群值", "forecast": "—", "cagr": "—"},
        ],
        "note": "數字皆為付費市場報告的公開摘要，方法與範圍未揭露；TrendForce 與 Yole 的螢光粉專門數據未在公開檢索中出現。可以確定的量級是：LED 螢光粉本身是「十億美元級」的材料市場，但它撐起的是數百億美元的 LED 與顯示產業。",
        "srcs": [{"url": "https://www.researchandmarkets.com/reports/4897091/led-phosphors-market-share-analysis-industry", "name": "Research and Markets"}, {"url": "https://www.mordorintelligence.com/industry-reports/led-phosphors-market", "name": "Mordor Intelligence"}],
    },
    "patents": [
        {"title": "日亞 YAG 白光 LED 專利：2015 年被判無效、2017 年到期", "detail": "US 5,998,925 等專利曾是全球 LED 訴訟焦點；億光 2012 年提起確認無效訴訟，2015 年 4 月美國陪審團判定無效；歐洲專利 EP936682 於 2017 年 7 月 29 日到期。YAG:Ce 從此成為公共技術。", "src": "https://en.everlight.com/pr_20221125/", "srcName": "Everlight 新聞稿"},
        {"title": "NIMS／三菱化學的 CASN 與 SCASN：仍然有效且持續執法", "detail": "日、美、韓、台、中多國專利；2015 年與日亞、Citizen 交互授權；2018 年授權拆成製造與應用兩類；三菱化學對 Intematix、煙台希爾德勝訴；2026 年中國專利在博睿六年無效訴訟後全數維持。", "src": "https://www.nims.go.jp/eng/press/2026/05/202605130.html", "srcName": "NIMS 2026"},
        {"title": "GE → Edison Innovations 的 KSF 專利組合：2026 年密集授權", "detail": "抗濕與色穩定專利（US 8,057,706、US 8,252,613）是 KSF 商用的基礎；授權對象從 2016 年的瑞豐、穗晶、聚飛，到 2020 年日亞、2022 年 Savant 交互授權，再到 2026 年億光、富采、木林森、Bridgelux、Lumens 等。", "src": "https://www.ledinside.com/interview/2026/8/2026_08_31_01", "srcName": "LEDinside 2026"},
        {"title": "Lumileds／LMU 的 SLA 與 ams OSRAM／LMU 的 SALON", "detail": "窄頻紅粉的核心專利分別在 Lumileds 與 OSRAM 陣營；UCr₄C₄ 型結構的後續變體則由中國與德國大學大量申請。", "src": "https://www.nature.com/articles/s41467-019-09632-w", "srcName": "Nature Communications 2019"},
        {"title": "NIMS／Denka 的 SiAlON", "detail": "β-SiAlON 與 α-SiAlON 由 NIMS 發明、Denka 授權量產（ALONBRIGHT）；是廣色域背光綠粉的專利基礎。", "src": "https://www.denka.co.jp/eng/product/detail_00031/", "srcName": "Denka 官網"},
        {"title": "量子點智財：Nanosys（昭榮）800+ 件、Nanoco 與 Samsung 和解", "detail": "2023 年昭榮化學收購 Nanosys 逾 800 件專利；Nanoco 的無鎘 InP 專利在 2023 年與 Samsung 和解授權，顯示色轉換材料的智財戰場已從螢光粉延伸到量子點。", "src": "https://www.businesswire.com/news/home/20230907824277/en/Shoei-Chemical-Acquires-Quantum-Dot-Business-from-Nanosys", "srcName": "Business Wire 2023"},
    ],
}
