# -*- coding: utf-8 -*-
"""材料家族：每種螢光粉一張卡片，加一張比較表。
peak/fwhm 為文獻與廠商規格的典型值；同一家族會隨組成微調而變動。"""

MATERIALS = {
    "lead": "螢光粉的「姓氏」由基質決定（石榴石、氮化物、氟化物…），「名字」由活化劑決定（Ce³⁺、Eu²⁺、Mn⁴⁺…）。下面依發光顏色與商業化狀態整理主要家族：每張卡片說明它是什麼、好在哪、卡在哪、誰在做、專利在誰手上。可用上方篩選。",
    "families": [
        {"id": "yag", "name": "YAG:Ce 黃色石榴石", "formula": "Y3Al5O12:Ce3+（可用 Gd、Ga、Lu 取代調色）", "activator": "Ce3+",
         "color": "黃", "colorGroup": "黃／綠", "peak": 555, "peakText": "530–560 nm", "fwhm": 115, "fwhmText": "約 110–120 nm",
         "status": "商用主流",
         "plain": "白光 LED 的元老。450 nm 藍光激發效率極高、量子效率超過 90%、耐熱、便宜，藍光加它就能成白光。缺點是光譜幾乎沒有紅色成分，單獨使用顯色指數只有 70–80，也做不出 3000 K 以下的暖白。",
         "pros": ["效率與穩定性經過近 30 年驗證", "專利已到期，任何廠商都能做", "石榴石結構可換元素微調顏色"],
         "cons": ["缺紅光，Ra 約 70–80、R9 很低", "單獨使用只能做冷白／中性白", "高溫下仍有一定熱猝滅"],
         "makers": ["Nichia", "三菱化學", "Intematix", "有研稀土", "煙台希爾德", "多數中國廠"],
         "history": "1967 年飛利浦的 Blasse 與 Bril 為彩色電視映像管開發，1996 年日亞化學把它塗在藍光晶片上做出白光 LED。日亞的核心專利（US 5,998,925 等）在 2015 年被美國陪審團判定無效，歐洲對應專利 2017 年 7 月到期，YAG:Ce 從此成為公共技術。",
         "apps": "一般照明、手電筒、車內燈、低成本背光。",
         "src": "https://www.nichia.co.jp/en/about_nichia/history.html", "srcName": "Nichia 公司歷史；Everlight 新聞稿（專利判決）"},
        {"id": "luag", "name": "LuAG:Ce 綠色石榴石", "formula": "Lu3Al5O12:Ce3+", "activator": "Ce3+",
         "color": "綠", "colorGroup": "黃／綠", "peak": 520, "peakText": "510–535 nm", "fwhm": 110, "fwhmText": "約 100–120 nm",
         "status": "商用",
         "plain": "把 YAG 的釔換成鎦，發光藍移成綠色，而且熱穩定性更好（陶瓷在 200 °C 亮度只降不到 5%）。常和氮化物紅粉搭配做高顯色暖白，也是雷射照明陶瓷與閃爍體的基質。",
         "pros": ["熱穩定性極佳，適合高功率與雷射", "與紅粉搭配可達 Ra 90+", "可燒成透明陶瓷"],
         "cons": ["鎦是最貴的稀土之一，成本高", "譜帶仍寬，不適合廣色域顯示"],
         "makers": ["Intematix（GAL 系列）", "Nichia", "三菱化學", "Baikowski"],
         "history": "石榴石家族的延伸。Intematix 以 GAL 系列商品化（GAL520 表示峰值 520 nm），並持有多項專利；LuAG:Ce 陶瓷也是 Lumileds、OSRAM 雷射照明轉換片的材料之一。",
         "apps": "高顯色照明、雷射車燈與投影、閃爍體。",
         "src": "https://image-ppubs.uspto.gov/dirsearch-public/print/downloadPdf/11901492", "srcName": "USPTO US11901492（Intematix）"},
        {"id": "casn", "name": "CASN:Eu 深紅氮化物", "formula": "CaAlSiN3:Eu2+（業界俗稱 1113）", "activator": "Eu2+",
         "color": "紅", "colorGroup": "橙／紅", "peak": 650, "peakText": "約 650 nm", "fwhm": 90, "fwhmText": "約 80–120 nm",
         "status": "商用主流",
         "plain": "讓 LED 做出暖白光與高顯色的關鍵紅粉。吸收從紫外到 590 nm 的光，放出寬帶紅光，化學鍵強、耐熱耐濕。缺點是譜帶太寬，一部分能量落在 650 nm 以後人眼不敏感的深紅區，會拖累效率。",
         "pros": ["R9 高，紅色物體顯得真實", "耐熱耐濕、可靠度高", "可被藍光高效激發"],
         "cons": ["譜帶寬，深紅區能量浪費", "高光通量下有光猝滅，是暖白 LED 效率下降的原因之一", "需高溫高壓氮氣合成，且受專利保護"],
         "makers": ["三菱化學", "Denka", "Nichia（交互授權）", "有研稀土", "江蘇博睿"],
         "history": "2006 年日本 NIMS 的 Uheda 等人與三菱化學共同發表；NIMS 與三菱化學持有多國專利。2015 年 Nichia、三菱化學、NIMS、Citizen 交互授權；三菱化學曾對 Intematix、煙台希爾德等提告勝訴。2026 年 5 月 NIMS 宣布中國專利在博睿六年無效訴訟後全數維持有效。",
         "apps": "暖白照明、高顯色燈具、車內照明。",
         "src": "https://www.nims.go.jp/eng/press/2026/05/202605130.html", "srcName": "NIMS 新聞稿 2026-05；ECS Solid-State Letters 2006"},
        {"id": "scasn", "name": "SCASN:Eu 橙紅氮化物", "formula": "(Sr,Ca)AlSiN3:Eu2+", "activator": "Eu2+",
         "color": "橙紅", "colorGroup": "橙／紅", "peak": 625, "peakText": "610–630 nm", "fwhm": 85, "fwhmText": "約 80–90 nm",
         "status": "商用主流",
         "plain": "在 CASN 裡用鍶取代部分鈣，峰值往短波移到 610–630 nm，光效更高又不至於太深紅，是目前用量最大的紅粉之一。三菱化學的 BR-102/D 峰值 620 nm、BR-101/J（CASN 型）646 nm 是典型商品。",
         "pros": ["效率比 CASN 高", "紅色成分足夠做 Ra 80–90", "耐熱耐濕"],
         "cons": ["譜帶仍寬，效率上限受限", "同樣受 NIMS／三菱專利約束"],
         "makers": ["三菱化學", "Denka", "Nichia", "有研稀土", "煙台希爾德（曾涉訟）"],
         "history": "CASN 的固溶體版本，與 CASN 一起由 NIMS 與三菱化學開發並專利化；2018 年 NIMS 把授權拆成「製造」與「應用」兩類，降低下游門檻。",
         "apps": "暖白與高顯色 LED、Mini LED 背光的紅色成分（與 β-SiAlON 搭配約 85% NTSC）。",
         "src": "https://www.ledinside.com/press/2018/10/nims_separates_its_red_phosphor_patent_usages_into_manufacturing_and_application", "srcName": "LEDinside 2018（NIMS 授權）；NIMS 2026"},
        {"id": "sr258", "name": "Sr₂Si₅N₈:Eu「258」氮化物", "formula": "M2Si5N8:Eu2+（M = Ca, Sr, Ba）", "activator": "Eu2+",
         "color": "橙紅", "colorGroup": "橙／紅", "peak": 610, "peakText": "590–625 nm", "fwhm": 90, "fwhmText": "約 80–100 nm",
         "status": "商用",
         "plain": "最早商品化的氮化物紅粉之一，由 Schnick 團隊在 2000 年前後報導、OSRAM 等公司採用。可被藍光直接激發，也能吸收綠粉的光再轉紅。化學與熱穩定性不如 CASN，市占逐漸被 CASN／SCASN 取代。",
         "pros": ["歷史悠久、製程成熟", "顏色可由 Ca/Sr/Ba 比例調整"],
         "cons": ["熱穩定性與抗濕性不如 CASN", "市占持續下滑"],
         "makers": ["ams OSRAM（早期）", "部分中國廠"],
         "history": "2000 年 Höppe 與 Schnick 報導 Ba2Si5N8:Eu 等 258 型氮化物的發光，OSRAM 在 2000 年代將其用於暖白 LED；之後 NIMS／三菱的 CASN 因穩定性更好而勝出。",
         "apps": "早期暖白 LED、部分中低階產品。",
         "src": "https://pmc.ncbi.nlm.nih.gov/articles/PMC10142842/", "srcName": "PMC 綜述（氮化物紅粉沿革）"},
        {"id": "bsialon", "name": "β-SiAlON:Eu 窄頻綠粉", "formula": "Si6-zAlzOzN8-z:Eu2+", "activator": "Eu2+",
         "color": "綠", "colorGroup": "黃／綠", "peak": 538, "peakText": "535–540 nm", "fwhm": 55, "fwhmText": "約 55 nm",
         "status": "商用主流",
         "plain": "廣色域背光的標準綠粉。半高寬只有 55 nm、色度 (0.32, 0.64) 綠得很純，又耐熱（150 °C 亮度只掉約 10%）耐濕。藍光晶片＋β-SiAlON＋KSF 就是 2015 年以來廣色域 LCD 背光最普及的配方。",
         "pros": ["窄頻、色純度高", "熱與化學穩定性極佳", "雷射激發的飽和閾值比 YAG 高"],
         "cons": ["量子效率低於 YAG（早期 IQE 約 70%）", "合成需高溫高壓氮氣", "受 NIMS／Denka 專利約束"],
         "makers": ["Denka（GR-MW540K 等）", "三菱化學", "Nichia", "有研稀土"],
         "history": "2005 年 NIMS 廣崎尚登、謝榮軍等人在 Applied Physics Letters 發表，由 Denka 取得授權量產。與 KSF 一起把 LCD 背光色域從 72% NTSC 拉到 DCI-P3 九成以上。",
         "apps": "電視、筆電、手機背光；高顯色照明的綠色成分。",
         "src": "https://pubs.aip.org/aip/apl/article/86/21/211905/931445/Characterization-and-properties-of-green-emitting", "srcName": "Applied Physics Letters 2005（NIMS）"},
        {"id": "asialon", "name": "α-SiAlON:Eu 橙黃粉", "formula": "Ca-α-SiAlON:Eu2+（近年也有 Sr 型）", "activator": "Eu2+",
         "color": "橙黃", "colorGroup": "黃／綠", "peak": 585, "peakText": "580–600 nm", "fwhm": 90, "fwhmText": "約 90 nm",
         "status": "商用",
         "plain": "SiAlON 家族的橙黃色成員，可取代或補充 YAG 做偏暖的白光，耐熱性好。2024 年 NIMS 與廈門大學做出富鍶的新型 α-SiAlON（590 nm，150 °C 仍保有 93% 亮度）。",
         "pros": ["耐熱、抗濕", "一種粉就能做出較暖的白光"],
         "cons": ["量子效率不如 YAG", "顯色仍受限"],
         "makers": ["Denka", "三菱化學"],
         "history": "NIMS 開發、Denka 量產，是 2000 年代與 YAG 競爭的黃粉之一；2024 年新型 Sr3Si24Al6N40:Eu2+ 發表於 STAM。",
         "apps": "暖白照明。",
         "src": "https://www.tandfonline.com/doi/full/10.1080/14686996.2024.2396276", "srcName": "Science and Technology of Advanced Materials 2024"},
        {"id": "srsi2o2n2", "name": "SrSi₂O₂N₂:Eu「122」氮氧化物", "formula": "SrSi2O2N2:Eu2+", "activator": "Eu2+",
         "color": "綠", "colorGroup": "黃／綠", "peak": 540, "peakText": "約 540 nm", "fwhm": 80, "fwhmText": "約 70–80 nm",
         "status": "商用",
         "plain": "介於矽酸鹽與純氮化物之間的層狀材料，綠色發光、熱猝滅溫度高於 200 °C，是 OSRAM 早期綠色／黃綠螢光粉的代表之一。",
         "pros": ["熱與色穩定性好", "合成條件比純氮化物溫和"],
         "cons": ["譜帶比 β-SiAlON 寬", "市占不大"],
         "makers": ["ams OSRAM", "部分中國廠"],
         "history": "2000 年代由 Schnick 團隊與 OSRAM 發展的氮氧矽酸鹽家族成員。",
         "apps": "白光 LED 綠色成分。",
         "src": "https://www.researchgate.net/publication/271286639_Two-Step_Synthesis_of_SrSi2O2N2_Eu2_Green_Oxynitride_Phosphor_Electron-Phonon_Coupling_and_Thermal_Quenching_Behavior", "srcName": "ResearchGate（SrSi2O2N2:Eu 熱猝滅研究）"},
        {"id": "silicate", "name": "矽酸鹽 BOSE", "formula": "(Ba,Sr)2SiO4:Eu2+", "activator": "Eu2+",
         "color": "綠～橙黃", "colorGroup": "黃／綠", "peak": 555, "peakText": "505–580 nm（可調）", "fwhm": 70, "fwhmText": "約 65–80 nm",
         "status": "商用",
         "plain": "便宜、顏色從綠到橙黃都能調，2000 年代中低功率 LED 常用。但怕熱也怕水：高溫下亮度掉得比 YAG 快，鹼性強、遇水會水解並把 Eu²⁺ 氧化，85 °C／85% RH 老化測試明顯劣於 YAG，所以已退居次要。",
         "pros": ["成本低、顏色可調", "不需氮氣高壓合成"],
         "cons": ["熱猝滅明顯", "吸濕水解、壽命差"],
         "makers": ["Intematix（早期）", "Toyoda Gosei（早期）", "中國多家"],
         "history": "2000 年代 Intematix、Toyoda Gosei 等公司推廣，曾是 YAG 專利未到期時的替代方案；YAG 專利到期與氮化物普及後式微。",
         "apps": "低功率指示燈、低價背光。",
         "src": "https://www.sciencedirect.com/science/article/abs/pii/S0022231314001276", "srcName": "Journal of Luminescence（(Ba,Sr)2SiO4:Eu 溫度特性）"},
        {"id": "ksf", "name": "KSF / PFS 線狀紅粉", "formula": "K2SiF6:Mn4+", "activator": "Mn4+",
         "color": "紅", "colorGroup": "橙／紅", "peak": 631, "peakText": "631 nm 主線（600–650 nm 多條）", "fwhm": 5, "fwhmText": "每條線約 5 nm",
         "status": "商用主流",
         "plain": "不含稀土的紅粉。錳(IV)在氟化物裡放出以 631 nm 為中心的幾條細線，紅光集中在人眼敏感的位置，LED 封裝光效比氮化物紅粉高 10% 以上，色純度極高。弱點是怕水（[MnF₆]²⁻ 會水解）、發光衰減時間長達毫秒級、藍光吸收弱所以用量大。",
         "pros": ["色純度極高，背光可達 DCI-P3", "光效比寬帶紅粉高 10%+", "不含稀土"],
         "cons": ["怕水氣，需核殼或疏水處理", "毫秒級衰減，高刷新率顯示有殘影疑慮", "R9 反而不如寬帶紅粉；專利仍受嚴密保護"],
         "makers": ["GE Current／Edison Innovations（專利）", "Nichia", "Denka", "三菱化學", "有研稀土（KGF）", "聚飛、穗晶（授權）"],
         "history": "GE 研究團隊（Setlur 等）2008–2012 年解決抗濕與色穩定問題，2015 年以 TriGain 商品化；2020 年 Nichia 成為第一家 TriGain 授權商。2026 年 SID 文章稱 KSF「稱霸廣色域顯示十年」、累計出貨逾 1,000 億顆；2026 年 8 月專利持有方 Edison Innovations 大舉授權億光、富采、木林森、Bridgelux 等廠。",
         "apps": "廣色域電視／筆電／車用顯示背光、高顯色照明。",
         "src": "https://sid.onlinelibrary.wiley.com/doi/10.1002/msid.70057", "srcName": "SID Information Display 2026（Murphy & Hendy）；LEDinside 2026-08"},
        {"id": "ktf", "name": "KTF／KGF 其他錳氟化物", "formula": "K2TiF6:Mn4+、K2GeF6:Mn4+", "activator": "Mn4+",
         "color": "紅", "colorGroup": "橙／紅", "peak": 632, "peakText": "約 630 nm", "fwhm": 6, "fwhmText": "線狀",
         "status": "商用初期",
         "plain": "與 KSF 同屬 A₂MF₆:Mn⁴⁺ 家族，性能相近（外部量子效率 >60%），是繞開 KSF 專利或改善性能的路線。中國有研稀土宣稱是唯一能批量供應鍺基氟化物紅粉的廠商。",
         "pros": ["性能接近 KSF", "專利路徑不同"],
         "cons": ["同樣怕水", "鍺較貴"],
         "makers": ["有研稀土", "多所中國大學"],
         "history": "2010 年代中期起中國與台灣（含臺大劉如熹團隊）大量研究 Mn⁴⁺ 氟化物，包括核殼防水、無 HF 合成等。",
         "apps": "背光與照明紅色成分。",
         "src": "https://lighting.ofweek.com/2018-09/ART-34002-8420-30268628.html", "srcName": "OFweek 照明網 2018"},
        {"id": "sla", "name": "SLA 窄頻紅氮化物", "formula": "Sr[LiAl3N4]:Eu2+", "activator": "Eu2+",
         "color": "紅", "colorGroup": "橙／紅", "peak": 650, "peakText": "約 650 nm", "fwhm": 50, "fwhmText": "約 50 nm（1,180 cm⁻¹）",
         "status": "商用初期",
         "plain": "2014 年慕尼黑大學 Schnick 團隊與 Lumileds 發表，半高寬只有 CASN 的一半，200 °C 仍保有室溫 95% 以上的量子效率。原型 LED 比市售高顯色 LED 效率高 14%。開啟了「UCr₄C₄ 型結構」窄頻 Eu²⁺ 螢光粉的研究熱潮。",
         "pros": ["窄頻、幾乎零熱猝滅", "R9 高又省能量"],
         "cons": ["峰值 650 nm 仍偏深紅", "合成困難、抗濕性差", "受 Lumileds／LMU 專利保護"],
         "makers": ["Lumileds（LUXEON 中功率產品）"],
         "history": "Nature Materials 2014；Lumileds 2016 年 12 月發布窄頻紅粉白皮書並導入中功率產品。",
         "apps": "高顯色高效率照明。",
         "src": "https://www.nature.com/articles/nmat4012", "srcName": "Nature Materials 2014"},
        {"id": "salon", "name": "SALON 窄頻紅氮氧化物", "formula": "Sr[Li2Al2O2N2]:Eu2+", "activator": "Eu2+",
         "color": "紅", "colorGroup": "橙／紅", "peak": 614, "peakText": "約 614 nm", "fwhm": 48, "fwhmText": "約 48 nm",
         "status": "研究階段",
         "plain": "2019 年發表的 SLA 進階版：峰值移到人眼更敏感的 614 nm，半高寬 48 nm，熱穩定性極佳。原型中功率白光 LED 比市售高顯色 LED 效率高 16%。窄譜來自 Eu²⁺ 周圍由 4 個氧與 4 個氮組成的高對稱立方體配位。",
         "pros": ["光譜位置最理想", "窄頻＋耐熱"],
         "cons": ["抗濕性是 UCr₄C₄ 型材料的共同弱點", "尚未見大規模量產報導"],
         "makers": ["ams OSRAM／LMU（開發）"],
         "history": "Nature Communications 2019（Hoerder、Seibald、Schnick 等）。2025 年 Laser & Photonics Reviews 綜述整理了十年來的 UCr₄C₄ 型家族。",
         "apps": "下一代高效高顯色 LED 的候選紅粉。",
         "src": "https://www.nature.com/articles/s41467-019-09632-w", "srcName": "Nature Communications 2019"},
        {"id": "ucr4c4", "name": "UCr₄C₄ 型窄頻氧化物家族", "formula": "RbLi(Li3SiO4)2:Eu2+、Na5K3(Li3SiO4)8:Eu2+ 等", "activator": "Eu2+",
         "color": "青／綠／紅（可調）", "colorGroup": "藍／青", "peak": 483, "peakText": "483（青）～532（綠）nm 等", "fwhm": 18, "fwhmText": "18–45 nm",
         "status": "研究階段",
         "plain": "以礦物 UCr₄C₄ 的剛性骨架衍生的一大類鋰矽酸鹽／鋁酸鹽，Eu²⁺ 在高對稱位置發出超窄光：2024 年的青色 Na₅K₃(Li₃SiO₄)₈:Eu²⁺ 半高寬只有 18 nm，2025 年機器學習找到的綠粉 CsRbKNa(Li₃SiO₄)₄:Eu²⁺ 為 44 nm。最大障礙是怕水。",
         "pros": ["半高寬可低至 20 nm 以下", "顏色可跨整個可見光調整"],
         "cons": ["潮濕環境迅速劣化", "多為實驗室成果"],
         "makers": ["華南理工大學（夏志國）", "廈門大學", "LMU 慕尼黑"],
         "history": "2018 年起華南理工夏志國、LMU Schnick 等團隊陸續發表；2025 年 Laser & Photonics Reviews 綜述。",
         "apps": "廣色域背光、Micro LED 色轉換的潛在材料。",
         "src": "https://onlinelibrary.wiley.com/doi/10.1002/lpor.202500740", "srcName": "Laser & Photonics Reviews 2025（綜述）"},
        {"id": "cyan", "name": "青色缺口螢光粉", "formula": "Ba2Y5B5O17:Ce3+、LuMgAl5SiO12:Ce3+ 等", "activator": "Ce3+ / Eu2+",
         "color": "藍青", "colorGroup": "藍／青", "peak": 490, "peakText": "480–500 nm", "fwhm": 60, "fwhmText": "約 50–70 nm",
         "status": "商用初期",
         "plain": "傳統白光 LED 在 480–500 nm 有個凹陷（青色缺口），會拉低顯色與生理刺激指標。近年出現專門補這段的 Ce³⁺ 硼酸鹽、石榴石與青光 LED；Nichia 的 Vitasolis、Bridgelux Thrive 等產品就是靠補青色做出更接近日光的光譜。",
         "pros": ["讓光譜連續、接近日光", "支援以人為本照明"],
         "cons": ["效率通常低於 YAG", "多數仍在改良"],
         "makers": ["Nichia", "Bridgelux", "多所大學"],
         "history": "2020 年 Chem. Mater. 的 NaMgBO₃:Ce³⁺、2023 年 PMC 綜述、2024 年 ACS AMI 的藍光激發青粉。",
         "apps": "全光譜與人因照明。",
         "src": "https://pmc.ncbi.nlm.nih.gov/articles/PMC10616965/", "srcName": "PMC 2023 綜述（cyan gap）"},
        {"id": "bam", "name": "BAM 藍粉", "formula": "BaMgAl10O17:Eu2+", "activator": "Eu2+",
         "color": "藍", "colorGroup": "藍／青", "peak": 450, "peakText": "約 450 nm", "fwhm": 61, "fwhmText": "約 60 nm",
         "status": "商用",
         "plain": "日光燈與電漿電視的標準藍粉，也是「紫光晶片＋紅綠藍三色粉」全光譜 LED 的藍色來源。內部量子效率約 87%，長期問題是使用中劣化（Eu²⁺ 氧化與缺陷）。",
         "pros": ["可被近紫外高效激發", "製程成熟"],
         "cons": ["使用中會劣化", "只適合紫光／紫外激發架構"],
         "makers": ["Nichia", "三菱化學", "中國多家"],
         "history": "1970 年代飛利浦三基色配方的藍色成員之一，後用於 PDP 與紫光 LED。",
         "apps": "螢光燈管、紫光激發全光譜 LED。",
         "src": "https://www.sciencedirect.com/science/article/abs/pii/S0921452609013386", "srcName": "Physica B（BAM 熱穩定性）"},
        {"id": "phosphate", "name": "磷酸鹽藍／青粉", "formula": "Sr5(PO4)3Cl:Eu2+、Ca9ZnK(PO4)7:Eu2+ 等", "activator": "Eu2+",
         "color": "藍～青", "colorGroup": "藍／青", "peak": 445, "peakText": "445–490 nm", "fwhm": 60, "fwhmText": "約 50–70 nm",
         "status": "商用初期",
         "plain": "化學穩定、效率高，激發範圍正好對應近紫外晶片（240–420 nm），是紫光激發全光譜 LED 常用的藍色與青色成分。",
         "pros": ["穩定、便宜", "適合紫外／紫光激發"],
         "cons": ["藍光激發效率低"],
         "makers": ["多家"],
         "history": "磷灰石結構自 1940 年代鹵磷酸鹽以來就是照明主力；2026 年仍有新的青色磷酸鹽發表。",
         "apps": "全光譜 LED、紫外 LED。",
         "src": "https://www.sciencedirect.com/science/article/abs/pii/S0925838826038466", "srcName": "Journal of Alloys and Compounds 2026"},
        {"id": "mn4oxide", "name": "Mn⁴⁺ 氧化物深紅粉", "formula": "3.5MgO·0.5MgF2·GeO2:Mn4+（MFG）等", "activator": "Mn4+",
         "color": "深紅", "colorGroup": "橙／紅", "peak": 658, "peakText": "650–660 nm", "fwhm": 25, "fwhmText": "數條線，整體約 20–30 nm",
         "status": "商用",
         "plain": "錳(IV)在氧化物中的發光偏深紅（650–660 nm），衰減比氟化物快、不怕水，但藍光吸收弱，所以照明主流仍是氟化物；園藝燈需要深紅光時會用它。",
         "pros": ["不怕水、不含稀土", "深紅光適合植物"],
         "cons": ["藍光吸收弱", "人眼敏感度低"],
         "makers": ["多家"],
         "history": "MFG 是螢光燈時代就有的老材料；2018 年 Light: Science & Applications 比較了氧化物與氟化物 Mn⁴⁺ 的差異。",
         "apps": "園藝照明、顯色補紅。",
         "src": "https://www.nature.com/articles/s41377-018-0013-1", "srcName": "Light: Science & Applications 2018"},
        {"id": "nir", "name": "Cr³⁺ 近紅外螢光粉", "formula": "ScBO3:Cr3+、Ga 石榴石:Cr3+ 等", "activator": "Cr3+",
         "color": "近紅外（不可見）", "colorGroup": "遠紅／近紅外", "peak": 800, "peakText": "700–1000 nm", "fwhm": 120, "fwhmText": "約 100–200 nm",
         "status": "商用初期",
         "plain": "藍光激發後放出寬頻近紅外光，讓一顆 LED 變成迷你光譜儀光源。ams OSRAM 2020 年推出的 OSLON P1616 SFH 4737 只有 1.6 mm 見方，光譜涵蓋 650–1050 nm（刻意對準便宜的矽偵測器）、350 mA 時輸出 74 mW，用於食品成分、農產品品質、藥物真偽檢測。2025 年的新材料把峰值推到 785–866 nm、發光範圍延伸到 1250 nm，並用 Yb³⁺ 共摻雜補上 1000 nm 附近。",
         "pros": ["不含稀土", "光譜寬，適合光譜分析", "配合矽偵測器即可組成低成本光譜儀"],
         "cons": ["輸出功率仍偏低（商品 74 mW、論文 28 mW 等級）", "內部量子效率多在 60–70%，熱猝滅待改善"],
         "makers": ["ams OSRAM", "Lumileds", "多所中國與台灣大學"],
         "history": "2016 年 OSRAM 提出藍光晶片激發螢光粉的近紅外 pc-LED 概念；此後 Cr³⁺ 石榴石、硼酸鹽、磷酸鹽成為熱門研究題目。",
         "apps": "食品與農產品檢測、生醫感測、夜視、防偽。",
         "src": "https://www.led-professional.com/products-services/osram-presents-the-worlds-smallest-broadband-ir-led-for-spectroscopy-applications", "srcName": "LED professional（OSRAM SFH 4737）"},
        {"id": "glow", "name": "長餘輝夜光粉", "formula": "SrAl2O4:Eu2+,Dy3+（及 CaAl2O4、Sr4Al14O25 系）", "activator": "Eu2+（Dy3+ 為陷阱）",
         "color": "黃綠", "colorGroup": "黃／綠", "peak": 520, "peakText": "約 520 nm", "fwhm": 90, "fwhmText": "約 90 nm",
         "status": "商用主流",
         "plain": "1996 年 Matsuzawa 等人發表在鋁酸鍶中共摻鏑，餘輝亮度比舊的硫化鋅高十倍以上、可持續十幾個小時。原理是 Dy³⁺ 等形成深約 0.6–0.7 eV 的「陷阱」把電子存起來，室溫熱能再慢慢把電子搖出來發光。同家族的 CaAl₂O₄:Eu,Nd 發藍光（約 440 nm）、Sr₄Al₁₄O₂₅:Eu,Dy 發藍綠光（約 490 nm）；黃綠色的 SrAl₂O₄ 最亮，因為 520 nm 正好落在人眼夜間最敏感的波段。",
         "pros": ["無放射性、亮且持久", "成本低", "顏色可由基質選擇（藍、藍綠、黃綠）"],
         "cons": ["怕水（需包覆）", "紅色與近紅外長餘輝仍是難題", "藍光 LED 用途有限"],
         "makers": ["根本特殊化學（LumiNova）", "大連路明", "多家中國廠"],
         "history": "1996 年 8 月發表於 J. Electrochem. Soc.，同時期 Takasaki 等人獨立報告類似結果，帶動長餘輝材料研究熱潮。",
         "apps": "安全標示、道路標線、手錶、玩具。",
         "src": "https://pmc.ncbi.nlm.nih.gov/articles/PMC5445854/", "srcName": "Materials 2010 綜述（PMC）"},
        {"id": "upconv", "name": "上轉換螢光粉", "formula": "NaYF4:Yb3+,Er3+／Tm3+", "activator": "Er3+ / Tm3+（Yb3+ 敏化）",
         "color": "綠／藍（近紅外激發）", "colorGroup": "白／其他", "peak": 540, "peakText": "540（綠）、450（藍）nm", "fwhm": 20, "fwhmText": "線狀",
         "status": "商用初期",
         "plain": "反其道而行：吸收兩個以上的紅外光子，放出一個可見光子。1972 年即知 NaYF₄:Yb,Er 是效率最高的上轉換材料，今日奈米版本用於生醫影像、防偽油墨、紅外偵測。",
         "pros": ["近紅外激發，生物組織穿透深", "防偽難以仿造"],
         "cons": ["效率低（多光子過程）", "需高功率雷射激發"],
         "makers": ["多家特用化學與奈米材料公司"],
         "history": "Applied Physics Letters 1972 首次報導；2000 年代奈米化後成為生醫熱點。",
         "apps": "防偽、生醫影像、太陽能電池補光研究。",
         "src": "https://pubs.aip.org/aip/apl/article/21/4/159/528541/NaYF4-Yb-Er-an-efficient-upconversion-phosphor", "srcName": "Applied Physics Letters 1972"},
        {"id": "scint", "name": "閃爍體", "formula": "CsI:Tl、Gd2O2S:Tb、LYSO:Ce、GAGG:Ce", "activator": "Tl+ / Tb3+ / Ce3+",
         "color": "綠～黃綠", "colorGroup": "白／其他", "peak": 550, "peakText": "420–550 nm（依材料）", "fwhm": 100, "fwhmText": "寬帶",
         "status": "商用主流",
         "plain": "把 X 光、γ 射線轉成可見光的螢光材料。醫療數位 X 光平板最常用柱狀 CsI:Tl 與便宜的 Gd₂O₂S:Tb 粉末；正子造影用 LYSO:Ce；GAGG:Ce 石榴石則是近年高能物理與安檢的新寵。",
         "pros": ["成熟且不可替代", "石榴石可燒成透明陶瓷"],
         "cons": ["CsI 吸濕", "高端單晶昂貴"],
         "makers": ["Luxium（原 Saint-Gobain）", "濱松", "CRYTUR", "上海矽酸鹽研究所"],
         "history": "與 CRT 螢光粉同源；2019 年 Medical Physics 比較了 CsI:Tl 與 GOS 平板的成像表現。",
         "apps": "醫療影像、安檢、高能物理。",
         "src": "https://aapm.onlinelibrary.wiley.com/doi/abs/10.1002/mp.13791", "srcName": "Medical Physics 2019"},
        {"id": "qd", "name": "量子點（競爭技術）", "formula": "CdSe/ZnS、InP/ZnS、CsPbBr3（鈣鈦礦）", "activator": "半導體奈米晶（非離子活化）",
         "color": "全色可調", "colorGroup": "白／其他", "peak": 630, "peakText": "粒徑決定", "fwhm": 30, "fwhmText": "20–40 nm",
         "status": "商用",
         "plain": "不是傳統螢光粉，但做的是同一件事（藍光轉紅綠）。譜帶比多數螢光粉窄、色域可接近 Rec.2020，在高階電視（QD 膜、QD-OLED）與 Micro LED 色轉換上是主要對手。缺點是含鎘或含鉛、需阻隔水氧、成本高。",
         "pros": ["色域最大", "可噴墨、可做極薄膜"],
         "cons": ["穩定性與法規（鎘、鉛）", "成本高於 KSF 方案"],
         "makers": ["Nanosys／Shoei", "Samsung", "納晶科技", "Nanoco"],
         "history": "2013 年起用於電視背光膜；2024 年 Omdia 統計含量子點的 LCD 電視出貨 2,440 萬台。",
         "apps": "高階電視、顯示器、Micro LED 色轉換。",
         "src": "https://www.nanosys.com/blog-newsroom/omdia-shipments-of-qd-miniled-tvs-to-surpass-oled-tvs-by-2025", "srcName": "Nanosys／Omdia 2024"},
        {"id": "lamp", "name": "螢光燈管螢光粉（淘汰中）", "formula": "鹵磷酸鹽 Ca5(PO4)3(F,Cl):Sb,Mn；三基色 BAM／LAP／YOX", "activator": "Sb3+,Mn2+ / Eu2+,Tb3+,Eu3+",
         "color": "白（混合）", "colorGroup": "白／其他", "peak": 0, "peakText": "多成分", "fwhm": 0, "fwhmText": "—",
         "status": "淘汰中",
         "plain": "用 254 nm 汞紫外線激發的照明螢光粉：1942 年的鹵磷酸鹽讓日光燈效率翻倍，1974 年飛利浦的稀土三基色配方（藍 BAM、綠 LaPO₄:Ce,Tb、紅 Y₂O₃:Eu）大幅提升顯色並催生省電燈泡。2023 年起歐盟依 RoHS 淘汰含汞燈管，這類螢光粉需求快速萎縮。",
         "pros": ["技術成熟、極便宜"],
         "cons": ["依賴含汞燈管，法規淘汰中", "鋱、銪用量大"],
         "makers": ["Nichia", "三菱化學", "有研稀土", "Signify（自用）"],
         "history": "1938 年 GE 讓日光燈商業化；1942 年 McKeag 團隊發明鹵磷酸鹽；1974 年 Verstegen 的三波長配方。",
         "apps": "日光燈管、省電燈泡（逐步退出）。",
         "src": "https://www.sciencedirect.com/science/article/abs/pii/0254058487901039", "srcName": "Phosphors based on rare-earths（1987）"},
    ],
    "compare": {
        "columns": ["材料", "化學式", "峰值 (nm)", "半高寬 (nm)", "顏色", "主要用途", "商業狀態"],
        "rows": [
            ["YAG:Ce", "Y3Al5O12:Ce3+", "530–560", "110–120", "黃", "一般照明", "主流"],
            ["LuAG:Ce", "Lu3Al5O12:Ce3+", "510–535", "100–120", "綠", "高顯色、雷射", "商用"],
            ["β-SiAlON:Eu", "Si6-zAlzOzN8-z:Eu2+", "535–540", "55", "綠", "廣色域背光", "主流"],
            ["SCASN:Eu", "(Sr,Ca)AlSiN3:Eu2+", "610–630", "80–90", "橙紅", "暖白照明", "主流"],
            ["CASN:Eu", "CaAlSiN3:Eu2+", "650", "80–120", "深紅", "高顯色暖白", "主流"],
            ["KSF:Mn", "K2SiF6:Mn4+", "631（多線）", "≈5（每線）", "紅", "廣色域背光、高顯色", "主流"],
            ["SLA:Eu", "Sr[LiAl3N4]:Eu2+", "650", "50", "紅", "高效高顯色", "初期"],
            ["SALON:Eu", "Sr[Li2Al2O2N2]:Eu2+", "614", "48", "紅", "下一代紅粉", "研究"],
            ["BAM:Eu", "BaMgAl10O17:Eu2+", "450", "60", "藍", "紫光激發全光譜", "商用"],
            ["Cr3+ NIR", "ScBO3:Cr3+ 等", "700–1000", "100–200", "近紅外", "光譜感測", "初期"],
            ["SrAl2O4:Eu,Dy", "SrAl2O4:Eu2+,Dy3+", "520", "90", "黃綠", "夜光標示", "主流"],
            ["量子點", "CdSe / InP / CsPbBr3", "可調", "20–40", "全色", "高階顯示", "商用"],
        ],
        "note": "數值為文獻與廠商規格的典型範圍，同一家族會因組成、活化劑濃度與量測條件而異；KSF 的「半高寬」指單條譜線。",
    },
}
