# -*- coding: utf-8 -*-
"""最新動態：2024 年至整理時點（2026-09）的重要事件，每則附日期、為什麼重要與來源。
date 用 YYYY-MM 或 YYYY-MM-DD；tags 採固定詞彙供篩選：產品、論文、專利授權、法規與標準、市場、併購與重整、獎項、
顯示背光、雷射照明、量子點、KSF、稀土、Micro LED、近紅外、台灣、健康照明、園藝、車用、閃爍體、AI 材料。
confidence：high＝一手來源；medium＝二手或單一媒體；low＝轉載或口徑不明。"""

NEWS = {
    "lead": "把 2023 年下半年到 2026 年 9 月之間跟螢光粉直接相關的產品發表、論文、專利授權、法規、市場數字與併購排成一條時間線（共一百餘則）。每則都標了「為什麼重要」與信心等級，可依年份、主題或地區篩選。整體趨勢是：材料創新加速（新綠粉結構、雷射陶瓷、近紅外、鈣鈦礦）、供應鏈與專利重組（KSF 專利轉手、稀土管制、Lumileds 收購被擋）、顯示端的路線之爭（RGB 背光 vs 色轉換）。",
    "items": [
        # ---------------- 2026 ----------------
        {"date": "2026-09-01", "title": "億光泰國新廠動土，強化 AI 與車用 LED 供應鏈", "region": "台灣", "tags": ["市場", "台灣", "車用"],
         "detail": "億光電子在泰國北柳府舉行新製造基地動土典禮，作為因應關稅與地緣風險、服務 AI 與車用市場的全球製造布局。",
         "why": "台灣 LED 封裝廠（含 KSF 授權產品）把產能外移東南亞，回應美國關稅與中國供應鏈風險。", "entities": ["億光"], "confidence": "high",
         "src": "https://www.ledinside.com/news/2026/8/2026_09_01_01", "srcName": "LEDinside 2026-09-01"},
        {"date": "2026-08-31", "title": "Edison Innovations 專訪：KSF 授權網涵蓋台、中、韓、美，下一步是次微米 KSF 墨水", "region": "美國／台灣", "tags": ["專利授權", "KSF", "顯示背光", "Micro LED"],
         "detail": "GE 約 2,500 件專利在 2025 年初轉到 Edison Innovations。2026 年已授權億光、富采、Coreach、曼森、木林森、惠州 Torch、惠州 DOJ、韓國 Lumens 與美國 Bridgelux；並與 Current Chemicals 開發可印刷的次微米高吸收 KSF，瞄準未來 3–5 年的車用顯示與 Mini／Micro LED 市場。KSF 專利方統計：美國展廳車用顯示器逾四成、Display Week 2025 車用 LCD 逾七成採用 KSF，2014–2025 年 KSF LED 累計出貨逾 1,000 億顆。",
         "why": "KSF 是少數仍受嚴密專利保護的主流螢光粉；台灣封裝廠取得授權，代表車用與 Mini LED 背光市場的合規供應鏈成形。採用率數字來自授權方，具利益關係。", "entities": ["Edison Innovations", "億光", "富采", "Bridgelux"], "confidence": "high",
         "src": "https://www.ledinside.com/interview/2026/8/2026_08_31_01", "srcName": "LEDinside 專訪 2026-08-31"},
        {"date": "2026-08-24", "title": "TrendForce：2025 年 Mini LED 電視 1,156 萬台，2026 年 RGB Mini LED 上看 170–200 萬台", "region": "全球", "tags": ["市場", "顯示背光"],
         "detail": "Mini LED 背光電視 2025 年出貨年增 50%；2026 年 RGB Mini LED 電視預測上修至 170 萬台、有機會逼近 200 萬台。Mini LED 背光採用大量 LED，是 KSF／β-SiAlON 或量子點膜的主要出海口，而 RGB Mini LED 改用三色晶片則不需要螢光粉。",
         "why": "Mini LED 放量是螢光粉需求的正面訊號，RGB Mini LED 則是高階市場「去色轉換化」的隱憂。", "entities": ["TrendForce"], "confidence": "medium",
         "src": "https://www.ledinside.com/intelligence/2026/8/2026_08_24_05", "srcName": "LEDinside／TrendForce 2026-08"},
        {"date": "2026-08-21", "title": "市場報告：2025 年全球螢光粉市場約 82.6 億美元、中國產量 4.8 萬噸（口徑不明）", "region": "中國", "tags": ["市場"],
         "detail": "新浪財經轉載的《2026 年中國 LED 照明行業報告》稱 2025 年全球螢光粉市場 82.6 億美元（年增 5.3%），LED 照明與顯示占 67.4%，中國產量 4.8 萬噸、消費量占全球 43.2%；材料形態由粉末走向陶瓷與玻璃。",
         "why": "與 2023 年「中國 LED 螢光粉 600 噸」相差數十倍，說明市場數字的口徑差異極大；本站只當量級參考。", "entities": ["市場研究報告"], "confidence": "low",
         "src": "https://finance.sina.com.cn/wm/2026-08-21/doc-iniparar1564485.shtml", "srcName": "新浪財經 2026-08-21（轉載）"},
        {"date": "2026-08-17", "title": "日本 2026 年上半年釔進口年減 74% 至 204 噸、鏑進口年減 82%", "region": "日本／中國", "tags": ["稀土", "市場"],
         "detail": "TrendForce 引述日本海關資料，2025 年 12 月以來中國對日氧化釔出口極少；三井金屬原計畫以中國釔原料生產半導體設備用稀土材料，因供應不足幾乎無法出口。日本自 2011 年起透過 JOGMEC 與雙日投資 Lynas 確保重稀土。",
         "why": "釔是 YAG:Ce 黃粉的基質元素，日本是最大的高階螢光粉生產國，進口驟減直接衝擊其成本與供應。", "entities": ["三井金屬", "JOGMEC"], "confidence": "high",
         "src": "https://www.trendforce.com/news/2026/08/17/news-china-rare-earth-curbs-send-japan-dysprosium-imports-down-82-in-1h26-chip-supply-chain-feels-squeeze/", "srcName": "TrendForce 2026-08-17"},
        {"date": "2026-08-13", "title": "Edison Innovations 將 KSF 專利授權給美國 Bridgelux；8 月 24 日再授權惠州 Torch", "region": "美國／中國", "tags": ["專利授權", "KSF"],
         "detail": "由 Dominion Harbor 執行長 David Pridham 與 Bridgelux 執行長李宜群共同宣布，Bridgelux（隸屬木林森集團）將 KSF 用於高階顯示；8 月 24 日 Edison 再授權 2009 年成立的 LED 背光廠惠州 Torch Energy，用於 Mini／Micro LED 背光模組。",
         "why": "美國本土 LED 廠加入 KSF 授權，使授權網絡涵蓋美、台、中主要封裝廠。", "entities": ["Edison Innovations", "Bridgelux", "惠州 Torch"], "confidence": "high",
         "src": "https://www.ledinside.com/news/2026/8/2026_08_13_02", "srcName": "LEDinside 2026-08-13"},
        {"date": "2026-08", "title": "Gallant Capital 買下 Lumileds 多數優先擔保貸款，但未取得所有權", "region": "美國", "tags": ["併購與重整", "市場"],
         "detail": "私募基金透過次級市場買下 Lumileds 優先擔保定期貸款的多數部位，非股權出售，公司治理、經營團隊與客戶承諾不變。分析指出任何有中資背景的買家都會面臨與三安案相同的國安審查，以債權介入是一種繞道安排。",
         "why": "Lumileds 是 Lumiramic 陶瓷螢光片與 SLA 窄頻紅粉的擁有者，其所有權懸而未決是這些技術走向的變數。", "entities": ["Lumileds", "Gallant Capital"], "confidence": "high",
         "src": "https://inside.lighting/news/26-08/lumileds-private-equity-deal-stops-short-ownership", "srcName": "Inside Lighting 2026-08"},
        {"date": "2026-08", "title": "臺大劉如熹團隊在 ACS Energy Letters 報導 1547 nm 近紅外螢光粉，內量子效率 68.8%", "region": "台灣", "tags": ["論文", "近紅外", "台灣"],
         "detail": "〈Phosphor Materials for Extended NIR-III Window〉報導部分反尖晶石 MgGa₂O₄ 共摻 Cr³⁺ 與 Er³⁺，在 460 nm 藍光激發下於 1547 nm 得到窄帶發光，內量子效率 68.8%；同年另在 Adv. Opt. Mater. 以 In³⁺ 取代調控 MgGa₂O₄:Cr³⁺,Ni²⁺ 的近紅外發光。",
         "why": "把藍光可激發的螢光粉推進到 1,500 nm 以上的 NIR-III 窗口，是台灣螢光粉研究的代表性成果。數值取自摘要。", "entities": ["劉如熹", "臺灣大學"], "confidence": "medium",
         "src": "https://pubs.acs.org/aelccp/article/11/8/5275/5171943/Phosphor-Materials-for-Extended-NIR-III-Window", "srcName": "ACS Energy Letters 2026"},
        {"date": "2026-07-30", "title": "億光在美國控告日亞高功率 LED 侵害覆晶專利；雙方 YAG 之爭並未和解", "region": "台灣／日本", "tags": ["專利授權", "台灣"],
         "detail": "億光在密西根東區法院控告日亞侵害其覆晶封裝專利 US 7,554,126，是億光 2026 年繼控告 Lumileds、首爾半導體後的第三件美國覆晶專利訴訟。此前日亞 2025 年 3 月在杜塞道夫依已確定的 YAG 專利侵權判決向億光求償 250 萬歐元；億光回應該歐洲專利已於 2017 年 7 月到期。",
         "why": "更正常見誤解：日亞與億光從未在 2022 年和解，YAG 專利戰延燒成覆晶專利互告。", "entities": ["億光", "日亞化學"], "confidence": "high",
         "src": "https://www.nichia.co.jp/en/newsroom/2025/2025_042201.html", "srcName": "日亞新聞稿 2025-04（求償）"},
        {"date": "2026-07-20", "title": "歐盟啟動數位產品護照登錄系統，照明產品納入 ESPR 框架", "region": "歐洲", "tags": ["法規與標準"],
         "detail": "LED 照明產品同時受 (EU) 2019/2020 生態設計、2024 年 7 月生效的永續產品生態設計法規（ESPR）、EPREL 登錄與可替換性要求規範。",
         "why": "螢光粉與 LED 封裝的材料揭露（含稀土、鎘）未來將成為歐洲市場合規的一部分。來源為產業部落格整理。", "entities": ["歐盟執委會"], "confidence": "low",
         "src": "https://www.olamled.com/led-lighting-regulations-in-the-eu-2026/", "srcName": "OLAMLED（產業整理）"},
        {"date": "2026-06-24", "title": "臺大劉如熹團隊於 Progress in Materials Science 發表〈突破 1700 nm〉NIR-III 螢光粉設計原則", "region": "台灣", "tags": ["論文", "近紅外", "台灣"],
         "detail": "提出三項策略：以化學取代與陽離子工程調控晶場使 Ni²⁺ 等過渡金屬寬頻發光紅移、以奈米結構與界面工程降低表面缺陷與高頻振動損失、選擇低聲子能量且剛性佳的基質；鎖定生醫影像、夜視與食品檢測。同日中村修二獲牛津大學榮譽理學博士。",
         "why": "把近紅外螢光粉的研究前沿從 NIR-I／II 推向超過 1700 nm 的 NIR-III。", "entities": ["劉如熹", "臺灣大學"], "confidence": "high",
         "src": "https://www.ntu.edu.tw/spotlight/2026/2500_20260624.html", "srcName": "臺大焦點新聞 2026-06-24"},
        {"date": "2026-06-09", "title": "Edison Innovations 與億光續簽 KSF 授權；同月擴大惠州 DOJ 授權並與 Lumens 簽 10 年新約", "region": "台灣／韓國／中國", "tags": ["專利授權", "KSF", "台灣"],
         "detail": "與億光的付費授權涵蓋行動、車用與消費電子 LED；6 月 3 日授權廣東曼森，6 月 29 日擴大與惠州 DOJ 的協議納入 GE 自首爾半導體購入的 KSF 專利；Lumens 簽下 10 年新約並成為首家將授權擴及首爾 KSF 專利組合的公司。",
         "why": "KSF 專利池在 2026 年完成對台灣兩大封裝廠與多家中韓廠的授權，確立其為 Mini LED 背光紅光的產業標準。", "entities": ["Edison Innovations", "億光", "Lumens"], "confidence": "high",
         "src": "https://www.pr-inside.com/edison-innovations-renews-license-agreement-with-everlight-electronics-r5190328.htm", "srcName": "PR-inside（ACCESS Newswire 轉載）2026-06"},
        {"date": "2026-06", "title": "中國把 MP Materials 等 10 家美企列入出口管制名單；稀土執法持續升高", "region": "中國／美國", "tags": ["稀土", "法規與標準"],
         "detail": "2026 年 1 月 1 日生效的出口許可目錄已新增釤、釓、鎦化合物；6 月再將 MP Materials、USA Rare Earth 等 10 家美國實體列入管制名單，5 月並有日籍人員因涉稀土物項走私在大連被拘。S&P Global 預期稀土供應瓶頸延續整個 2026 年。",
         "why": "即使 10 月管制暫緩，稀土出口管制的執法強度在 2026 年持續升高，螢光粉用稀土的供應風險並未解除。", "entities": ["中國商務部", "MP Materials"], "confidence": "medium",
         "src": "https://www.morganlewis.com/pubs/2026/07/recent-china-export-control-actions-signal-active-enforcement-for-rare-earths-and-strategic-minerals", "srcName": "Morgan Lewis 2026-07"},
        {"date": "2026-05-13", "title": "NIMS：CASN 紅粉中國專利歷經七年無效訴訟，全部請求項確定有效", "region": "日本／中國", "tags": ["專利授權"],
         "detail": "中國專利第 200580005112.5 號（涵蓋 CASN／SCASN 紅粉 LED 裝置）自 2019 年起被江蘇博睿多次提出無效請求，2020 年曾被裁定部分無效；2025 年 12 月 25 日最高人民法院撤銷該裁定並發回，博睿隨後撤回請求，2026 年 4 月 2 日全部請求項確定有效。",
         "why": "確認氮化物紅粉的專利在中國仍有效，對三菱化學、Denka 等授權製造商與中國廠商的競爭格局影響直接。", "entities": ["NIMS", "三菱化學", "江蘇博睿"], "confidence": "high",
         "src": "https://www.nims.go.jp/eng/press/2026/05/202605130.html", "srcName": "NIMS 新聞稿 2026-05-13"},
        {"date": "2026-05-05", "title": "Samsung Display 在 Display Week 2026 展出 18 吋 500 nits 無鎘電致發光量子點原型", "region": "韓國", "tags": ["量子點", "顯示背光", "產品"],
         "detail": "EL-QD 是量子點自己通電發光、不需 OLED 或 LED 的形態。18 吋 500 nits 與 6.5 吋 400 nits 原型亮度分別比前一年提升 25% 與 33%，皆為無鎘配方；Display Week 2026 新增鈣鈦礦與無鉛衍生物專場。商用時程未公布。",
         "why": "若 EL-QD 商用，顯示器將不再需要色轉換層；但距離量產仍遠，螢光粉與量子點色轉換在可見的未來仍是主流。", "entities": ["Samsung Display"], "confidence": "high",
         "src": "https://global.samsungdisplay.com/31450", "srcName": "Samsung Display 新聞稿"},
        {"date": "2026-05", "title": "機器學習引導的 Cs₂Zr(Cl,Br)₆:Mo⁴⁺/Sb³⁺ 鹵化物近紅外螢光粉：920 nm、內量子效率 92.4%", "region": "中國", "tags": ["論文", "近紅外", "AI 材料"],
         "detail": "以機器學習引導共摻雜策略設計的鹵化物近紅外螢光粉，在 920 nm 達到內／外量子效率 92.4%／65.9% 的紀錄，目標為 AI 輔助醫學影像；2026 年 2 月 RSC Advances 另刊出僅憑組成預測 Mn⁴⁺ 螢光粉激發／發射波長的模型，6 月廈大宋坤傑與解榮軍在《無機材料學報》發表機器學習驅動發光材料研發的中文綜述。",
         "why": "AI 輔助設計已從「找基質」延伸到「調共摻雜」，且產出效率紀錄。期刊名未在摘要中顯示。", "entities": ["廈門大學"], "confidence": "medium",
         "src": "https://pmc.ncbi.nlm.nih.gov/articles/PMC13377217/", "srcName": "PMC 2026-05"},
        {"date": "2026-04-27", "title": "日亞與研究機構證實 1800K 高壓鈉燈色 LED 較不吸引昆蟲，並擴充 NVSW219GL3 低色溫產品", "region": "日本", "tags": ["產品", "論文"],
         "detail": "日亞 2026 年 3 月擴充高功率 LED NVSW219GL3 的低色溫（含 1800K）產品，4 月 27 日公布聯合研究：模擬高壓鈉燈色的 1800K LED 對昆蟲的吸引力低於其他色溫。",
         "why": "以螢光粉配方模擬高壓鈉燈光色，兼顧 ANSI C78.377-2024 新增的 1800K 規範與生態友善照明需求。", "entities": ["日亞化學"], "confidence": "high",
         "src": "https://www.ledinside.com/products/2026/4/2026_04_27_04", "srcName": "LEDinside 2026-04-27"},
        {"date": "2026-04-22", "title": "Sony、大阪大學與岩崎電氣展出藍光 VCSEL 陣列＋螢光體的分割式雷射照明", "region": "日本", "tags": ["雷射照明", "產品"],
         "detail": "在 OPIE 2026 展出以二維藍光面射型雷射（VCSEL）陣列搭配螢光體的位置分割雷射照明裝置，不需掃描鏡即可電控配光；為 NEDO 2023–2026 年度補助計畫。同日中科院福建物構所發表稀土摻雜光激勵發光材料綜述。",
         "why": "VCSEL 激發螢光粉是繼邊射型雷射之後的新雷射照明架構，日本產官學聯手推進。", "entities": ["Sony", "大阪大學", "岩崎電氣"], "confidence": "medium",
         "src": "https://optronics-media.com/news/20260422/109186/", "srcName": "OPTRONICS ONLINE 2026-04-22"},
        {"date": "2026-04-17", "title": "美國 CFIUS 以國安理由封殺三安／Inari 收購 Lumileds，交易 4 月 30 日終止", "region": "美國／中國", "tags": ["併購與重整", "法規與標準"],
         "detail": "CFIUS 認定交易存在「無法化解的國安風險」並要求撤件，三安光電與 Inari Amertron 致函撤回申報並放棄收購，4 月 30 日簽署終止協議；未支付任何款項、未移轉股份。這是繼 2016 年 33 億美元金沙江收購案後 Lumileds 第二次被美國擋下中資收購；3 月 Lumileds 已確認關閉聖荷西製造據點，三安 2025 年首度年度虧損且實際控制人 3 月被留置調查。",
         "why": "確立 LED（含車用照明與螢光粉技術）被美國視為敏感技術，中國廠商透過併購取得西方 LED 資產的路徑幾近封閉。", "entities": ["Lumileds", "三安光電", "Inari", "CFIUS"], "confidence": "high",
         "src": "https://inside.lighting/news/26-04/us-regulators-block-proposed-lumileds-acquisition", "srcName": "Inside Lighting 2026-04"},
        {"date": "2026-04-07", "title": "CEA-Leti 以脈衝雷射沉積製作鈣鈦礦薄膜色轉換層，用於全彩 Micro LED 微顯示", "region": "歐洲", "tags": ["論文", "Micro LED", "量子點"],
         "detail": "法國 CEA-Leti 在 200 mm 晶圓上均勻沉積無機鹵化物鈣鈦礦色轉換層（綠光 CsPbBr₃、紅光 CsPbI₂Br），克服量子點吸收率低、需 3–10 µm 厚度而難以縮小像素的問題；瑞典 Polar Light 亦獲 110 萬歐元 Eurostars 經費開發雙色 Micro LED 微顯示。",
         "why": "鈣鈦礦薄膜是量子點之後 Micro LED 色轉換最受矚目的材料路線，歐洲研究機構搶先實現晶圓級製程。", "entities": ["CEA-Leti"], "confidence": "high",
         "src": "https://www.trendforce.com/news/2026/04/07/news-two-key-breakthroughs-advance-full-color-micro-led-microdisplays/", "srcName": "TrendForce 2026-04-07"},
        {"date": "2026-04-01", "title": "友達於 Touch Taiwan 2026 展示 Micro LED 量產成熟度；台灣串起 Micro LED 光通訊供應鏈", "region": "台灣", "tags": ["Micro LED", "產品", "台灣"],
         "detail": "AUO 以 Micro LED 為核心技術平台展示透明模組的量產能力；富采與友達、鼎元展示 Micro LED 光通訊，錼創展示高密度陣列。富采 2026 年第一季 Micro LED 正式量產；2025 年富采營收 221.8 億元、淨損 27.1 億元，晶電與隆達已合併為富采光電。",
         "why": "台灣 Micro LED 生態系從顯示走向 AI 光通訊，是 2026 年台灣 LED 產業的主軸；傳統 LED（含螢光粉封裝）獲利困難。", "entities": ["友達", "富采", "錼創"], "confidence": "high",
         "src": "https://www.ledinside.com/news/2026/4/2026_04_01_03", "srcName": "LEDinside 2026-04-01"},
        {"date": "2026-03-19", "title": "TrendForce：2026 年 LED 市場規模 121.76 億美元，動能來自 Micro／Mini LED、UV／IR、車用與農業照明", "region": "全球", "tags": ["市場"],
         "detail": "另預估 2026 年車用 LED 市場 34.51 億美元、車用照明 357.29 億美元；2025 年 LED 市場產值 130.03 億美元。2026 年初中國 LED 產業鏈全面漲價 3–15%。",
         "why": "提供 2026 年市場基準，其中車用與 Mini LED 背光是螢光粉（含 KSF）需求成長的主要來源。", "entities": ["TrendForce"], "confidence": "high",
         "src": "https://www.ledinside.com/intelligence/2026/3/2026_03_19_gold", "srcName": "LEDinside／TrendForce 2026-03-19"},
        {"date": "2026-03-06", "title": "Bridgelux 以 Thrive 全光譜、F90 與 RGBW 平台進軍軟性線型燈市場", "region": "美國", "tags": ["產品", "健康照明"],
         "detail": "軟燈條產品線涵蓋 1612、2025、2835、3838 封裝，CRI 最高 98（Thrive 系列 Rg > 101），光效最高 160 lm/W，強調從晶片、螢光粉到封裝的垂直整合，於 Light+Building 2026 展示。",
         "why": "美系 LED 廠以自有螢光粉配方的全光譜產品切入原本由中國廠主導的燈條市場。效能為公司宣稱。", "entities": ["Bridgelux"], "confidence": "medium",
         "src": "https://edisonreport.com/2026/03/06/bridgelux-expands-into-flexible-linear-light-market-with-new-thrive-f90-and-rgbw-led-platforms/", "srcName": "EdisonReport 2026-03-06"},
        {"date": "2026-02-24", "title": "第 14 屆 Phosphor Safari 在澳洲 Gosford 舉行；phys.org 報導因斯布魯克新綠粉", "region": "全球", "tags": ["論文"],
         "detail": "2009 年創辦的亞洲螢光粉年會 2026 年 2 月 24–26 日移師澳洲，共同主席為雪梨科技大學金大勇與 Jiajia Zhou；上一屆 2024 年在台北北科大舉行。同月 phys.org 報導因斯布魯克大學與 ams OSRAM 的 Li₉RESi₄N₄O₈:Ce³⁺ 綠粉。",
         "why": "螢光粉社群最重要的年度交流平台之一；2026 年 9 月 ICL 國際發光會議也回到京都。", "entities": ["Phosphor Safari"], "confidence": "high",
         "src": "https://phosphorsafari2026.com/", "srcName": "Phosphor Safari 2026 官網"},
        {"date": "2026-02-17", "title": "Edison Innovations 與富采續簽 KSF 螢光粉技術授權", "region": "台灣", "tags": ["專利授權", "KSF", "台灣"],
         "detail": "由 Dominion Harbor 執行長 David Pridham 與富采董事長范進雍共同宣布，續約涵蓋 KSF LED、Mini LED 與 Micro LED 製造；富采官網虛擬專利標示載明使用 K₂SiF₆:Mn⁴⁺ 技術。",
         "why": "台灣 LED 龍頭延續 KSF 授權，確認 KSF 仍是 Mini LED 背光與車用顯示紅光的主流方案。", "entities": ["Edison Innovations", "富采"], "confidence": "high",
         "src": "https://www.morningstar.com/news/accesswire/1137972msn/edison-innovations-renews-license-agreement-with-ennostar-corporation-for-ksf-technology", "srcName": "ACCESS Newswire（Morningstar 轉載）2026-02-17"},
        {"date": "2026-02-03", "title": "ams OSRAM 以 5.7 億歐元把非光學感測事業賣給 Infineon，Schwabmünchen 廠將關閉", "region": "歐洲", "tags": ["併購與重整", "市場"],
         "detail": "2025 年 4 月啟動的去槓桿計畫目標處分資產逾 5 億歐元：ENI 燈具事業以 1.14 億歐元售予 Ushio，感測事業售予 Infineon；「Simplify」計畫裁員約 2,000 人，Schwabmünchen 廠（約 270 人）最遲 2027 年底關閉。2024 年集團營收 34.3 億歐元（−5%）。",
         "why": "歐洲最大 LED 廠瘦身，螢光粉／轉換材料業務未見單獨處分，但研發資源勢必收縮。", "entities": ["ams OSRAM", "Infineon", "Ushio"], "confidence": "high",
         "src": "https://ams-osram.com/news/press-releases/sale-of-eni-2025", "srcName": "ams OSRAM 新聞稿"},
        {"date": "2026-01-30", "title": "Signify 宣布削減 1.8 億歐元成本、裁員 900 人並啟動策略檢討", "region": "歐洲", "tags": ["併購與重整", "市場"],
         "detail": "全球最大照明公司公布 2025 年營收 57.7 億歐元、低於預期後宣布成本削減方案，由 2025 年 9 月上任的執行長主導策略與產品組合檢討，股價當日重挫約 15%；2026 年第一季營收再減 12%。2024 年 LED 產品已占其銷售 93%。",
         "why": "反映歐美通用照明市場持續萎縮與美國關稅壓力，也影響對高階螢光粉 LED 的需求。", "entities": ["Signify"], "confidence": "high",
         "src": "https://nltimes.nl/2026/01/30/philips-lighting-spin-signify-cut-900-jobs-due-weak-2025-results-poor-outlook", "srcName": "NL Times 2026-01-30"},
        {"date": "2026-01-14", "title": "日亞啟動「無汞專案」，2030 年前以 LED 取代廠內所有汞燈", "region": "日本", "tags": ["產品", "法規與標準"],
         "detail": "以「永續製造」為概念，目標在 2030 年前把生產線上使用的所有汞燈（含紫外固化等製程光源）全部更換為 LED。",
         "why": "汞燈與傳統螢光燈同屬水俣公約淘汰對象，最大 LED 與螢光粉廠自身的去汞化具示範意義。", "entities": ["日亞化學"], "confidence": "high",
         "src": "https://www.nichia.co.jp/en/newsroom/2026/2026_011401.html", "srcName": "日亞新聞室 2026-01-14"},
        {"date": "2026-01-06", "title": "Samsung 於 CES 2026 發表 130 吋 Micro RGB 電視，產品線擴至 55–115 吋", "region": "韓國", "tags": ["顯示背光", "產品", "Micro LED"],
         "detail": "使用小於 100 µm 的紅綠藍 LED 獨立發光，經 VDE 驗證達 100% BT.2020 色域。R95H 65／75／85 吋定價 3,199.99／4,499.99／6,499.99 美元，55 吋入門約 1,600 美元；115 吋 MR95F（2025 年款）29,999.99 美元，130 吋尚未定價。",
         "why": "Samsung 以原生 RGB 背光取代量子點色轉換，是對量子點與 KSF 在高階電視地位的最大挑戰。", "entities": ["Samsung"], "confidence": "high",
         "src": "https://news.samsung.com/global/samsung-unveils-worlds-first-130-inch-micro-rgb-tv-featuring-next-generation-color-and-bold-new-design", "srcName": "Samsung Newsroom 2026-01"},
        {"date": "2026-01-05", "title": "TCL 於 CES 2026 推出 X11L「SQD-Mini LED」旗艦：超級量子點、20,000 分區、10,000 nits", "region": "中國", "tags": ["顯示背光", "量子點", "產品"],
         "detail": "以藍光 Mini LED 背光搭配改良的「超級量子點」紅綠轉換，宣稱 100% BT.2020 色域；75／85／98 吋定價 7,000／8,000／10,000 美元。TCL 把 SQD 而非 RGB Mini LED 定為 2026 年旗艦技術，改良量子點亦下放至 C8L、C7L、QM8L。",
         "why": "在 Hisense、Samsung 押注 RGB 背光的同時，TCL 選擇強化「藍光＋色轉換」路線，是量子點／螢光粉陣營在高階電視的重要背書。", "entities": ["TCL"], "confidence": "high",
         "src": "https://us.tcl.com/blogs/press-releases/tcl-unveils-x11l-series-sqd-mini-led-tv-at-ces-2026-delivering-ultimate-performance-with-an-all-new-level-of-accurate-color", "srcName": "TCL 北美新聞稿 2026-01-05"},
        {"date": "2026-01", "title": "Nature Communications：機器學習輔助的秒級快速燒結製得高亮度雷射螢光陶瓷", "region": "中國", "tags": ["論文", "雷射照明", "AI 材料"],
         "detail": "脈衝高溫快速燒結在 10 秒內製得同時緻密且晶粒細化的螢光陶瓷：LuAG:Ce 光轉換效率提高 31%、斷裂韌性提高 1.5 倍；LuAG:Ce–CaAlSiN₃:Eu 複合陶瓷量子效率大幅提升，藍光雷射激發下白光 CRI 達 93，並展示可見光通訊。Matter 2026 另報導準透明陶瓷實現公里級雷射白光通訊。",
         "why": "解決燒結時「緻密化必伴隨晶粒粗化」的長期矛盾，是雷射照明與 LiFi 用螢光陶瓷製程的突破。發表月份依卷期推估。", "entities": ["Nature Communications"], "confidence": "medium",
         "src": "https://www.nature.com/articles/s41467-026-74741-2", "srcName": "Nature Communications 2026"},
        # ---------------- 2025 ----------------
        {"date": "2025-12-25", "title": "中國最高人民法院撤銷 NIMS 紅粉專利部分無效裁定並發回重審", "region": "中國／日本", "tags": ["專利授權"],
         "detail": "針對江蘇博睿自 2019 年起提出的無效請求，最高人民法院撤銷 2020 年國家知識產權局的部分無效裁定，同時駁回博睿對其他請求項的主張；發回程序中博睿撤回請求，專利於 2026 年 4 月 2 日確定全部有效。",
         "why": "中國司法體系最終維持日本氮化物紅粉專利，是螢光粉專利史上少見的長期攻防。", "entities": ["NIMS", "江蘇博睿"], "confidence": "high",
         "src": "https://www.nims.go.jp/eng/press/2026/05/202605130.html", "srcName": "NIMS 新聞稿 2026-05-13"},
        {"date": "2025-11-24", "title": "美國能源部裁撤 EERE 獨立辦公室，固態照明計畫併入「關鍵礦物與能源創新辦公室」", "region": "美國", "tags": ["法規與標準", "市場"],
         "detail": "運作二十年的 SSL 計畫（含 CALiPER、DOE SSL 報告與對 DLC 的技術支援）移入 CMEI 的能源技術支柱，未列明照明優先度；FY2026 預算案原提議削減 EERE 約 74%，國會最終保留約 31 億美元。2024–2026 年未見新版《SSL R&D Opportunities》。",
         "why": "DOE SSL 計畫長期是螢光粉與下轉換材料研發目標的制定者，其邊緣化意味美國公部門對螢光粉研究的引導力減弱。", "entities": ["美國能源部"], "confidence": "high",
         "src": "https://www.energy.gov/cmei/articles/energy-department-announces-realignment-critical-minerals-and-energy-innovation", "srcName": "美國能源部 2025-11"},
        {"date": "2025-11-21", "title": "歐盟 RoHS 含鎘量子點顯示豁免 39(a) 到期，僅晶片上量子點豁免 39(b) 延至 2027 年底", "region": "歐洲", "tags": ["法規與標準", "量子點", "顯示背光"],
         "detail": "依授權指令 (EU) 2024/1416，附件 III 第 39(a) 項（顯示照明用 CdSe 下轉換量子點，< 0.2 µg Cd/mm²）到期；新增第 39(b) 項僅允許直接沉積於 LED 晶片上的含鎘量子點（< 5 µg Cd/mm²、每裝置最多 1 mg），效期至 2027 年 12 月 31 日。到期後顯示器須符合一般 0.01% 鎘限值。",
         "why": "終結含鎘量子點膜在歐洲電視的合法地位，將市場推向 InP 無鎘量子點、KSF 螢光粉與鈣鈦礦色轉換材料。", "entities": ["歐盟"], "confidence": "high",
         "src": "https://www.tuv.com/regulations-and-standards/en/europe-directive-eu-2024-1416-amending-annex-iii-to-eu-rohs-cadmium-in-downshifting-semiconductor.html", "srcName": "TÜV Rheinland（(EU) 2024/1416）"},
        {"date": "2025-11-07", "title": "中國宣布暫停 10 月 9 日稀土出口管制一年，至 2026 年 11 月 10 日；4 月的釔管制仍有效", "region": "中國／美國", "tags": ["稀土", "法規與標準"],
         "detail": "釜山川習會後，商務部第 70 號公告暫停第 55、56、57、58、61、62 號公告（含銪等五種稀土與域外 0.1% 規則），同時暫停 2024 年 12 月起對美的鎵、鍺、銻禁令至 2026 年 11 月 27 日；但 2025 年 4 月對釔等 7 類中重稀土的許可證管制從未暫停，CSIS 2026 年 4 月分析稱其「仍在咬人」。",
         "why": "暫緩只是延後而非撤銷，2026 年 11 月到期日是螢光粉供應鏈的下一個關鍵時點。", "entities": ["中國商務部"], "confidence": "high",
         "src": "https://www.pillsburylaw.com/en/news-and-insights/china-suspends-export-controls-certain-critical-minerals-related-items.html", "srcName": "Pillsbury Law 2025-11"},
        {"date": "2025-11-03", "title": "DLC 發布 SSL V6.0 與 LUNA V2.0：平均光效門檻提高 14%，2026 年起受理", "region": "美國", "tags": ["法規與標準"],
         "detail": "DesignLights Consortium 五年來首次重大更新固態照明技術要求，所有產品類別平均光效門檻提高 14%（部分達 19%），2026 年 1 月 5 日起受理申請，10 月 9 日為 V5.1 產品升級截止日，12 月 15 日後未升級者自 QPL 下架。",
         "why": "DLC 名單是北美節能補助的門檻，光效要求提高直接推升對高效率螢光粉與窄頻紅粉的需求。", "entities": ["DesignLights Consortium"], "confidence": "high",
         "src": "https://designlights.org/final-version-of-designlights-consortiums-new-technical-requirements-for-led-lighting-released/", "srcName": "DLC 2025-11-03"},
        {"date": "2025-11", "title": "因斯布魯克大學與 ams OSRAM 發表全新結構綠色螢光粉 Li₉RESi₄N₄O₈:Ce³⁺，效能可與商用石榴石相比", "region": "歐洲", "tags": ["論文", "產品"],
         "detail": "Huppertz 團隊與 ams OSRAM（Schwabmünchen）及杜塞道夫大學合作，在 Advanced Functional Materials 第 35 卷第 44 期（封面文章）報導鋰稀土氧氮矽酸鹽（RE = Y、La、Gd、Dy、Yb、Lu），Ce³⁺ 激活發出高效綠光（Y：544 nm；Gd：536 nm），合成溫度低於石榴石，並已製作原型 LED 驗證。",
         "why": "數十年來 LuAG:Ce／YAG:Ce 石榴石幾乎壟斷綠黃色螢光粉，這是少見的「全新基質結構」且有產業夥伴背書的成果。發表月份依卷期推估。", "entities": ["因斯布魯克大學", "ams OSRAM"], "confidence": "high",
         "src": "https://www.uibk.ac.at/en/newsroom/2025/green-light-from-new-sources/", "srcName": "因斯布魯克大學新聞室 2025"},
        {"date": "2025-11", "title": "釔價暴漲：歐洲氧化釔一年內漲約 4,400% 至每公斤約 270 美元，中國境內僅約 7 美元", "region": "全球", "tags": ["稀土", "市場"],
         "detail": "2025 年 4 月中國對釔實施出口許可後，歐洲氧化釔自年初約 6 美元/公斤飆升至 220–320 美元/公斤（Argus），中國對美直接出貨幾近停止（CSIS：4–12 月僅 17 噸，管制前 8 個月 333 噸）；DIGITIMES 2026 年 4 月稱境外漲幅達 140 倍。不同來源的倍數（1,500%、3,500%、4,400%）取決於基期與地區。",
         "why": "YAG:Ce 黃粉是白光 LED 的基礎材料，釔價暴漲直接推高中國以外螢光粉與 LED 封裝成本，並促使南非等非中國釔供應加速開發。", "entities": ["Argus", "CSIS"], "confidence": "medium",
         "src": "https://www.asiafinancial.com/yttrium-is-latest-rare-earth-concern-as-global-supplies-fall", "srcName": "Asia Financial（引 Argus）"},
        {"date": "2025-10-21", "title": "Lumileds 推出最薄的單晶片可定址車用前照 LED LUXEON Altilon SMD-A", "region": "美國", "tags": ["產品", "車用"],
         "detail": "發光區之間的間隙縮到 70 µm，並優化晶片與螢光片尺寸比以提高亮度，已設計進 2026 年式車款；2024 年其 NightScape 與 LUXEON 3D 曾獲 LEDs Magazine BrightStar 獎。",
         "why": "畫素化頭燈把螢光片的幾何精度推到新高，是 Lumiramic 陶瓷螢光片路線的延伸。", "entities": ["Lumileds"], "confidence": "high",
         "src": "https://lumileds.com/new-luxeon-altilon-smd-a-the-thinnest-single-chip-addressable-package-for-high-performance-automotive-forward-lighting/", "srcName": "Lumileds 新聞稿 2025-10-21"},
        {"date": "2025-10-09", "title": "中國擴大稀土出口管制：新增銪、鈥、鉺、銩、鐿並管制境外含中國稀土產品（原定 11 月 8 日生效）", "region": "中國", "tags": ["稀土", "法規與標準"],
         "detail": "商務部第 55–58、61、62 號公告把五種稀土納入管制（17 種中 12 種受控），並首度對境外使用中國稀土材料或技術製造、含中國原產稀土價值 0.1% 以上的物項實施域外管制（原定 12 月 1 日生效）。銪是大多數紅色螢光粉與 LED 螢光粉的活化劑。",
         "why": "若全面實施，將是全球螢光粉產業自 2010 年以來最嚴重的原料風險；隨後在美中協議下暫緩。", "entities": ["中國商務部"], "confidence": "high",
         "src": "https://cset.georgetown.edu/publication/mofcom-notice-2025-61/", "srcName": "CSET（第 61 號公告譯本）"},
        {"date": "2025-10-05", "title": "中國國家標準 GB/T 30075-2025《LED 用稀土氮化物紅色螢光粉》發布，2026 年 5 月 1 日實施", "region": "中國", "tags": ["法規與標準"],
         "detail": "全面取代 2013 年版，由全國稀土標準化技術委員會歸口，主要起草單位包括有研稀土、江蘇博睿光電與江門科恆。",
         "why": "CASN／SCASN 氮化物紅粉是高顯色白光 LED 的核心材料，中國更新國家標準顯示其本土供應鏈已成熟並意圖主導規格。", "entities": ["有研稀土", "江蘇博睿"], "confidence": "high",
         "src": "https://std.samr.gov.cn/gb/search/gbDetailed?id=40B74A27FC60BD79E06397BE0A0AB048", "srcName": "全國標準資訊公共服務平台"},
        {"date": "2025-10", "title": "臺大劉如熹團隊近紅外螢光粉綜述登上 Progress in Materials Science", "region": "台灣", "tags": ["論文", "近紅外", "台灣"],
         "detail": "〈Revolutionary near-infrared phosphors with emerging structures and mechanisms〉涵蓋 NIR-I（650–950 nm）、NIR-II（1000–1350 nm）、NIR-III（1500–1850 nm）三個生物視窗，以 Cr³⁺ 為主要活化劑並整理位點工程與能量轉移機制；ScienceDirect 標示為 2026 年卷 157、文章號 101588。",
         "why": "台灣團隊在近紅外螢光粉領域的系統性整理，與 2022 年 Chemical Reviews 綜述並列入門文獻。", "entities": ["劉如熹", "臺灣大學"], "confidence": "high",
         "src": "https://www.ntu.edu.tw/spotlight/2025/2421_20251029.html", "srcName": "臺大焦點新聞 2025-10-29"},
        {"date": "2025-09-05", "title": "日亞於 ISAL 2025 推出 µPLS Mini 與採板上螢光粉的 DominoPLS 車用光源", "region": "日本", "tags": ["產品", "車用"],
         "detail": "µPLS Mini 以數位驅動只點亮使用中的 LED，市區行駛閒置功耗減半；DominoPLS 以較大晶粒搭配板上螢光粉（on-board phosphor）減少光損失。同月 Garmin fenix 8 Pro 搭載友達供應的 1.39 吋 Micro LED 面板上市。",
         "why": "板上螢光粉架構在自適應頭燈成為主流設計，說明螢光粉塗佈製程仍是車用 LED 效率的關鍵。", "entities": ["日亞化學"], "confidence": "high",
         "src": "https://www.semiconductor-today.com/news_items/2025/sep/nichia-050925.shtml", "srcName": "Semiconductor Today 2025-09-05"},
        {"date": "2025-08-01", "title": "三安光電與 Inari 宣布以 2.39 億美元企業價值聯合收購 Lumileds", "region": "中國／美國", "tags": ["併購與重整", "市場"],
         "detail": "透過香港特殊目的公司（三安 74.5%、Inari 25.5%）收購 Lumileds 100% 股權，另注資 4,100 萬美元營運資金，總投資 2.8 億美元，預計 2026 年第一季完成。Lumileds 2022 年走出破產重整、2024 年賣掉車燈事業。",
         "why": "售價之低（2016 年估值 33 億美元）反映西方 LED 廠的困境；交易最終於 2026 年 4 月被 CFIUS 封殺。", "entities": ["Lumileds", "三安光電", "Inari"], "confidence": "high",
         "src": "https://lumileds.com/sanan-and-inari-to-acquire-100-of-lumileds-holding-b-v-s-shares/", "srcName": "Lumileds 新聞稿 2025-08-01"},
        {"date": "2025-07", "title": "Hisense 116UX 上市：首款量產 RGB Mini LED 電視，售價 29,999 美元", "region": "中國", "tags": ["顯示背光", "產品"],
         "detail": "116 吋 116UX 與 100 吋 100UX 以獨立紅綠藍 Mini LED 取代藍光 LED＋量子點／螢光粉，色域達 BT.2020 的 95%、峰值亮度 8,000 nits，7 月底至 8 月出貨。Hisense 2025 年雷射電視全球市占 70.3%。",
         "why": "RGB 背光是對「藍光＋色轉換材料」架構的直接替代，若成本下降將壓縮 KSF 與量子點膜在高階電視的市場。「首款」為公司說法。", "entities": ["Hisense"], "confidence": "high",
         "src": "https://www.prnewswire.com/news-releases/hisense-debuts-116-ux-tv-with-rgb-miniled-for-stunning-color-precision-302498550.html", "srcName": "PR Newswire 2025-07"},
        {"date": "2025-06-24", "title": "廣州光亞展：億光展出解決 KSF 吸濕問題的包覆技術", "region": "台灣／中國", "tags": ["產品", "KSF", "台灣"],
         "detail": "TrendForce 回顧第 30 屆廣州國際照明展指出，億光以特殊包覆技術與高精度離心沉降解決 KSF 對濕氣敏感的核心問題，達成高色彩穩定性、低色偏與高光效。",
         "why": "KSF 的吸濕劣化是其在照明領域普及的最大障礙，台灣封裝廠的包覆技術是實用化關鍵。", "entities": ["億光"], "confidence": "high",
         "src": "https://www.trendforce.com/news/2025/06/24/insight-led-lighting-manufacturers-unveiled-innovations-at-the-30th-guangzhou-international-lighting-exhibition-gile-2025/", "srcName": "TrendForce 2025-06-24"},
        {"date": "2025-06", "title": "Lynas 在馬來西亞產出首批氧化鋱（5 月首批氧化鏑），成中國以外唯一重稀土分離商", "region": "全球", "tags": ["稀土", "市場"],
         "detail": "關丹廠重稀土分離迴路 2025 年第一季完工，設計每年處理 1,500 噸含釤、銪、釓、鈥、鏑、鋱的混合重稀土化合物；「Towards 2030」策略計畫再回收至少五種重稀土（含釔）。尚未量產分離釔與銪。",
         "why": "鋱是綠色螢光粉與閃爍體的關鍵元素，這是中國以外重稀土供應鏈重建的第一步。", "entities": ["Lynas"], "confidence": "high",
         "src": "https://www.miningweekly.com/article/lynas-adds-terbium-oxide-to-heavy-rare-earths-portfolio-2025-06-18", "srcName": "Mining Weekly 2025-06-18"},
        {"date": "2025-06", "title": "Ca₂YHf₂Ga₃O₁₂:Cr³⁺ 近紅外螢光粉：發射峰 794 nm、半高寬 189 nm、內量子效率 82%", "region": "中國", "tags": ["論文", "近紅外"],
         "detail": "新型石榴石結構近紅外螢光粉內／外部量子效率 82%／22%，鎖定夜視、無損檢測與防偽；9 月另有 Lu₃Ga₅O₁₂:Cr³⁺ 內量子效率 89.5% 用於植物生長節律調控的報導。",
         "why": "Cr³⁺ 近紅外螢光粉是 2024–2026 年論文數量成長最快的子領域，中國團隊居主導地位。轉載媒體未註明期刊。", "entities": ["生物通"], "confidence": "low",
         "src": "https://www.ebiotrade.com/newsf/2025-6/20250628000424596.htm", "srcName": "生物通 2025-06（轉載）"},
        {"date": "2025-05-29", "title": "錼創展示量子點色轉換全彩 Micro LED 搭配 Lumus 波導的微型投影", "region": "台灣", "tags": ["Micro LED", "量子點", "台灣"],
         "detail": "在 Display Week 2025，PlayNitride 展示以藍光 Micro LED 為基礎、以量子點將藍光轉為紅與綠的單晶片全彩 Micro LED，搭配幾何波導做成極小的 AR 投影機；同時展示 6 吋 Micro LED 磊晶片的均勻度。",
         "why": "台灣 Micro LED 領導廠選擇量子點色轉換路線，與 Samsung 原生 RGB Micro RGB 形成對照。來源為獨立分析師部落格。", "entities": ["錼創", "Lumus"], "confidence": "medium",
         "src": "https://kguttag.com/2025/05/29/exclusive-playnitride-single-chip-full-color-microled-lumus-waveguide-with-a-fantasically-tiny-projector/", "srcName": "KGOnTech 2025-05-29"},
        {"date": "2025-05-07", "title": "SID 2025 榮譽獎：TCL 華星閆曉林獲 Braun 獎（含 QD-EL 材料），Samsung Display EL-QD 獲傑出論文獎", "region": "全球", "tags": ["獎項", "量子點"],
         "detail": "閆曉林獲 Karl Ferdinand Braun 獎，表彰其在 Mini LED、噴墨 OLED 量產與 QLED 材料的貢獻；安達千波矢獲 Jan Rajchman 獎；Samsung Display 無偏光片 OLED 獲年度顯示器獎。Nanosys／昭榮同月表示無鎘量子點 521–640 nm 全波段可量產並取得首家大型車廠設計案。",
         "why": "反映顯示產業對量子點與新型發光材料研究的肯定，是 2025 年最具指標性的產業獎項。", "entities": ["SID", "TCL 華星", "Samsung Display"], "confidence": "high",
         "src": "https://sid.onlinelibrary.wiley.com/doi/full/10.1002/msid.1560", "srcName": "Information Display（SID）2025"},
        {"date": "2025-05", "title": "Seaborough 與 Luminus 合作將奈米工程 Eu³⁺ 螢光粉 EuroLED 商業化", "region": "歐洲／美國", "tags": ["產品", "論文"],
         "detail": "荷蘭 Seaborough 與美國 Luminus Devices 宣布合作，目標推出首款採用奈米工程 Eu³⁺ 螢光粉的 LED；公司宣稱在 CRI 80–90 範圍可比現有螢光粉多提供 10–20% 的流明／瓦。Seaborough 先前已與 Current Chemicals 合作工業化。",
         "why": "Eu³⁺ 線狀紅光的光譜效率極高但過去難以用藍光激發，若成功商業化將是暖白光 LED 效率的一大躍進。截至 2026 年 9 月未見量產公告。", "entities": ["Seaborough", "Luminus"], "confidence": "medium",
         "src": "https://www.seaborough.com/news/seaborough-and-luminus-devices-announce-partnership-to-bring-the-worlds-first-leds-with-nano-engineered-eu3-based-phosphor-to-market/", "srcName": "Seaborough 新聞稿 2025-05"},
        {"date": "2025-04-24", "title": "歐洲統一專利法院判 Laser Components 侵害首爾半導體 Micro LED 專利，須回收產品", "region": "歐洲／韓國", "tags": ["專利授權", "Micro LED"],
         "detail": "UPC 裁定在法、德、荷銷售的產品侵害 Seoul Viosys 的歐洲專利 EP 3 404 726，發出永久禁制令並命令回收，另判賠約 25 萬歐元；這是首爾半導體在 UPC 的第二次勝訴（首次為 2024 年 10 月，禁售令涵蓋 8 國）。",
         "why": "LED 專利在 18 個 UPC 成員國的一體執法，強化韓日大廠對中國 LED 出口的壓力。", "entities": ["首爾半導體", "UPC"], "confidence": "high",
         "src": "https://inside.lighting/news/25-04/european-court-orders-recall-infringing-led-products", "srcName": "Inside Lighting 2025-04"},
        {"date": "2025-04-22", "title": "ams OSRAM 推出 OSCONIQ S 3030 與 DURIS E 2835 高光效中功率 LED", "region": "歐洲", "tags": ["產品"],
         "detail": "OSCONIQ S 3030（CRI 80／90）採藍寶石覆晶與特殊螢光粉技術，DURIS E 2835 為其 2835 平台中光效最高者。",
         "why": "顯示歐洲大廠在中功率主流封裝仍以自有螢光粉配方追求光效與演色性並進。", "entities": ["ams OSRAM"], "confidence": "high",
         "src": "https://ams-osram.com/news/media-updates/ultra-efficient-leds-perfect-for-high-performance-indoor-lighting-applications", "srcName": "ams OSRAM 媒體更新 2025-04-22"},
        {"date": "2025-04-08", "title": "Solvay 拉羅歇爾廠啟動磁材用稀土生產，目標 2030 年供應歐洲 30% 需求", "region": "歐洲", "tags": ["稀土", "市場"],
         "detail": "中國以外最大、能分離全部稀土元素的工廠啟用釹、鐠分離產線；鏑與鋱的工業規模分離目標為 2026 年 9 月。Solvay 曾於 2012 年建立螢光燈螢光粉稀土回收線，2016 年初因稀土價格崩跌停止。",
         "why": "歐洲重建稀土分離能力的關鍵一步，但螢光粉最需要的釔與銪尚不在其近期產品線。", "entities": ["Solvay"], "confidence": "high",
         "src": "https://www.solvay.com/en/press-release/solvay-advances-european-rare-earths-production-through-capacity-expansion", "srcName": "Solvay 新聞稿 2025-04"},
        {"date": "2025-04-04", "title": "中國商務部第 18 號公告：對釤、釓、鋱、鏑、鎦、鈧、釔等 7 類中重稀土實施出口管制", "region": "中國", "tags": ["稀土", "法規與標準"],
         "detail": "即日起對 7 類中重稀土及其氧化物、合金、化合物與混合物實施出口許可管理，是對美國關稅的反制；實施後兩個月內稀土磁材出口約減四分之三。釔是 YAG:Ce 黃粉的主要基質元素，鋱、釓則用於三基色螢光粉與閃爍體。此公告至今未暫停。",
         "why": "這是自 2010 年以來對螢光粉供應鏈衝擊最大的政策，直接引發 2025 年釔價暴漲。", "entities": ["中國商務部"], "confidence": "high",
         "src": "https://www.mofcom.gov.cn/zwgk/zcfb/art/2025/art_9c2108ccaf754f22a34abab2fedaa944.html", "srcName": "中國商務部 2025 年第 18 號公告"},
        {"date": "2025-04", "title": "美國關稅：LED 元件不在中國進口豁免清單內，綜合稅率普遍達 30–35%", "region": "美國", "tags": ["法規與標準", "市場"],
         "detail": "2025 年 2 月起美國對中國商品加徵的關稅由 10% 提高至 20%，加上既有 Section 301 的 25%，LED 照明產品綜合稅率普遍 30–35%。",
         "why": "推升美國市場 LED 封裝與螢光粉供應鏈向越南、墨西哥、泰國轉移，也是 Signify、Lumileds 等營運壓力的來源之一。具體稅率因 HS 編碼而異。", "entities": ["Inside Lighting"], "confidence": "medium",
         "src": "https://inside.lighting/news/25-04/no-leds-are-not-exempt-china-tariffs", "srcName": "Inside Lighting 2025-04"},
        {"date": "2025-03-28", "title": "BOE HC Semi 宣稱全球首條 6 吋 Micro LED 量產線正式出貨", "region": "中國", "tags": ["Micro LED", "產品"],
         "detail": "京東方旗下 Micro LED 工廠宣布正式交付產品，整合晶片與封裝模組產線，強調巨量轉移與設備國產化。",
         "why": "Micro LED 走向量產，色轉換（量子點／螢光粉）與原生 RGB 路線的商業競逐進入實戰階段。「全球首條」為公司說法。", "entities": ["BOE"], "confidence": "medium",
         "src": "https://www.ledinside.com/news/2025/3/2025_03_28_02", "srcName": "LEDinside 2025-03-28"},
        {"date": "2025-02-26", "title": "首爾半導體以 SunLike 自然光技術提出「照明新典範」；2025 年財報連續第五年營業虧損", "region": "韓國", "tags": ["產品", "健康照明", "市場"],
         "detail": "SunLike 以紫光晶片激發 TRI-R 三色螢光粉模擬太陽光譜（CRI 97、Rf 96–97），在 JAPAN SHOP、LightFair 與 Future Lighting 2025 展出；5 月 UC Davis 加州照明技術中心以 50 位受試者研究指出低亮度下仍維持視覺滿意度。公司 2025 年營收 1 兆 135 億韓元、營業損失 315 億韓元。",
         "why": "SunLike 是「人因照明」路線中最積極的商業推廣案例；健康效益為公司宣稱，引述的臨床研究未逐一查證。", "entities": ["首爾半導體"], "confidence": "medium",
         "src": "https://www.businesswire.com/news/home/20250226897387/en/Seoul-Semiconductor-Presents-a-New-Paradigm-in-Lighting-with-Natural-Light-Technology", "srcName": "Business Wire 2025-02-26"},
        {"date": "2025-02-21", "title": "富采宣布晶元光電與隆達電子合併為富采光電", "region": "台灣", "tags": ["併購與重整", "台灣"],
         "detail": "合併基準日原訂 2025 年 10 月 1 日，後延至 2026 年 1 月 1 日，成為整合面板、LED 晶片與封裝的業者，聚焦車用、先進顯示、智慧感測與 AI 光通訊。",
         "why": "台灣 LED 上下游整合的關鍵一步，隆達原有的螢光粉封裝與背光模組能力併入單一公司。", "entities": ["富采", "晶電", "隆達"], "confidence": "high",
         "src": "https://www.ledinside.com.tw/news/20250224-39791.html", "srcName": "LEDinside 台灣 2025-02-24"},
        {"date": "2025-02-19", "title": "Edison Innovations（Dominion Harbor）自 Dolby 收購 2,500 件 GE 專利，取得 KSF 螢光粉專利組合", "region": "美國", "tags": ["併購與重整", "專利授權", "KSF"],
         "detail": "所購專利均為 Dolby 2024 年收購 GE Licensing 時取得，其中包含 GE 原有及 GE 向首爾半導體購入的 PFS／KSF 專利，Edison 稱其為顯示產業最大的 KSF 專利組合。",
         "why": "自此 KSF 專利由專利授權公司持有，2026 年展開對台、中、韓、美 LED 廠的大規模授權與續約。", "entities": ["Edison Innovations", "Dolby"], "confidence": "high",
         "src": "https://www.accessnewswire.com/newsroom/en/business-and-professional-services/edison-innovations-llc-a-dominion-harbor-company-acquires-diverse-988115", "srcName": "ACCESS Newswire 2025-02-19"},
        {"date": "2025-02", "title": "Advanced Science 報導超窄帶紅色螢光粉 Nb₂O₅:Pr³⁺（半高寬 19 nm）", "region": "中國", "tags": ["論文", "顯示背光"],
         "detail": "透過氧空位工程設計出半高寬僅 19 nm 的超窄帶紅粉，可與 CsPbI₃ 量子點相比且化學穩定；以 420 nm 晶片搭配 β-SiAlON:Eu²⁺ 綠粉製成的暖白光 LED 達 CRI 92.3。同月 Cree LED 推出電光轉換效率 83.5% 的園藝用 XP-L Photo Red 直接發光紅光 LED。",
         "why": "無銪、無鎘的超窄帶紅粉若能提高量子效率，將是 KSF 之外的廣色域候選。", "entities": ["Advanced Science"], "confidence": "medium",
         "src": "https://advanced.onlinelibrary.wiley.com/doi/full/10.1002/advs.202416761", "srcName": "Advanced Science 2025"},
        {"date": "2025-01-29", "title": "日亞量產 280 nm UVC LED NCSU434D，電光效率 7.4% 為業界最高", "region": "日本", "tags": ["產品"],
         "detail": "350 mA 時輻射通量 135 mW、最大電流 700 mA 時 263 mW；路線圖 2021 年 3.1%、2022 年 5.4%。AlGaN UVC LED 是「直接發 UVC」路線，不用螢光粉。",
         "why": "對照 Pr³⁺、Bi³⁺ 紫外螢光粉仍在研究階段，說明消毒用紫外光源的商用路線是晶片直接發光。", "entities": ["日亞化學"], "confidence": "high",
         "src": "https://www.nichia.co.jp/en/newsroom/2025/2025_012901.html", "srcName": "日亞新聞稿 2025-01-29"},
        {"date": "2025-01-23", "title": "日亞推出以綠光晶片取代綠色螢光粉的 LCD 背光白光 LED NS2W806H-B2", "region": "日本", "tags": ["產品", "顯示背光"],
         "detail": "單一封裝內同時放入藍光與新開發的綠光晶片，產生尖銳且窄的綠光光譜，與彩色濾光片高度匹配，提高 LCD 模組效率並擴大綠與紅的色彩再現範圍。",
         "why": "在高階背光領域，「晶片直接發光」開始侵蝕綠色螢光粉的角色，對 β-SiAlON 等綠粉市場是重要訊號。", "entities": ["日亞化學"], "confidence": "high",
         "src": "https://www.nichia.co.jp/en/newsroom/2025/2025_012301.html", "srcName": "日亞新聞室 2025-01-23"},
        {"date": "2025-01", "title": "日亞推出 GigaWhite 白光雷射 SMD：藍光雷射＋螢光粉，亮度約 LED 的 10 倍", "region": "日本", "tags": ["產品", "雷射照明", "車用"],
         "detail": "內建感測器可電性偵測螢光粉破裂或脫落以防雷射外洩，目標為車用頭燈、特殊與工業照明；日亞預估可實現透鏡直徑小於 10 mm 的超薄頭燈並符合 ECE R112 Class-B。",
         "why": "白光雷射照明從 Kyocera SLD Laser、OSRAM 走向日亞加入，代表螢光粉在高功率密度雷射激發下的可靠度已達車規水準。精確發布日未確認。", "entities": ["日亞化學"], "confidence": "high",
         "src": "https://www.lightnowblog.com/2025/01/nichia-releases-gigawhite-white-laser-smd/", "srcName": "LightNOW 2025-01"},
        {"date": "2025", "title": "Laser & Photonics Reviews：雙螢光粉陶瓷實現 782.5 lm/mm² 暖白光雷射照明", "region": "中國", "tags": ["論文", "雷射照明"],
         "detail": "以放電電漿燒結製備 Ca-α-SiAlON:Eu（橙）與 YAG:Ce（黃）雙螢光粉陶瓷，發射峰可在 541–601 nm 調整，外部量子效率約 42%，熱導率 > 17.6 W/(m·K)，飽和閾值 18.8 W/mm²，色溫 2278 K；2026 年同刊另報導 CALSON:Ce 陶瓷 EQE 57%、飽和閾值 19.58 W/mm²。同年 Nature Communications 報導快速燒結螢光粉玻璃薄膜用於雷射光源。",
         "why": "解決雷射照明長期缺乏暖白光陶瓷螢光體的問題，是車用與投影雷射光源的材料突破。作者機構未在摘要中確認。", "entities": ["Laser & Photonics Reviews"], "confidence": "medium",
         "src": "https://onlinelibrary.wiley.com/doi/abs/10.1002/lpor.202402144", "srcName": "Laser & Photonics Reviews 2025"},
        {"date": "2025", "title": "Light: Science & Applications：Rb₃Y(PO₄)₂:Eu²⁺ 在高摻雜濃度下仍保持高量子效率", "region": "全球", "tags": ["論文", "稀土"],
         "detail": "Glaserite 型結構讓活化劑彼此保持距離，在 0.8 mol% 與 70 mol% 兩種 Eu 含量下都維持高內部量子產率，可組合成暖白光 LED。同年 Nature Electronics 觀點文章論述鈣鈦礦作為色轉換材料的優勢（半高寬 ≤ 20 nm、高吸收），Nature Communications 報導自組裝奈米光子閃爍體使 X 光成像光產率提高 6 倍。",
         "why": "提出「以結構抑制濃度猝滅」的新設計原則，對降低稀土用量與提高紅光成分具參考價值。", "entities": ["Light: Science & Applications"], "confidence": "medium",
         "src": "https://www.nature.com/articles/s41377-025-01760-x", "srcName": "Light: Science & Applications 2025"},
        {"date": "2025", "title": "廈門大學以機器學習發現窄帶綠光 CsRbKNa(Li₃SiO₄)₄:Eu²⁺；上海矽酸鹽所建構螢光粉 AI 代理人", "region": "中國", "tags": ["論文", "AI 材料", "顯示背光"],
         "detail": "解榮軍團隊建立可預測 UCr₄C₄ 型 Eu²⁺ 矽酸鹽發光波長與半高寬的模型，找到發光峰 530 nm、半高寬 44 nm、內／外量子效率 82.8%／52.9%、425 K 保持 97% 的綠粉（Chemical Engineering Journal）；11 月中科院上海矽酸鹽所在 PCCP 發表自 5,400 篇以上文獻建成知識庫、以檢索增強生成預測發光波長（誤差約 10–20 nm）的 AI 代理人。",
         "why": "資料驅動方法在 2025 年同時產出可用於背光的窄帶綠粉與文獻級 AI 工具，是「AI 找螢光粉」從概念走向實務的一年。", "entities": ["廈門大學", "中科院上海矽酸鹽所"], "confidence": "high",
         "src": "https://www.sciencedirect.com/science/article/abs/pii/S138589472506557X", "srcName": "Chemical Engineering Journal 2025"},
        # ---------------- 2024 ----------------
        {"date": "2024-12", "title": "ANSI C78.377-2024 發布，新增 1800K 與 2000K 標準色度", "region": "美國", "tags": ["法規與標準"],
         "detail": "《固態照明產品色度規範》修訂版新增 2000K 與 1800K 名義相關色溫，以因應取代高壓鈉燈的戶外與特殊照明需求。同年 ANSI/IES TM-30-24 色彩還原評估方法更新版出版。",
         "why": "為超低色溫（琥珀色）LED 建立統一色度標準，這類產品高度依賴橙紅色螢光粉配方，也與生態友善照明趨勢相關。發布月份依報導推估。", "entities": ["ANSI", "IES"], "confidence": "medium",
         "src": "https://www.lightnowblog.com/2025/01/2-new-ccts-published-in-ansi-c78-377-2024/", "srcName": "LightNOW 2025-01"},
        {"date": "2024-11-25", "title": "東芝同意以 1,500 億日圓把東芝材料（TRI-R 螢光粉）賣給 Niterra，2025 年更名 Niterra Materials", "region": "日本", "tags": ["併購與重整"],
         "detail": "東芝材料生產螢光粉與氮化矽陶瓷球等，目標 2025 年 5 月 30 日完成交割；Niterra（前 NGK Spark Plug）隨後宣布完成收購並更名。TRI-R 三色螢光粉是首爾半導體 SunLike 的核心。",
         "why": "日本螢光粉重要供應商易主，由火星塞大廠接手作為事業多角化的一環。", "entities": ["東芝材料", "Niterra"], "confidence": "high",
         "src": "https://www.niterragroup.com/english/news/detail/003026.html", "srcName": "Niterra 新聞稿"},
        {"date": "2024-10-30", "title": "ams OSRAM 推出戶外與體育場照明用 OSCONIQ C 3030；10 月 Lumileds LUXEON 5050 HE Plus 達 199 lm/W", "region": "歐洲／美國", "tags": ["產品"],
         "detail": "OSCONIQ C 3030 採 UX:3 晶片與自有螢光粉轉換技術，驅動電流最高 3 A、功率 9 W；Lumileds 宣稱 LUXEON 5050 HE Plus 光效 199 lm/W、746 lm，可讓戶外照明系統耗電降低 18% 以上。",
         "why": "接近 200 lm/W 的商用封裝光效，顯示螢光粉轉換效率與晶片效率仍在推進；體現大廠把自有螢光粉配方視為差異化核心。數字為公司宣稱。", "entities": ["ams OSRAM", "Lumileds"], "confidence": "medium",
         "src": "https://www.ledinside.com/products/2024/10/2024_10_30_01", "srcName": "LEDinside 2024-10-30"},
        {"date": "2024-10", "title": "Samsung Electronics 決定分階段退出 LED 事業，最晚 2030 年結束車用 LED", "region": "韓國", "tags": ["併購與重整", "市場"],
         "detail": "DS 部門解散 LED 事業部，人力轉往記憶體、晶圓代工、功率半導體與 Micro LED；照明用 LED 晶片 2026 年上半年停產，電視背光 LED 2026 年底結束，車用 LED 2030 年結束。同月首爾半導體在歐洲統一專利法院首度勝訴，禁售令涵蓋 8 國。",
         "why": "三星 2012 年併入 Samsung LED 後因中國低價競爭難以獲利；LM301 系列（覆晶＋螢光粉塗佈）曾是中功率光效與園藝照明的標竿。", "entities": ["Samsung"], "confidence": "high",
         "src": "https://www.lightnowblog.com/2024/10/samsung-to-gradually-exit-led-business-by-2030/", "srcName": "LightNOW 2024-10"},
        {"date": "2024-09", "title": "歐盟生態設計法規 (EU) 2019/2020 第二階段：LED 光源頻閃可見度 SVM ≤ 0.4 自 2024 年 9 月適用", "region": "歐洲", "tags": ["法規與標準"],
         "detail": "自 2021 年 9 月起要求 Pst LM ≤ 1.0 與 SVM ≤ 0.9，2024 年 9 月起 SVM 收緊至 0.4，並持續適用最低光效、流明維持率與 EPREL 登錄。YAG 類螢光粉衰減僅奈秒級，無法「濾掉」驅動器造成的閃爍；毫秒級的 KSF 則略能平滑。",
         "why": "歐盟對 LED 光源的品質要求持續提高，間接推升對高效率螢光粉與驅動設計的需求。", "entities": ["歐盟"], "confidence": "high",
         "src": "https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX%3A32019R2020", "srcName": "EUR-Lex (EU) 2019/2020"},
        {"date": "2024-08-07", "title": "Lumileds 推出無透鏡高功率 LED LUXEON HL4Z，2.16 mm² 發光面輸出逾 1,400 lm", "region": "美國", "tags": ["產品"],
         "detail": "在 3.5 A、85 °C 下由 2.16 mm × 2.16 mm 發光面輸出超過 1,400 lm，鎖定需要極高光強度的應用；同月 Dolby 完成收購 GE Licensing（含 KSF 專利）。",
         "why": "高光通量密度封裝對螢光粉的熱穩定性與光飽和要求極高，是評估螢光粉材料上限的指標性產品。", "entities": ["Lumileds"], "confidence": "high",
         "src": "https://www.semiconductor-today.com/news_items/2024/aug/lumileds-070824.shtml", "srcName": "Semiconductor Today 2024-08"},
        {"date": "2024-07-30", "title": "第 13 屆 Phosphor Safari 在國立臺北科技大學舉行，主席林群哲", "region": "台灣", "tags": ["論文", "台灣"],
         "detail": "2009 年創辦的亞洲螢光粉年會 2024 年 7 月 30 日至 8 月 2 日在台北舉行，會後由 ACS Applied Optical Materials 出版專刊。同月 BMW 與 Audi 表明不再發展雷射頭燈（美國 FMVSS 108 的 150,000 cd 上限使雷射遠光優勢消失）。",
         "why": "台灣首次主辦這個年會（2012 年新竹場除外），反映台灣在螢光粉學術社群的能見度。", "entities": ["Phosphor Safari", "北科大", "林群哲"], "confidence": "high",
         "src": "https://phosphorsafari2026.com/", "srcName": "Phosphor Safari 官網（歷屆）"},
        {"date": "2024-06-06", "title": "Dolby 宣布以 4.29 億美元收購 GE Licensing（含 KSF 螢光粉專利）", "region": "美國", "tags": ["併購與重整", "專利授權", "KSF"],
         "detail": "交易於 2024 年 8 月 19 日完成，涵蓋逾 5,000 件專利，其中包括 GE 原有的 PFS／KSF 窄帶紅色螢光粉專利組合；GE Aerospace 保留航太國防專利與 GE 商標。",
         "why": "KSF 是全球 LCD 背光與高顯色 LED 最重要的窄帶紅粉專利之一，這筆交易開啟 2025 年 KSF 專利再度轉手給 Edison Innovations 的連鎖事件。", "entities": ["Dolby", "GE Aerospace"], "confidence": "high",
         "src": "https://news.dolby.com/en-WW/238205-dolby-laboratories-announces-agreement-to-acquire-ge-licensing-from-ge-aerospace/", "srcName": "Dolby 新聞室 2024-06-06"},
        {"date": "2024-04-19", "title": "友達整合富采與錼創建立 Micro LED 生態系，龍潭 6 吋線 2,150 萬美元", "region": "台灣", "tags": ["Micro LED", "台灣", "市場"],
         "detail": "分工上富采／晶電負責高階晶片、錼創負責巨量轉移、友達與群創負責背板與驅動 IC；錼創與晶電估 Micro LED 電視價格甜蜜點約在 2026–2027 年。同月 KRICT 在 Scientific Reports 公開 3,952 組螢光粉光學性質資料集。",
         "why": "Micro LED 以 RGB 自發光為主，長期可能減少大尺寸顯示對螢光粉的需求，但目前規模仍小；小尺寸與 AR 仍靠量子點色轉換。", "entities": ["友達", "富采", "錼創"], "confidence": "high",
         "src": "https://www.ledinside.com/news/2024/4/2024_04_19_01", "srcName": "LEDinside 2024-04-19"},
        {"date": "2024-03-27", "title": "中國 2023 年 LED 螢光粉產量達 600 噸；三基色粉 500 噸、長餘輝粉 240 噸", "region": "中國", "tags": ["市場"],
         "detail": "中國鋼鐵新聞網報導 2023 年 LED 螢光粉產量 600 噸（較 2022 年 +8%）；《Journal of Rare Earths》2025 年綜述另列三基色 500 噸（−25%）、長餘輝 240 噸（−1%），並指出產學界轉向低成本高效率合成與全光譜、寬色域、Mini LED 所需的青光與窄帶綠紅材料。",
         "why": "提供全球最大螢光粉產地的產量基準，可對照後續稀土管制與價格波動的影響；三基色粉持續萎縮反映螢光燈退場。", "entities": ["中國鋼鐵新聞網", "Journal of Rare Earths"], "confidence": "medium",
         "src": "https://www.sciencedirect.com/science/article/abs/pii/S1002072125002832", "srcName": "Journal of Rare Earths 2025"},
        {"date": "2024-03", "title": "臺大劉如熹團隊「玻璃保護鈣鈦礦量子點」綜述登上 Progress in Materials Science", "region": "台灣", "tags": ["論文", "量子點", "台灣"],
         "detail": "系統整理 CsPbX₃ 鈣鈦礦量子點的發光機制、不穩定成因，以及以玻璃基質包覆（quantum dot in glass）提升穩定度、應用於背光 LED 與顯示器的方法。同月劉如熹獲國輻中心第 4 屆光環論文獎（2018 年近紅外 LED 論文引用逾 300 次並技轉億光）。",
         "why": "把「玻璃包覆」這個螢光粉的老方法用到鈣鈦礦量子點上，是台灣團隊跨足量子點的代表作。", "entities": ["劉如熹", "臺灣大學"], "confidence": "high",
         "src": "https://www.ntu.edu.tw/spotlight/2024/2240_20240306.html", "srcName": "臺大焦點新聞 2024-03-06"},
        {"date": "2024-02-28", "title": "ams OSRAM 宣布 Micro LED 核心專案遭客戶取消，認列 6–9 億歐元減損", "region": "歐洲", "tags": ["併購與重整", "Micro LED", "市場"],
         "detail": "Micro LED 計畫的「基石客戶」（業界普遍指 Apple Watch 專案，官方未點名）意外取消，預計對相關資產與商譽認列 6 億至 9 億歐元非現金減損，並重新評估馬來西亞居林 8 吋新廠的用途；其後決定大致退出 Micro LED 顯示市場，僅保留車用方向。",
         "why": "2024 年 LED 產業最大衝擊事件，也讓「量子點／螢光粉色轉換 Micro LED」與「原生 RGB Micro LED」路線之爭重新洗牌。", "entities": ["ams OSRAM", "Apple"], "confidence": "high",
         "src": "https://ams-osram.com/news/press-releases/revised-microled-strategy", "srcName": "ams OSRAM 新聞稿 2024-02-28"},
        {"date": "2024-01-24", "title": "日亞推出橫向配光的晶片級白光 LED NFSWL11A-D6", "region": "日本", "tags": ["產品"],
         "detail": "透過封裝結構讓光線以水平方向分佈，營造柔和無眩光的照明；同日發表帶透鏡的全彩 RGB LED NSSM237B。",
         "why": "CSP 白光 LED 已從單純追求亮度轉向以螢光粉層與封裝幾何控制配光。", "entities": ["日亞化學"], "confidence": "high",
         "src": "https://www.nichia.co.jp/en/newsroom/2024/2024_012401.html", "srcName": "日亞新聞室 2024-01-24"},
        {"date": "2024", "title": "LMU 慕尼黑團隊發表窄帶綠色螢光粉 Ba[BeSiON₂]:Eu²⁺（峰值 526 nm、半高寬約 45 nm）", "region": "歐洲", "tags": ["論文", "顯示背光"],
         "detail": "Advanced Optical Materials 報導新型氧氮化鈹矽酸鹽，在紫外或藍光激發下發出窄帶綠光，鎖定廣色域顯示背光；含鈹化合物具毒性疑慮，商業化門檻高。同年 NIMS 以機器學習分類 Eu 價態合成 12 種新 Eu²⁺ 螢光粉。",
         "why": "窄帶綠粉是 β-SiAlON:Eu 之外的候選材料，對 Mini LED 背光的色域提升具潛在意義。", "entities": ["LMU 慕尼黑"], "confidence": "medium",
         "src": "https://advanced.onlinelibrary.wiley.com/doi/full/10.1002/adom.202302343", "srcName": "Advanced Optical Materials 2024"},
    ],
}

# 第一版（2026-09-07）已刊出、未被上方取代的條目，保留並統一標籤。
NEWS["items"].extend([
    {"date": "2026-04-09", "title": "Samsung Display QD-OLED 螢幕面板累計出貨突破 500 萬片", "region": "韓國", "tags": ["量子點", "市場"],
     "detail": "2025 年出貨約 250 萬片，在全球 OLED 螢幕面板市占約 75%；重心已從電視轉向獲利較好的電競螢幕。Omdia 預估 2026 年 Samsung Display 與 LG Display 合計 OLED 螢幕面板出貨 540 萬片。",
     "why": "QD-OLED 用的是噴墨列印的 InP 量子點色轉換層，是螢光粉在自發光面板上缺席的領域。", "entities": ["Samsung Display", "Omdia"], "confidence": "high",
     "src": "https://www.koreatimes.co.kr/business/companies/20260409/samsung-displays-qd-oled-monitor-panels-surpass-5-mil-cumulative-shipments", "srcName": "The Korea Times 2026-04-09"},
    {"date": "2026-03-04", "title": "Hisense 宣布 2025 年雷射電視全球市占 70.3%，連續七年第一", "region": "中國", "tags": ["雷射照明", "市場"],
     "detail": "雷射電視本質是「藍光雷射＋螢光粉輪」的超短焦投影機。光峰科技掌握 ALPD 螢光粉輪核心智財，2019 年在中國雷射投影光源市占 98.6%；2024 年總營收人民幣 24.19 億元，車載光學 6.38 億元。",
     "why": "顯示領域中螢光粉除了背光之外的另一個重要出海口，且由中國廠商主導。", "entities": ["Hisense", "光峰科技"], "confidence": "medium",
     "src": "https://tools.prnewswire.com/en-us/live/20823/release/20260304EN01197", "srcName": "PR Newswire（Hisense）2026-03"},
    {"date": "2026-02-18", "title": "《Nature》：首爾大學發表可量產、100% 量子產率的鈣鈦礦奈米晶「冷注入」合成法", "region": "韓國", "tags": ["量子點", "論文"],
     "detail": "李泰雨團隊的方法不需高溫、真空或特殊氣體，從實驗室放大到工業規模仍維持 100% 光致發光量子產率；衍生新創 SN Display 以鈣鈦礦顯示原型獲 CES 2026 創新獎。",
     "why": "鈣鈦礦譜線可小於 20 nm 且成本低，是螢光粉與傳統量子點在色轉換上的新競爭者；量產一致性一直是它的瓶頸。", "entities": ["首爾大學", "SN Display"], "confidence": "high",
     "src": "https://www.nature.com/articles/s41586-026-10117-2", "srcName": "Nature 2026"},
    {"date": "2026-01", "title": "SID《Information Display》：KSF 稱霸廣色域顯示十年，累計出貨逾 1,000 億顆 LED", "region": "美國", "tags": ["KSF", "顯示背光", "市場"],
     "detail": "GE／Edison 出身的 Murphy 與 Hendy 回顧：2014 年推出至 2025 年，含 KSF 的顯示用 LED 銷量超過 1,000 億顆；Display Week 2025 近 80 台 LCD 中過半含 KSF、車用展品逾七成；美國展廳車用顯示器逾四成、123 款車型中 55% 的中控或儀表為 KSF；估計 KSF 可觸及市場約為量子點的兩到四倍。",
     "why": "數字來自專利持有方陣營，但仍是目前對 KSF 市場地位最完整的公開描述。", "entities": ["Edison Innovations", "SID"], "confidence": "medium",
     "src": "https://sid.onlinelibrary.wiley.com/doi/10.1002/msid.70057", "srcName": "SID Information Display 2026"},
    {"date": "2026-01", "title": "《Advanced Functional Materials》：青色 Li₂CaSiO₄:Eu²⁺ 陶瓷讓紫光雷射全光譜照明達 Ra 96.5", "region": "中國", "tags": ["論文", "雷射照明", "健康照明"],
     "detail": "發光峰 482 nm、半高寬 30 nm、相對密度 97.7%，200 °C 仍保有 92.3% 發光，紫光雷射連續照射 120 分鐘幾乎不衰減。",
     "why": "補上 YAG:Ce 白光在青色區的缺口，是雷射照明走向高顯色的關鍵材料之一。", "entities": ["Li2CaSiO4:Eu"], "confidence": "high",
     "src": "https://advanced.onlinelibrary.wiley.com/doi/10.1002/adfm.202515542", "srcName": "Advanced Functional Materials 2026"},
    {"date": "2026-01", "title": "NIMS 以「單顆粒診斷法」發現具兩個窄頻發光的 SrLi₃AlO₄:Eu²⁺", "region": "日本", "tags": ["論文"],
     "detail": "從混相粉末中挑出單顆發光晶粒直接做結構與光譜分析，發現受 SLA 啟發的氧化物版本 SrLi₃AlO₄:Eu²⁺，發表於 Science and Technology of Advanced Materials。",
     "why": "顯示 UCr₄C₄ 型氧化物仍是活躍的探索領域，而單顆粒診斷法是日本獨特的材料發現工具。", "entities": ["NIMS"], "confidence": "medium",
     "src": "https://doi.org/10.1080/14686996.2026.2650843", "srcName": "STAM 2026"},
    {"date": "2025-07", "title": "《Journal of Advanced Ceramics》：核殼式 YAG:Ce@Al₂O₃ 螢光陶瓷晶圓亮度 3,900 lm/mm²", "region": "中國", "tags": ["論文", "雷射照明"],
     "detail": "仿光纖結構：Al₂O₃ 包層折射率較低，把光斑限制在幾乎等於入射藍光雷射的大小（核心 1.0 mm），同時提供高導熱；飽和門檻 30 W/mm²、最大白光 2,100 lm。",
     "why": "「小而亮」是雷射照明的核心指標，這個結構同時解決了散熱與光斑擴散兩個問題。", "entities": ["YAG:Ce@Al2O3"], "confidence": "high",
     "src": "https://www.sciopen.com/article/10.26599/JAC.2025.9221137", "srcName": "Journal of Advanced Ceramics 2025"},
    {"date": "2025-04-25", "title": "Touch Taiwan 2025：群創、錼創、友達、工研院的 Micro LED 全走「藍光晶片＋量子點色轉換」", "region": "台灣", "tags": ["Micro LED", "量子點", "台灣"],
     "detail": "群創以藍光 Micro LED 搭配量子點色轉換，只需轉移一種顏色的晶片；錼創與 Lumus 展示量子點轉色的單晶片全彩微投影機；工研院發表結合量子點的全彩微顯示模組；友達 2025 年 9 月供應 Garmin 1.39 吋 Micro LED 手錶面板。",
     "why": "台灣 Micro LED 產業鏈在色轉換上押注量子點，螢光粉要進入這個市場必須先解決顆粒尺寸與吸收問題。", "entities": ["群創", "錼創", "友達", "工研院"], "confidence": "high",
     "src": "https://www.trendforce.com/news/2025/04/25/insight-touch-taiwan-2025-promising-potential-for-micro-led-displays-and-optical-communication/", "srcName": "TrendForce 2025-04-25"},
    {"date": "2025-04", "title": "《Advanced Science》：透明螢光陶瓷直接燒在藍寶石上，導熱 36.9 W/(m·K)、5,902 lm", "region": "中國", "tags": ["論文", "雷射照明"],
     "detail": "不再靠混入高導熱微晶稀釋發光相，而是以高溫燒結把透明陶瓷與藍寶石結合；同一策略在多種陶瓷系統中使發光提升 152–319%、飽和門檻提高 100–233%。",
     "why": "為雷射照明提供一個通用的散熱架構，而不是針對單一材料的配方。", "entities": ["透明陶瓷@藍寶石"], "confidence": "high",
     "src": "https://advanced.onlinelibrary.wiley.com/doi/10.1002/advs.202505232", "srcName": "Advanced Science 2025"},
    {"date": "2025-01", "title": "Regal Cineworld 宣布 2030 年前 4,000 個影廳換裝 Barco 雷射螢光投影", "region": "美國／歐洲", "tags": ["雷射照明", "市場"],
     "detail": "Barco 2015 年推出首台 18,000 流明雷射螢光影院投影機；Regal 換裝後能源消耗比燈泡機減少最多 70%。",
     "why": "電影放映是螢光粉輪最大的專業市場之一，換裝潮直接帶動需求。", "entities": ["Barco", "Regal"], "confidence": "medium",
     "src": "https://www.barco.com/it/News/Press-releases/Barco-first-to-launch-18000-lumen-laser-phosphor-projector-for-cinema.aspx", "srcName": "Barco 新聞稿；Forbes 2025-01"},
    {"date": "2025", "title": "「假 QLED」爭議：檢測未驗出銦與鎘，Samsung 在德國對 TCL 勝訴", "region": "歐洲／美國／中國", "tags": ["量子點", "法規與標準", "顯示背光"],
     "detail": "SGS 與 Intertek 對三款 TCL「量子點」電視的檢測未驗出銦或鎘；德國法院認定 TCL 部分 QLED 廣告違反不正競爭法，美國也有針對 TCL 與 Hisense 的集體訴訟。TCL 稱其對量子點膜的檢測有驗出鎘化合物。",
     "why": "對消費者而言，「QLED」標籤不保證真的用了量子點，部分產品可能只靠 KSF 螢光粉達到廣色域。", "entities": ["Samsung", "TCL", "Hisense"], "confidence": "medium",
     "src": "https://www.techspot.com/news/111693-samsung-wins-court-ruling-after-german-judge-tcl.html", "srcName": "TechSpot 2025"},
    {"date": "2025", "title": "鈣鈦礦量子點膜首次商用：致晶科技與 TCL 試產 500 台 75 吋電視", "region": "中國", "tags": ["量子點", "產品", "顯示背光"],
     "detail": "以綠色無鎘鈣鈦礦量子點膜製作的量子點增強 LCD 電視在中國售出，色域達 147% BT.709；2024 年實驗室的 CsPbBr₃ 膜已達 PLQY 94%、98.8% Rec.2020。",
     "why": "鈣鈦礦從論文走到貨架的第一步，雖仍是試產規模。", "entities": ["致晶科技", "TCL"], "confidence": "medium",
     "src": "https://www.oled-info.com/tcl-brings-perovskite-qds-enhanced-lcds-market-pilot-project", "srcName": "OLED-Info"},
    {"date": "2025", "title": "高顯色雷射白光新高：CRI 95.4、220 lm/W（Optics Express）", "region": "中國", "tags": ["論文", "雷射照明"],
     "detail": "「陶瓷—螢光粉複合架構」在 28.76 W/mm² 的高功率密度下同時達到顯色指數 95.4 與 220 lm/W。",
     "why": "證明雷射照明也能做出接近自然光的光色品質，前提是紅光成分的散熱處理得當。", "entities": ["Optics Express"], "confidence": "medium",
     "src": "https://pubmed.ncbi.nlm.nih.gov/40733923/", "srcName": "Optics Express 2025（PubMed）"},
    {"date": "2024-08-14", "title": "Forbes：雷射頭燈正在退場，BMW 與 Audi 已無後續計畫", "region": "歐洲／美國", "tags": ["雷射照明", "市場", "車用"],
     "detail": "美國 FMVSS 108 限制每套頭燈 150,000 cd，使雷射在美國只能照約 250 公尺、無法發揮 600 公尺優勢；矩陣 LED 配光更好、成本更低，2024–2025 年式 BMW 3 系列與 5 系列已改用 LED；2024 年仍配備雷射燈的車款只剩 BMW X7、4 系 Gran Coupe 與 Audi A5／A7／Q7／Q8 等。",
     "why": "雷射螢光轉換器在車用的壓力，讓研發重心轉向投影、特殊照明與微型化封裝（如日亞 GigaWhite）。", "entities": ["BMW", "Audi"], "confidence": "high",
     "src": "https://www.forbes.com/sites/michaeltaylor/2024/08/14/laser-headlamps-are-disappearing-heres-why/", "srcName": "Forbes 2024-08-14"},
    {"date": "2024-06", "title": "瑞豐光電與 GE Lighting Solutions 續簽 KSF 背光廣色域全球授權", "region": "中國", "tags": ["專利授權", "KSF"],
     "detail": "瑞豐 2016 年成為中國首家取得 GE KSF 應用專利授權的封裝廠，2024 年 6 月續簽，範圍為顯示背光廣色域應用；公司將以 KSF 搭配 β-SiAlON 綠粉。",
     "why": "顯示即使 GE 專利即將易主，中國廠商仍持續透過授權合法使用 KSF。", "entities": ["瑞豐光電", "GE Lighting"], "confidence": "high",
     "src": "https://lights.ofweek.com/2024-06/ART-8100-2200-30637247.html", "srcName": "OFweek 半導體照明網 2024-06"},
    {"date": "2024-05-21", "title": "歐盟公布 RoHS 含鎘量子點豁免修正案 (EU) 2024/1416", "region": "歐洲", "tags": ["法規與標準", "量子點"],
     "detail": "顯示與照明用 39(a) 豁免只延長到 2025 年 11 月 21 日；新增 39(b) 允許晶片上含鎘量子點用到 2027 年 12 月 31 日，鎘含量每 mm² 晶片低於 5 µg、每裝置不超過 1 mg；成員國須於 2024 年底前轉化、2025 年 1 月 1 日適用。",
     "why": "為整個顯示產業定下無鎘化的時間表。", "entities": ["歐盟"], "confidence": "high",
     "src": "https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32024L1416", "srcName": "EUR-Lex (EU) 2024/1416"},
    {"date": "2024", "title": "含量子點的 LCD 電視 2024 年出貨 2,440 萬台創新高；量子點膜營收年增 42%", "region": "全球", "tags": ["市場", "量子點", "顯示背光"],
     "detail": "2023 年為 1,550 萬台；Counterpoint 指出 2024 年量子點膜與擴散板營收年增 42%，Apple MacBook Pro M4 首度改用量子點顯示器（先前 Mini LED 機種使用螢光粉片）。研究顯示頻閃背光下量子點色彩響應比 KSF 快（KSF 衰減約 5–8 毫秒），但 KSF 成本低、無鎘、可靠。",
     "why": "KSF 與量子點在 Mini LED 背光上持續競合，而非誰取代誰。", "entities": ["Counterpoint", "Omdia", "Nanosys"], "confidence": "medium",
     "src": "https://counterpointresearch.com/en/insights/increased-quantum-dot-adoption-in-displays-drives-double-digit-revenue-growth-in-2024", "srcName": "Counterpoint Research 2024"},
    {"date": "2024", "title": "KSF 防潮新解法：NaClO 一步處理長出小於 5 nm 的複合殼層；H₂NbF₇ 表面重構 IQE 98.9%", "region": "中國", "tags": ["KSF", "論文"],
     "detail": "Advanced Optical Materials 報導 NaClO 處理後 60 天保有 86% 強度；ACS Applied Materials & Interfaces 報導兩步表面重構後 85 °C／85% RH 六天幾乎不衰。",
     "why": "怕水是 KSF 最大的可靠度隱憂，低成本表面修補技術是它守住車用市場的關鍵。", "entities": ["KSF"], "confidence": "high",
     "src": "https://advanced.onlinelibrary.wiley.com/doi/10.1002/adom.202401498", "srcName": "Advanced Optical Materials 2024"},
    {"date": "2024", "title": "NIMS 與廈門大學合成富鍶新型 α-SiAlON:Eu²⁺", "region": "日本／中國", "tags": ["論文"],
     "detail": "單相 Sr₃Si₂₄Al₆N₄₀:Eu²⁺ 的 Sr 含量比先前極限高出 200% 以上，400 nm 激發下發 590 nm 橙黃光，150 °C 仍保有 93% 亮度。",
     "why": "顯示 SiAlON 家族在發明近 20 年後仍有新組成可挖。", "entities": ["NIMS", "廈門大學"], "confidence": "high",
     "src": "https://www.tandfonline.com/doi/full/10.1080/14686996.2024.2396276", "srcName": "STAM 2024"},
    {"date": "2024", "title": "螢光玻璃新高：Ce:YAG PiG 在 6.87 W 藍光雷射下輸出 1,481 lm、221.7 lm/W", "region": "中國", "tags": ["論文", "雷射照明"],
     "detail": "以鋰鋁矽玻璃低溫燒結，內量子效率 88.3%、導熱率 3.33 W/(m·K)；玻璃導熱雖不如陶瓷，但比矽膠高一個數量級且不會黃化。",
     "why": "螢光玻璃是取代矽膠最便宜的方案，已長期用於車用頭燈。", "entities": ["Ce:YAG PiG"], "confidence": "medium",
     "src": "https://www.sciencedirect.com/science/article/abs/pii/S0272884224043761", "srcName": "Ceramics International 2024"},
    {"date": "2023-09-06", "title": "日本昭榮化學完成收購 Nanosys 量子點事業", "region": "日本／美國", "tags": ["併購與重整", "量子點"],
     "detail": "包含超過 800 件已核准與申請中的專利、矽谷研發實驗室與銷售團隊；Nanosys 是 QDEF 量子點增亮膜先驅與 Samsung 等品牌的主要供應商，收購後仍以 Nanosys 品牌營運，昭榮自 2019 年起已負責其全部量產。",
     "why": "全球最重要的量子點智財之一轉入日本材料廠手中，日本在色轉換材料（螢光粉與量子點）的掌握度再提升。", "entities": ["昭榮化學", "Nanosys"], "confidence": "high",
     "src": "https://www.businesswire.com/news/home/20230907824277/en/Shoei-Chemical-Acquires-Quantum-Dot-Business-from-Nanosys", "srcName": "Business Wire 2023-09"},
])

