# -*- coding: utf-8 -*-
"""最新動態：2023 年下半年至整理時點的重要事件，每則附日期、為什麼重要與來源。
date 用 YYYY-MM 或 YYYY-MM-DD；tags 供篩選。"""

NEWS = {
    "lead": "把 2024 年到 2026 年 9 月之間，跟螢光粉直接相關的產品發表、論文、專利授權、法規與市場數字排成一條時間線。每則都標了「為什麼重要」，可依年份、主題或地區篩選。",
    "items": [
        {"date": "2026-08-31", "title": "Edison Innovations 大舉授權 KSF 專利給台灣、中國、韓國、美國 LED 廠", "region": "台灣／全球", "tags": ["專利授權", "顯示背光", "KSF"],
         "detail": "GE 約 2,500 件專利在 2025 年初轉到 Edison Innovations。2026 年已將 KSF 窄頻紅粉專利授權給億光、富采、芯瑞達、萬潤、木林森、惠州 Torch Energy、韓國 Lumens 與美國 Bridgelux；並與 Current Chemicals 開發次微米高吸收 KSF 墨水，瞄準 Micro LED 與發光彩色濾光片。",
         "why": "KSF 是少數仍受嚴密專利保護的主流螢光粉；台灣封裝廠取得授權，代表車用與 Mini LED 背光市場的合規供應鏈成形。", "entities": ["Edison Innovations", "億光", "富采", "Bridgelux"], "confidence": "high",
         "src": "https://www.ledinside.com/interview/2026/8/2026_08_31_01", "srcName": "LEDinside 專訪 2026-08-31"},
        {"date": "2026-08-24", "title": "TrendForce：2025 年 Mini LED 電視 1,156 萬台，2026 年 RGB Mini LED 上看 170–200 萬台", "region": "全球", "tags": ["市場", "顯示背光"],
         "detail": "Mini LED 背光電視 2025 年出貨年增 50%；2026 年 RGB Mini LED 電視預測上修至 170 萬台、有機會逼近 200 萬台。Mini LED 背光採用大量 LED，是 KSF／β-SiAlON 或量子點膜的主要出海口，而 RGB Mini LED 改用三色晶片則不需要螢光粉。",
         "why": "Mini LED 放量是螢光粉需求的正面訊號，RGB Mini LED 則是高階市場「去色轉換化」的隱憂。", "entities": ["TrendForce"], "confidence": "medium",
         "src": "https://www.ledinside.com/intelligence/2026/8/2026_08_24_05", "srcName": "LEDinside／TrendForce 2026-08"},
        {"date": "2026-05-13", "title": "NIMS：CASN 紅粉中國專利歷經六年無效訴訟，全部請求項維持有效", "region": "日本／中國", "tags": ["專利授權", "氮化物紅粉"],
         "detail": "中國專利第 200580005112.5 號（涵蓋 CASN／SCASN 紅粉 LED 裝置）自 2019 年起被江蘇博睿多次提出無效請求，2020 年曾被裁定部分無效；2025 年 12 月 25 日中國最高人民法院撤銷該裁定並發回，博睿隨後撤回請求。",
         "why": "確認氮化物紅粉的專利在中國仍有效，對三菱化學、Denka 等授權製造商與中國廠商的競爭格局影響直接。", "entities": ["NIMS", "三菱化學", "江蘇博睿"], "confidence": "high",
         "src": "https://www.nims.go.jp/eng/press/2026/05/202605130.html", "srcName": "NIMS 新聞稿 2026-05-13"},
        {"date": "2026-05", "title": "Samsung Display 在 SID 2026 展出無鎘電致發光量子點原型：18 吋 500 nits", "region": "韓國", "tags": ["量子點", "顯示背光"],
         "detail": "EL-QD 是量子點自己通電發光、不需 OLED 或 LED 的終極形態。18 吋 500 nits 與 6.5 吋 400 nits 原型亮度分別比前一年提升 25% 與 33%，皆為無鎘配方；商用時程未公布，Nanosys 曾提到 2029 年。",
         "why": "若 EL-QD 商用，顯示器將不再需要色轉換層；但距離量產仍遠，螢光粉與量子點色轉換在可見的未來仍是主流。", "entities": ["Samsung Display"], "confidence": "high",
         "src": "https://global.samsungdisplay.com/31450", "srcName": "Samsung Display 新聞稿"},
        {"date": "2026-04", "title": "Samsung Display QD-OLED 螢幕面板累計出貨突破 500 萬片", "region": "韓國", "tags": ["量子點", "市場"],
         "detail": "2025 年出貨約 250 萬片，在全球 OLED 螢幕面板市占約 75%；重心已從電視轉向獲利較好的電競螢幕。Omdia 預估 2026 年 Samsung Display 與 LG Display 合計 OLED 螢幕面板出貨 540 萬片。",
         "why": "QD-OLED 用的是噴墨列印的 InP 量子點色轉換層，是螢光粉在自發光面板上缺席的領域。", "entities": ["Samsung Display", "Omdia"], "confidence": "high",
         "src": "https://www.koreatimes.co.kr/business/companies/20260409/samsung-displays-qd-oled-monitor-panels-surpass-5-mil-cumulative-shipments", "srcName": "The Korea Times 2026-04-09"},
        {"date": "2026-03", "title": "Hisense 宣布 2025 年雷射電視全球市占 70.3%，連續七年第一", "region": "中國", "tags": ["雷射照明", "市場"],
         "detail": "雷射電視本質是「藍光雷射＋螢光粉輪」的超短焦投影機。光峰科技（Appotronics）掌握 ALPD 螢光粉輪核心智財與中國七到八成的電影雷射放映機市場；2024 年影院營收人民幣 24.19 億元。",
         "why": "顯示領域中螢光粉除了背光之外的另一個重要出海口，且由中國廠商主導。", "entities": ["Hisense", "Appotronics"], "confidence": "medium",
         "src": "https://tools.prnewswire.com/en-us/live/20823/release/20260304EN01197", "srcName": "PR Newswire（Hisense）"},
        {"date": "2026-02-18", "title": "《Nature》：首爾大學發表可量產、100% 量子產率的鈣鈦礦奈米晶「冷注入」合成法", "region": "韓國", "tags": ["量子點", "論文"],
         "detail": "李泰雨（Tae-Woo Lee）團隊的方法不需高溫、真空或特殊氣體，從實驗室放大到工業規模仍維持 100% 光致發光量子產率；衍生新創 SN Display 以鈣鈦礦顯示原型獲 CES 2026 創新獎。",
         "why": "鈣鈦礦譜線可小於 20 nm 且成本低，是螢光粉與傳統量子點在色轉換上的新競爭者；量產一致性一直是它的瓶頸。", "entities": ["首爾大學", "SN Display"], "confidence": "high",
         "src": "https://www.nature.com/articles/s41586-026-10117-2", "srcName": "Nature 2026"},
        {"date": "2026-01", "title": "SID《Information Display》：KSF 稱霸廣色域顯示十年，累計出貨逾 1,000 億顆 LED", "region": "美國", "tags": ["KSF", "顯示背光", "市場"],
         "detail": "GE／Edison 出身的 Murphy 與 Hendy 回顧：2014 年推出至 2025 年，含 KSF 的顯示用 LED 銷量超過 1,000 億顆；SID 2025 展場近 80 台 LCD 中過半含 KSF，車用展品七成以上；估計 KSF 可觸及市場約為量子點的兩到四倍。",
         "why": "數字來自專利持有方陣營，但仍是目前對 KSF 市場地位最完整的公開描述。", "entities": ["Edison Innovations", "SID"], "confidence": "medium",
         "src": "https://sid.onlinelibrary.wiley.com/doi/10.1002/msid.70057", "srcName": "SID Information Display 2026"},
        {"date": "2026-01", "title": "Samsung 擴大 Micro RGB 電視產品線：55–115 吋，三色晶片背光不需螢光粉或量子點", "region": "韓國", "tags": ["顯示背光", "市場"],
         "detail": "Micro RGB 使用小於 100 µm 的紅綠藍三色 LED 當背光，宣稱 100% BT.2020 覆蓋；售價從 1,599 美元（55 吋）到 29,999 美元（115 吋）。Hisense、TCL、LG、Sony 也推出 RGB Mini LED 電視。",
         "why": "高階 LCD 背光開始繞過色轉換材料，但成本仍高，主流機種預期沿用螢光粉／量子點方案。", "entities": ["Samsung"], "confidence": "high",
         "src": "https://news.samsung.com/us/samsung-expands-premium-micro-rgb-tv-lineup-2026-new-sizes-advanced-features", "srcName": "Samsung Newsroom 2026"},
        {"date": "2026-01", "title": "《Nature Communications》：機器學習加脈衝快速燒結，10 秒燒成雷射用 LuAG:Ce 陶瓷", "region": "中國", "tags": ["雷射照明", "AI 材料", "論文"],
         "detail": "Wang、Xiong、Qiu 等人結合機器學習與脈衝高溫快速燒結，在 10 秒內燒成緻密細晶 Lu₃Al₅O₁₂:Ce 陶瓷，光轉換效率提高 31%、斷裂韌性提高 1.5 倍；LuAG:Ce–CaAlSiN₃:Eu 複合陶瓷藍光雷射激發下顯色指數 93，用於可見光通訊光源。",
         "why": "把燒結時間從小時級縮到秒級，同時用 AI 找參數，是雷射螢光陶瓷量產化的重要一步。", "entities": ["浙江大學"], "confidence": "high",
         "src": "https://www.nature.com/articles/s41467-026-74741-2", "srcName": "Nature Communications 2026"},
        {"date": "2026-01", "title": "《Advanced Functional Materials》：青色 Li₂CaSiO₄:Eu²⁺ 陶瓷讓紫光雷射全光譜照明達 Ra 96.5", "region": "中國", "tags": ["青色缺口", "雷射照明", "論文"],
         "detail": "發光峰 482 nm、半高寬 30 nm、相對密度 97.7%，200 °C 仍保有 92.3% 發光，紫光雷射連續照射 120 分鐘幾乎不衰減。",
         "why": "補上 YAG:Ce 白光在青色區的缺口，是雷射照明走向高顯色的關鍵材料之一。", "entities": ["Li2CaSiO4:Eu"], "confidence": "high",
         "src": "https://advanced.onlinelibrary.wiley.com/doi/10.1002/adfm.202515542", "srcName": "Advanced Functional Materials 2026"},
        {"date": "2026-01", "title": "NIMS 以「單顆粒診斷法」發現具兩個窄頻發光的 SrLi₃AlO₄:Eu²⁺", "region": "日本", "tags": ["窄頻", "論文"],
         "detail": "從混相粉末中挑出單顆發光晶粒直接做結構與光譜分析，發現受 SLA 啟發的氧化物版本 SrLi₃AlO₄:Eu²⁺，發表於 Science and Technology of Advanced Materials。",
         "why": "顯示 UCr₄C₄ 型氧化物仍是活躍的探索領域，而單顆粒診斷法是日本獨特的材料發現工具。", "entities": ["NIMS"], "confidence": "medium",
         "src": "https://doi.org/10.1080/14686996.2026.2650843", "srcName": "STAM 2026"},
        {"date": "2025-11-21", "title": "歐盟 RoHS 顯示用含鎘量子點豁免到期", "region": "歐洲", "tags": ["法規", "量子點"],
         "detail": "2024 年 5 月 21 日公布的修正案只把 39(a) 豁免延長一年並給 18 個月緩衝，最終在 2025 年 11 月 21 日失效；新增的 39(b) 允許直接沉積在 LED 晶片上的含鎘量子點用到 2027 年底（每 mm² 晶片鎘含量低於 5 µg）。",
         "why": "在歐盟販售的電視不能再用 CdSe 量子點膜，加速轉向 InP、鈣鈦礦，或回到 KSF 螢光粉方案。", "entities": ["歐盟"], "confidence": "high",
         "src": "https://www.tuv.com/regulations-and-standards/en/eu-exemptions-on-the-use-of-cadmium-in-quantum-dots-in-led-lighting-and-displays.html", "srcName": "TÜV Rheinland"},
        {"date": "2025-07", "title": "《Journal of Advanced Ceramics》：核殼式 YAG:Ce@Al₂O₃ 螢光陶瓷晶圓亮度 3,900 lm/mm²", "region": "中國", "tags": ["雷射照明", "論文"],
         "detail": "仿光纖結構：Al₂O₃ 包層折射率較低，把光斑限制在幾乎等於入射藍光雷射的大小（核心 1.0 mm），同時提供高導熱；飽和門檻 30 W/mm²、最大白光 2,100 lm。",
         "why": "「小而亮」是雷射照明的核心指標，這個結構同時解決了散熱與光斑擴散兩個問題。", "entities": ["YAG:Ce@Al2O3"], "confidence": "high",
         "src": "https://www.sciopen.com/article/10.26599/JAC.2025.9221137", "srcName": "Journal of Advanced Ceramics 2025"},
        {"date": "2025-04", "title": "《Advanced Science》：透明螢光陶瓷直接燒在藍寶石上，導熱 36.9 W/(m·K)、5,902 lm", "region": "中國", "tags": ["雷射照明", "論文"],
         "detail": "不再靠混入高導熱微晶稀釋發光相，而是以高溫燒結把透明陶瓷與藍寶石結合；同一策略在多種陶瓷系統中使發光提升 152–319%、飽和門檻提高 100–233%。",
         "why": "為雷射照明提供一個通用的散熱架構，而不是針對單一材料的配方。", "entities": ["透明陶瓷@藍寶石"], "confidence": "high",
         "src": "https://advanced.onlinelibrary.wiley.com/doi/10.1002/advs.202505232", "srcName": "Advanced Science 2025"},
        {"date": "2025-04", "title": "Touch Taiwan 2025：群創、錼創、友達、工研院的 Micro LED 全走「藍光晶片＋量子點色轉換」", "region": "台灣", "tags": ["Micro LED", "量子點"],
         "detail": "群創以藍光 Micro LED 搭配量子點色轉換，只需轉移一種顏色的晶片；錼創與 Lumus 展示量子點轉色的單晶片全彩微投影機；工研院發表結合量子點的全彩微顯示模組；友達 2025 年底供應 Garmin 1.39 吋 Micro LED 手錶模組。",
         "why": "台灣 Micro LED 產業鏈在色轉換上押注量子點，螢光粉要進入這個市場必須先解決顆粒尺寸與吸收問題。", "entities": ["群創", "錼創", "友達", "工研院"], "confidence": "high",
         "src": "https://www.trendforce.com/news/2025/04/25/insight-touch-taiwan-2025-promising-potential-for-micro-led-displays-and-optical-communication/", "srcName": "TrendForce 2025-04-25"},
        {"date": "2025-01", "title": "Nichia 發表 GigaWhite 白光雷射封裝，亮度約為 LED 的 10 倍", "region": "日本", "tags": ["雷射照明", "產品"],
         "detail": "把藍光雷射二極體與螢光體整合成表面黏著封裝，內建感測器可電性偵測螢光體破裂或脫落以防止雷射外洩；車燈遠光 1,630 lm、近光 1,120 lm，均符合 ECE R112 Class-B，頭燈透鏡可縮到 10 mm 以下。",
         "why": "在 BMW 放棄雷射頭燈之後，日亞用「安全封裝」重新定義雷射照明產品。", "entities": ["Nichia"], "confidence": "high",
         "src": "https://led-ld.nichia.co.jp/en/product/ld_gigawhite.html", "srcName": "Nichia GigaWhite 產品頁"},
        {"date": "2025-01", "title": "Regal Cineworld 宣布 2030 年前 4,000 個影廳換裝 Barco 雷射螢光投影", "region": "美國／歐洲", "tags": ["雷射照明", "市場"],
         "detail": "Barco 2015 年推出首台 18,000 流明雷射螢光影院投影機；Regal 換裝後能源消耗比燈泡機減少最多 70%。",
         "why": "電影放映是螢光粉輪最大的專業市場之一，換裝潮直接帶動需求。", "entities": ["Barco", "Regal"], "confidence": "medium",
         "src": "https://www.barco.com/it/News/Press-releases/Barco-first-to-launch-18000-lumen-laser-phosphor-projector-for-cinema.aspx", "srcName": "Barco 新聞稿；Forbes 2025-01"},
        {"date": "2025", "title": "「假 QLED」爭議：檢測未驗出銦與鎘，Samsung 在德國對 TCL 勝訴", "region": "德國／美國／中國", "tags": ["量子點", "法規"],
         "detail": "SGS 與 Intertek 對三款 TCL「量子點」電視的檢測未驗出銦或鎘；德國法院認定 TCL 部分 QLED 廣告違反不正競爭法，美國也有針對 TCL 與 Hisense 的集體訴訟。TCL 稱其對量子點膜的檢測有驗出鎘化合物。",
         "why": "對消費者而言，「QLED」標籤不保證真的用了量子點，部分產品可能只靠 KSF 螢光粉達到廣色域。", "entities": ["Samsung", "TCL", "Hisense"], "confidence": "medium",
         "src": "https://www.techspot.com/news/111693-samsung-wins-court-ruling-after-german-judge-tcl.html", "srcName": "TechSpot 2025"},
        {"date": "2025", "title": "鈣鈦礦量子點膜首次商用：致晶科技與 TCL 試產 500 台 75 吋電視", "region": "中國", "tags": ["量子點", "產品"],
         "detail": "以綠色無鎘鈣鈦礦量子點膜製作的量子點增強 LCD 電視在中國售出，色域達 147% BT.709；2024 年實驗室的 CsPbBr₃ 膜已達 PLQY 94%、98.8% Rec.2020。",
         "why": "鈣鈦礦從論文走到貨架的第一步，雖仍是試產規模。", "entities": ["致晶科技", "TCL"], "confidence": "medium",
         "src": "https://www.oled-info.com/tcl-brings-perovskite-qds-enhanced-lcds-market-pilot-project", "srcName": "OLED-Info"},
        {"date": "2025", "title": "機器學習找到半高寬 44 nm 的窄頻綠粉 CsRbKNa(Li₃SiO₄)₄:Eu²⁺", "region": "中國", "tags": ["AI 材料", "窄頻", "論文"],
         "detail": "發表於 Chemical Engineering Journal，放射峰 530 nm、鎖定廣色域背光；同年 Laser & Photonics Reviews 綜述總結 UCr₄C₄ 型窄頻材料十年進展與怕水的弱點。",
         "why": "AI 與資料庫已成為螢光粉研發的新工具，但這類材料的耐濕性仍是商用門檻。", "entities": ["UCr4C4 型"], "confidence": "medium",
         "src": "https://www.sciencedirect.com/science/article/abs/pii/S138589472506557X", "srcName": "Chemical Engineering Journal 2025"},
        {"date": "2025", "title": "高顯色雷射白光新高：CRI 95.4、220 lm/W（Optics Express）", "region": "中國", "tags": ["雷射照明", "論文"],
         "detail": "「陶瓷—螢光粉複合架構」在 28.76 W/mm² 的高功率密度下同時達到顯色指數 95.4 與 220 lm/W。",
         "why": "證明雷射照明也能做出接近自然光的光色品質，前提是紅光成分的散熱處理得當。", "entities": ["Optics Express"], "confidence": "medium",
         "src": "https://pubmed.ncbi.nlm.nih.gov/40733923/", "srcName": "Optics Express 2025（PubMed）"},
        {"date": "2024-08", "title": "Forbes：雷射頭燈正在退場，BMW 已無後續計畫", "region": "德國／美國", "tags": ["雷射照明", "市場"],
         "detail": "美國 FMVSS 108 限制每套頭燈 150,000 cd，使雷射在美國只能照約 250 公尺、無法發揮 600 公尺優勢；矩陣 LED 配光更好、成本更低，2024–2025 年式 3 系列與 5 系列已改用 LED。",
         "why": "雷射螢光轉換器在車用的壓力，讓研發重心轉向投影、特殊照明與微型化封裝。", "entities": ["BMW"], "confidence": "high",
         "src": "https://www.forbes.com/sites/michaeltaylor/2024/08/14/laser-headlamps-are-disappearing-heres-why/", "srcName": "Forbes 2024-08-14"},
        {"date": "2024-06", "title": "瑞豐光電與 GE Lighting Solutions 續簽 KSF 背光廣色域全球授權", "region": "中國", "tags": ["專利授權", "KSF"],
         "detail": "瑞豐 2016 年成為中國首家取得 GE KSF 應用專利授權的封裝廠，2024 年 6 月續簽，範圍為顯示背光廣色域應用；公司將以 KSF 搭配 β-SiAlON 綠粉。",
         "why": "顯示即使 GE 專利即將易主，中國廠商仍持續透過授權合法使用 KSF。", "entities": ["瑞豐光電", "GE Lighting"], "confidence": "high",
         "src": "https://lights.ofweek.com/2024-06/ART-8100-2200-30637247.html", "srcName": "OFweek 半導體照明網 2024-06"},
        {"date": "2024-05-21", "title": "歐盟公布 RoHS 含鎘量子點豁免修正案", "region": "歐洲", "tags": ["法規", "量子點"],
         "detail": "顯示與照明用 39(a) 豁免只延長一年加 18 個月緩衝（2025 年 11 月 21 日失效）；新增 39(b) 允許晶片上含鎘量子點用到 2027 年 12 月 31 日，鎘含量每 mm² 晶片低於 5 µg、每裝置不超過 1 mg。",
         "why": "為整個顯示產業定下無鎘化的時間表。", "entities": ["歐盟"], "confidence": "high",
         "src": "https://www.greensofttech.com/blog-2024-cadmium-exemption-updates-to-eu-rohs/", "srcName": "GreenSoft Technology"},
        {"date": "2024", "title": "Omdia：含量子點的 LCD 電視 2024 年出貨 2,440 萬台創新高", "region": "全球", "tags": ["市場", "量子點"],
         "detail": "2023 年為 1,550 萬台；Omdia 預估 QD Mini LED 電視 2025 年 800 萬台、首度超越 OLED 電視。研究顯示頻閃背光下量子點色彩響應比 KSF 快（KSF 衰減約 8 毫秒），但 KSF 成本低、無鎘、可靠。",
         "why": "KSF 與量子點在 Mini LED 背光上持續競合，而非誰取代誰。", "entities": ["Omdia", "Nanosys"], "confidence": "medium",
         "src": "https://www.nanosys.com/blog-newsroom/omdia-shipments-of-qd-miniled-tvs-to-surpass-oled-tvs-by-2025", "srcName": "Nanosys／Omdia"},
        {"date": "2024", "title": "KSF 防潮新解法：NaClO 一步處理長出小於 5 nm 的複合殼層；H₂NbF₇ 表面重構 IQE 98.9%", "region": "中國", "tags": ["KSF", "論文"],
         "detail": "Advanced Optical Materials 報導 NaClO 處理後 60 天保有 86% 強度；ACS Applied Materials & Interfaces 報導兩步表面重構後 85 °C／85% RH 六天幾乎不衰。",
         "why": "怕水是 KSF 最大的可靠度隱憂，低成本表面修補技術是它守住車用市場的關鍵。", "entities": ["KSF"], "confidence": "high",
         "src": "https://advanced.onlinelibrary.wiley.com/doi/10.1002/adom.202401498", "srcName": "Advanced Optical Materials 2024"},
        {"date": "2024", "title": "NIMS 與廈門大學合成富鍶新型 α-SiAlON:Eu²⁺", "region": "日本／中國", "tags": ["氮化物", "論文"],
         "detail": "單相 Sr₃Si₂₄Al₆N₄₀:Eu²⁺ 的 Sr 含量比先前極限高出 200% 以上，400 nm 激發下發 590 nm 橙黃光，150 °C 仍保有 93% 亮度。",
         "why": "顯示 SiAlON 家族在發明近 20 年後仍有新組成可挖。", "entities": ["NIMS", "廈門大學"], "confidence": "high",
         "src": "https://www.tandfonline.com/doi/full/10.1080/14686996.2024.2396276", "srcName": "STAM 2024"},
        {"date": "2024", "title": "螢光玻璃新高：Ce:YAG PiG 在 6.87 W 藍光雷射下輸出 1,481 lm、221.7 lm/W", "region": "中國", "tags": ["雷射照明", "論文"],
         "detail": "以鋰鋁矽玻璃低溫燒結，內量子效率 88.3%、導熱率 3.33 W/(m·K)；玻璃導熱雖不如陶瓷，但比矽膠高一個數量級且不會黃化。",
         "why": "螢光玻璃是取代矽膠最便宜的方案，已長期用於車用頭燈。", "entities": ["Ce:YAG PiG"], "confidence": "medium",
         "src": "https://www.sciencedirect.com/science/article/abs/pii/S0272884224043761", "srcName": "Ceramics International 2024"},
        {"date": "2023-09-06", "title": "日本昭榮化學完成收購 Nanosys 量子點事業", "region": "日本／美國", "tags": ["量子點", "併購"],
         "detail": "包含超過 800 件已核准與申請中的專利、矽谷研發實驗室與銷售團隊；Nanosys 是 QDEF 量子點增亮膜先驅與 Samsung 等品牌的主要供應商，收購後仍以 Nanosys 品牌營運。",
         "why": "全球最重要的量子點智財之一轉入日本材料廠手中，日本在色轉換材料（螢光粉與量子點）的掌握度再提升。", "entities": ["昭榮化學", "Nanosys"], "confidence": "high",
         "src": "https://www.businesswire.com/news/home/20230907824277/en/Shoei-Chemical-Acquires-Quantum-Dot-Business-from-Nanosys", "srcName": "Business Wire 2023-09"},
    ],
}
