# -*- coding: utf-8 -*-
"""來源與說明：這個頁面怎麼做的、已知限制、主要來源類型。
完整的引用網址清單由 phosphor_build.py 自所有模組自動彙整，這裡只放人工整理的說明與代表性來源。"""

SOURCES = {
    "lead": "本頁是 2026 年 9 月一次性整理的快照。所有事實都附上當時可查到的公開來源連結；數字若各家不一致，會在文中標明範圍。它不是論文，也不是廠商規格書，請把它當成「看懂螢光粉世界的地圖」，細節仍以原始文獻為準。",
    "method": [
        "第一輪：分六個主題（原理與歷史、白光 LED 材料、顯示與量子點、雷射與高功率、近紅外與紫外、夜光／上轉換／閃爍體）各自做網路檢索，每個主題蒐集 25–40 條附來源的事實，並由獨立步驟試圖推翻或修正其中的數字、年份、人名與公司名。",
        "第二輪：另開七個獨立的研究工作階段，分別負責產業與供應鏈、學術版圖與 AI 材料探索、2024–2026 年動態、應用驅動的發展（人因照明、園藝、車用、紫外、近紅外、能源）、台灣與東亞生態系、長餘輝／閃爍體／近紅外，以及一次針對站內 181 條敘述的逐條事實查核。",
        "查核結果：181 條敘述中 149 條確認、24 條修正（例如 Lumileds 收購案時序、東芝材料易主、KSF 專利轉手鏈、日亞與億光並未和解、林群哲任職北科大、多份市場報告的數字）、8 條查無獨立來源（已標示或刪除），0 條被推翻。修正全部已併入本站。",
        "內容以 Python 模組維護，由產生器輸出 data/site.json；產生器會檢查欄位完整性、網址格式、日期格式與簡體用語，GitHub Actions 會比對資料檔與模組是否同步。",
    ],
    "caveats": [
        "光譜圖的曲線是依峰值波長與半高寬畫出的示意高斯曲線，不是實測光譜；KSF 等線狀發光以主峰示意。",
        "市場規模數字各研究機構相差 3–4 倍甚至十倍以上（2025 年從 5 億到 80 億美元），本頁只呈現範圍與來源，不下結論；中國產量的「600 噸」與「4.8 萬噸」是不同口徑。",
        "來自廠商新聞稿或專利持有方的數字（例如 KSF 累計出貨量、車用顯示採用率、SunLike 的健康效益、博睿的市占）已標明立場，未經第三方驗證。",
        "多數論文數據取自摘要或二手報導，實驗條件（雷射光斑、量測方法、電流與色溫）可能影響數字的可比性；部分論文的作者機構與發表月份僅能依卷期推估，引用時請查對 DOI。",
        "查無來源而未採用的常見說法：劉如熹「掌握台灣近半螢光粉專利」、日亞與億光「2022 年和解」、Denka 生產 KSF、三菱化學紅粉「50–80% 市占」（2012 年舊數字）。",
        "本頁整理時點之後的發展不會自動更新；「最新動態」以 2024 年到 2026 年 9 月為主。2026 年 11 月 10 日中國稀土管制暫停期到期是下一個關鍵時點。",
        "內容僅供學習與研究參考，不構成任何採購、投資或技術選型建議。",
    ],
    "list": [
        {"name": "NobelPrize.org – 2014 年物理獎新聞稿", "url": "https://www.nobelprize.org/prizes/physics/2014/press-release/", "kind": "官方", "year": "2014"},
        {"name": "Nichia – 白光 LED 25 週年", "url": "https://www.nichia.co.jp/specification/newsroom/news/Whiteled25anniversary.pdf", "kind": "廠商", "year": "2021"},
        {"name": "Chemical Reviews – 螢光粉世代演進（劉如熹團隊）", "url": "https://pubs.acs.org/doi/10.1021/acs.chemrev.1c00952", "kind": "期刊", "year": "2022"},
        {"name": "Nature Reviews Materials – 螢光粉發現指南（Brgoch、Setlur 等）", "url": "https://www.nature.com/articles/s41578-023-00605-6", "kind": "期刊", "year": "2023"},
        {"name": "Nature Materials – Sr[LiAl3N4]:Eu2+（SLA）", "url": "https://www.nature.com/articles/nmat4012", "kind": "期刊", "year": "2014"},
        {"name": "Nature Communications – Sr[Li2Al2O2N2]:Eu2+（SALON）", "url": "https://www.nature.com/articles/s41467-019-09632-w", "kind": "期刊", "year": "2019"},
        {"name": "Applied Physics Letters – β-SiAlON:Eu2+（NIMS）", "url": "https://pubs.aip.org/aip/apl/article/86/21/211905/931445/Characterization-and-properties-of-green-emitting", "kind": "期刊", "year": "2005"},
        {"name": "ECS Solid-State Letters – CaAlSiN3:Eu2+", "url": "https://iopscience.iop.org/article/10.1149/1.2173192", "kind": "期刊", "year": "2006"},
        {"name": "J. Electrochem. Soc. – K2SiF6:Mn4+ 首度報導（足立定夫）", "url": "https://iopscience.iop.org/article/10.1149/1.2993159", "kind": "期刊", "year": "2008"},
        {"name": "SID Symposium Digest – PFS/KSF（GE TriGain）", "url": "https://sid.onlinelibrary.wiley.com/doi/10.1002/sdtp.10406", "kind": "期刊", "year": "2015"},
        {"name": "SID Information Display – KSF: A Decade of Dominance", "url": "https://sid.onlinelibrary.wiley.com/doi/10.1002/msid.70057", "kind": "期刊", "year": "2026"},
        {"name": "Laser & Photonics Reviews – UCr4C4 型窄頻螢光粉綜述", "url": "https://onlinelibrary.wiley.com/doi/10.1002/lpor.202500740", "kind": "期刊", "year": "2025"},
        {"name": "Applied Physics Letters – 雷射螢光轉換器綜述", "url": "https://pubs.aip.org/aip/apl/article/118/21/210503/1061193/Phosphor-converters-for-laser-driven-light-sources", "kind": "期刊", "year": "2021"},
        {"name": "Materials（PMC）– Eu2+ 長餘輝綜述", "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC5445854/", "kind": "期刊", "year": "2010"},
        {"name": "Scientific Reports – KRICT 螢光粉光學性質資料集", "url": "https://www.nature.com/articles/s41598-024-58351-w", "kind": "期刊", "year": "2024"},
        {"name": "IEA – The next wave of LED lighting", "url": "https://www.iea.org/commentaries/the-next-wave-of-led-lighting-smarter-circular-and-more-efficient", "kind": "官方", "year": "2025"},
        {"name": "DOE – SSL Forecast Report", "url": "https://www.energy.gov/cmei/ssl/ssl-forecast-report", "kind": "政府", "year": "2019"},
        {"name": "DOE – 2022 SSL R&D Opportunities", "url": "https://www.osti.gov/servlets/purl/1862626", "kind": "政府", "year": "2022"},
        {"name": "USGS – Mineral Commodity Summaries 2026：釔", "url": "https://pubs.usgs.gov/periodicals/mcs2026/mcs2026-yttrium.pdf", "kind": "政府", "year": "2026"},
        {"name": "中國商務部 – 2025 年第 18 號公告（中重稀土出口管制）", "url": "https://www.mofcom.gov.cn/zwgk/zcfb/art/2025/art_9c2108ccaf754f22a34abab2fedaa944.html", "kind": "官方", "year": "2025"},
        {"name": "CSIS – 稀土出口管制一週年", "url": "https://www.csis.org/analysis/rare-earth-export-restrictions-one-year-later", "kind": "智庫", "year": "2026"},
        {"name": "Dolby – 收購 GE Licensing 新聞稿", "url": "https://news.dolby.com/en-WW/238205-dolby-laboratories-announces-agreement-to-acquire-ge-licensing-from-ge-aerospace/", "kind": "廠商", "year": "2024"},
        {"name": "ACCESS Newswire – Edison Innovations 購入 GE 專利", "url": "https://www.accessnewswire.com/newsroom/en/business-and-professional-services/edison-innovations-llc-a-dominion-harbor-company-acquires-diverse-988115", "kind": "廠商", "year": "2025"},
        {"name": "LEDinside – Edison Innovations KSF 專訪", "url": "https://www.ledinside.com/interview/2026/8/2026_08_31_01", "kind": "產業媒體", "year": "2026"},
        {"name": "Inside Lighting – CFIUS 封殺 Lumileds 收購案", "url": "https://inside.lighting/news/26-04/us-regulators-block-proposed-lumileds-acquisition", "kind": "產業媒體", "year": "2026"},
        {"name": "NIMS – CASN 中國專利訴訟終結新聞稿", "url": "https://www.nims.go.jp/eng/press/2026/05/202605130.html", "kind": "官方", "year": "2026"},
        {"name": "日本經濟新聞 – 日亞化學 2025 年度財報", "url": "https://www.nikkei.com/article/DGXZQOCC255FC0V20C26A3000000/", "kind": "媒體", "year": "2026"},
        {"name": "國立臺灣大學 – 劉如熹團隊 NIR-III 綜述焦點新聞", "url": "https://www.ntu.edu.tw/spotlight/2026/2500_20260624.html", "kind": "官方", "year": "2026"},
        {"name": "TÜV Rheinland – 歐盟 RoHS 含鎘量子點豁免（(EU) 2024/1416）", "url": "https://www.tuv.com/regulations-and-standards/en/europe-directive-eu-2024-1416-amending-annex-iii-to-eu-rohs-cadmium-in-downshifting-semiconductor.html", "kind": "法規", "year": "2024"},
        {"name": "Phosphor Safari 2026 – 歷屆會議與創辦人", "url": "https://phosphorsafari2026.com/", "kind": "會議", "year": "2026"},
    ],
}
