# -*- coding: utf-8 -*-
"""發展里程碑：從 1852 年「螢光」一詞誕生到 2026 年。
category：科學／產業／專利／政策／市場／應用。"""

TIMELINE = {
    "lead": "螢光粉的歷史可以分成四個時代：日光燈與映像管（1930–1980 年代）、稀土三基色（1970 年代起）、白光 LED（1996 年起）、以及窄頻與功能性螢光粉（2010 年代起）。每個時代的轉折點都是一種新材料。可依地區或類別篩選。",
    "events": [
        {"year": "1852", "title": "「螢光」一詞誕生", "detail": "英國物理學家 G. G. Stokes 研究螢石與鈾玻璃把紫外光轉成藍光的現象，創造 fluorescence 一詞，並以「激發停止後是否繼續發光」區分螢光與磷光。「phosphor」一詞則自中世紀就用來稱呼會在黑暗中發光的礦物。", "region": "歐洲", "category": "科學", "entities": ["G. G. Stokes"], "src": "https://link.springer.com/chapter/10.1007/978-3-642-56853-4_1", "srcName": "Springer（名詞源流）"},
        {"year": "1938", "title": "GE 讓日光燈商業化", "detail": "低壓汞蒸氣放電約 65% 的能量集中在 254 nm 紫外線，玻璃管內壁的螢光粉負責把它轉成可見光。1926 年德國 Germer 提出構想，GE 買下專利後由 Inman 團隊在 1938 年推出商品，這是螢光粉第一個大規模照明應用。", "region": "美國", "category": "產業", "entities": ["GE"], "src": "https://www.newworldencyclopedia.org/entry/Fluorescent_lamp", "srcName": "New World Encyclopedia"},
        {"year": "1942", "title": "鹵磷酸鹽螢光粉讓日光燈效率翻倍", "detail": "英國 Osram-GEC 的 McKeag 團隊發明 Ca₅(PO₄)₃(F,Cl):Sb³⁺,Mn²⁺，用銻的藍光加錳的橙紅光混成白光，效率幾乎提升一倍，並取代含劇毒鈹的矽酸鋅鈹。美國專利 US 2,488,733 於 1949 年核准。", "region": "歐洲", "category": "科學", "entities": ["McKeag", "Osram-GEC"], "src": "https://patents.google.com/patent/US2488733A/en", "srcName": "Google Patents US2488733A"},
        {"year": "1964", "title": "彩色電視的紅色：YVO₄:Eu³⁺", "detail": "Levine 與 Palilla 在 Applied Physics Letters 發表釩酸釔銪紅粉，620 nm 的尖銳紅線正好匹配人眼，解決了映像管紅色不足的問題，稀土首次進入螢幕；之後被效率更高的 Y₂O₂S:Eu³⁺ 取代。", "region": "美國", "category": "科學", "entities": ["Levine", "Palilla"], "src": "https://pubs.aip.org/aip/apl/article-abstract/5/6/118/51332/A-NEW-HIGHLY-EFFICIENT-RED-EMITTING", "srcName": "Applied Physics Letters 1964"},
        {"year": "1967", "title": "YAG:Ce 誕生：原本是為映像管做的", "detail": "飛利浦研究實驗室的 Blasse 與 Bril 為彩色電視的飛點掃描管開發 Y₃Al₅O₁₂:Ce³⁺，放射峰 550 nm、衰減只有 0.07 微秒。沒人料到 30 年後它會成為白光 LED 的標準黃粉。", "region": "歐洲", "category": "科學", "entities": ["Blasse", "Bril", "Philips"], "src": "https://pubs.aip.org/aip/apl/article-abstract/11/2/53/31404/A-NEW-PHOSPHOR-FOR-FLYING-SPOT-CATHODE-RAY-TUBES", "srcName": "Applied Physics Letters 1967"},
        {"year": "1972", "title": "上轉換材料 NaYF₄:Yb,Er", "detail": "Applied Physics Letters 報告 NaYF₄:Yb,Er 是效率最高的上轉換螢光粉，可見光輸出至少是 YF₃:Yb,Er 的兩倍；這個材料在 2000 年代奈米化後成為生醫影像與防偽的主角。", "region": "美國", "category": "科學", "entities": ["NaYF4:Yb,Er"], "src": "https://pubs.aip.org/aip/apl/article/21/4/159/528541/NaYF4-Yb-Er-an-efficient-upconversion-phosphor", "srcName": "Applied Physics Letters 1972"},
        {"year": "1974", "title": "飛利浦三基色螢光粉開啟稀土時代", "detail": "Verstegen 在 J. Electrochem. Soc. 報告紅光 Y₂O₃:Eu³⁺、綠光 (Ce,Tb)MgAl₁₁O₁₉、藍光 BaMg₂Al₁₆O₂₇:Eu²⁺ 的三色配方，同時得到高效率與高顯色，燈管可做得更細，直接催生了省電燈泡。", "region": "歐洲", "category": "科學", "entities": ["Verstegen", "Philips"], "src": "https://www.sciencedirect.com/science/article/abs/pii/0254058487901039", "srcName": "Phosphors based on rare-earths（1987）"},
        {"year": "1993", "title": "中村修二做出實用藍光 LED；夜光粉 LumiNova 發明", "detail": "日亞化學展示 InGaN 雙異質結構藍光 LED，11 月 30 日達到超過 1000 mcd 的亮度，1994 年量產；赤崎勇與天野浩在名古屋大學解決了 p 型 GaN 的難題。沒有藍光就沒有白光 LED。同年，根本特殊化學的 Matsuzawa 等人發明鋁酸鍶夜光粉 LumiNova，作為含鐳夜光塗料的安全替代品。", "region": "日本", "category": "產業", "entities": ["Nichia", "中村修二", "赤崎勇", "天野浩", "Nemoto"], "src": "https://ethw.org/Milestones:Practical_Blue_Light-Emitting_Diode,_1989%E2%80%931993", "srcName": "IEEE ETHW 里程碑"},
        {"year": "1996", "title": "第一顆白光 LED：藍光晶片＋YAG:Ce", "detail": "9 月，日亞化學用 455 nm 藍光晶片激發自家的黃色 YAG:Ce 螢光粉，藍光與黃光互補混成白光。日亞自 1956 年創立起就是螢光粉製造商，這個「藍＋黃」架構至今仍是白光 LED 的主流。同年 8 月，Matsuzawa 等人發表 SrAl₂O₄:Eu²⁺,Dy³⁺ 長餘輝論文，夜光粉亮度提升十倍以上。", "region": "日本", "category": "產業", "entities": ["Nichia", "YAG:Ce", "Nemoto"], "src": "https://www.nichia.co.jp/specification/newsroom/news/Whiteled25anniversary.pdf", "srcName": "Nichia 白光 LED 25 週年"},
        {"year": "1997", "title": "日亞申請白光 LED 核心專利", "detail": "US 5,998,925 於 1997 年 7 月 29 日申請，涵蓋藍光晶片加 YAG 系螢光粉的白光 LED。這組專利在往後 20 年成為全球 LED 產業訴訟與授權的焦點。", "region": "日本", "category": "專利", "entities": ["Nichia", "US5998925"], "src": "https://patents.google.com/patent/US5998925A/en", "srcName": "Google Patents US5998925A"},
        {"year": "2000", "title": "氮化物螢光粉登場", "detail": "慕尼黑大學 Schnick 團隊報導 M₂Si₅N₈:Eu²⁺（258 型）等氮化物的紅光發光，OSRAM 隨後將其用於暖白 LED，開啟「氮化物時代」：化學鍵強、耐熱耐濕，正是高功率 LED 需要的性質。", "region": "歐洲", "category": "科學", "entities": ["Schnick", "OSRAM"], "src": "https://pmc.ncbi.nlm.nih.gov/articles/PMC10142842/", "srcName": "PMC 綜述（氮化物紅粉沿革）"},
        {"year": "2005", "title": "NIMS 發表 β-SiAlON:Eu 窄頻綠粉", "detail": "廣崎尚登、謝榮軍等人在 Applied Physics Letters 報告放射峰 535 nm、半高寬 55 nm、可被 280–480 nm 激發的綠色氮氧化物，結構堅固、耐熱耐濕，由 Denka 取得授權量產，成為廣色域背光的標準綠粉。", "region": "日本", "category": "科學", "entities": ["NIMS", "Denka", "廣崎尚登", "謝榮軍"], "src": "https://pubs.aip.org/aip/apl/article/86/21/211905/931445/Characterization-and-properties-of-green-emitting", "srcName": "Applied Physics Letters 2005"},
        {"year": "2006", "title": "CASN 紅粉發表；白光 LED 突破 150 lm/W", "detail": "2 月，NIMS 的 Uheda 等人與三菱化學發表 CaAlSiN₃:Eu²⁺，405 nm 激發下的量子輸出是傳統紅粉 La₂O₂S:Eu 的 7 倍，成為暖白 LED 最普及的紅粉。12 月，日亞宣布 150 lm/W 的白光 LED。", "region": "日本", "category": "科學", "entities": ["NIMS", "三菱化學", "Nichia"], "src": "https://iopscience.iop.org/article/10.1149/1.2173192", "srcName": "ECS Solid-State Letters 2006"},
        {"year": "2011", "title": "GE 解決 KSF 的抗濕與色穩定問題", "detail": "GE 研究團隊（Setlur、Lyons 等）取得 Mn⁴⁺ 氟化物螢光粉的抗濕與色穩定專利（US 8,057,706、US 8,252,613），把原本怕水的 K₂SiF₆:Mn⁴⁺ 改良到可商用；日亞同年開始與 GE 合作照明用 PFS。", "region": "美國", "category": "專利", "entities": ["GE", "Setlur", "KSF"], "src": "https://sid.onlinelibrary.wiley.com/doi/10.1002/sdtp.10406", "srcName": "SID Symposium Digest 2015"},
        {"year": "2012", "title": "億光在美國挑戰日亞 YAG 專利", "detail": "台灣億光對日亞的美國專利 5,998,925 與 7,531,960 提起確認無效訴訟；2015 年 4 月 22 日密西根東區聯邦地院陪審團判定被主張的請求項全部無效。", "region": "台灣", "category": "專利", "entities": ["億光", "Nichia"], "src": "https://en.everlight.com/pr_20221125/", "srcName": "Everlight 新聞稿"},
        {"year": "2014", "title": "藍光 LED 獲諾貝爾獎；SLA 窄頻紅粉發表；KSF 進入背光", "detail": "10 月，赤崎勇、天野浩、中村修二獲諾貝爾物理獎。6 月，Schnick 團隊與 Lumileds 在 Nature Materials 發表 Sr[LiAl₃N₄]:Eu²⁺（650 nm、半高寬 50 nm、200 °C 效率 >95%，原型 LED 效率 +14%）。3 月，Cree 宣布 303 lm/W 實驗室紀錄。KSF 開始進入 LCD 背光市場。", "region": "全球", "category": "科學", "entities": ["諾貝爾獎", "Schnick", "Lumileds", "Cree", "SLA"], "src": "https://www.nobelprize.org/prizes/physics/2014/press-release/", "srcName": "NobelPrize.org；Nature Materials 2014"},
        {"year": "2015", "title": "GE TriGain 商品化；日亞與三菱／NIMS 交互授權", "detail": "GE 以 TriGain 為名發表 KSF，LED 封裝光效比氮化物紅粉高 10% 以上，並授權顯示應用。1 月，日亞與三菱化學、NIMS、Citizen 就氮化物紅粉專利交互授權。IES 同年推出 TM-30 顯色評估法。", "region": "全球", "category": "產業", "entities": ["GE", "Nichia", "三菱化學", "NIMS"], "src": "https://www.nichia.co.jp/en/newsroom/2015/2015_010701.html", "srcName": "Nichia 新聞稿 2015"},
        {"year": "2016", "title": "OSRAM 提出近紅外 pc-LED；Lumileds 發布窄頻紅粉白皮書", "detail": "OSRAM 提出以藍光晶片激發 Cr³⁺ 螢光粉的寬頻近紅外 LED 概念，把 LED 帶進光譜檢測領域；GE 開始把 KSF 授權給中國穗晶、聚飛；12 月 Lumileds 發布窄頻紅粉技術白皮書並導入中功率產品。", "region": "歐洲", "category": "產業", "entities": ["OSRAM", "Lumileds", "GE"], "src": "https://www.led-professional.com/products-services/osram-presents-the-worlds-smallest-broadband-ir-led-for-spectroscopy-applications", "srcName": "LED professional"},
        {"year": "2017", "title": "日亞 YAG 專利到期；SunLike 類太陽光 LED 上市", "detail": "7 月 29 日日亞歐洲專利 EP936682 及德國對應專利到期，YAG:Ce 成為公共技術。首爾半導體與東芝材料推出以紫光晶片激發 TRI-R 三色螢光粉的 SunLike。Nature Materials 提出「零熱猝滅螢光粉」概念。", "region": "全球", "category": "專利", "entities": ["Nichia", "首爾半導體", "東芝材料"], "src": "https://www.ledinside.com/news/2017/6/seoul_semiconductor_and_toshiba_materials_co_develop_sunlike_solution_friendly_to_human_eyes", "srcName": "LEDinside 2017"},
        {"year": "2018", "title": "NIMS 把紅粉專利授權拆成「製造」與「應用」；機器學習進入螢光粉研究", "detail": "10 月 NIMS 宣布 CASN／SCASN 專利分為製造用與應用用兩種授權，降低封裝廠與燈具廠門檻。同年休士頓大學 Brgoch 團隊以機器學習篩選高熱穩定性基質，開啟資料驅動的螢光粉發現。", "region": "日本", "category": "專利", "entities": ["NIMS", "Brgoch"], "src": "https://www.ledinside.com/press/2018/10/nims_separates_its_red_phosphor_patent_usages_into_manufacturing_and_application", "srcName": "LEDinside 2018"},
        {"year": "2019", "title": "SALON 發表；日亞 Vitasolis 走向人因照明", "detail": "4 月，Schnick 團隊在 Nature Communications 發表 Sr[Li₂Al₂O₂N₂]:Eu²⁺（614 nm、半高寬 48 nm、原型 LED 效率 +16%）。5 月，日亞在 LIGHTFAIR 發表以螢光粉配方增加青色成分、支援生理節律的 Vitasolis。", "region": "全球", "category": "科學", "entities": ["Schnick", "Nichia", "SALON"], "src": "https://www.nature.com/articles/s41467-019-09632-w", "srcName": "Nature Communications 2019"},
        {"year": "2020", "title": "日亞成為 GE TriGain 第一家授權商", "detail": "11 月，日亞宣布取得 GE Current 的 TriGain（PFS／KSF）授權，用於全球照明產品；日亞自 2011 年起與 GE 合作、2015 年起供貨。KSF 的專利網此後仍是少數受嚴密保護的主流螢光粉。", "region": "日本", "category": "專利", "entities": ["Nichia", "GE Current"], "src": "https://www.businesswire.com/news/home/20201119005876/en/Nichia-Corporation-Becomes-First-to-License-TriGain-Technology-from-GE-Current-a-Daintree-company", "srcName": "Business Wire 2020"},
        {"year": "2021", "title": "白光 LED 25 週年；Bridgelux Thrive 填補青色缺口", "detail": "日亞慶祝白光 LED 25 週年，並推出結合先進螢光粉技術、同時提升顯色與光效的 LED。11 月 Bridgelux 發表 Thrive 93，用寬頻藍光晶片加特殊螢光粉配方讓光譜與日光的差異縮小到 3–7%。", "region": "全球", "category": "產業", "entities": ["Nichia", "Bridgelux"], "src": "https://www.bridgelux.com/blog/bridgelux-releases-thrive-93-delivering-lighting-s-closest-match-natural-light-while-saving", "srcName": "Bridgelux 2021"},
        {"year": "2022", "title": "DOE 指出 pc-LED 封裝光效可從 160 提升到 255 lm/W", "detail": "美國能源部固態照明研發機會報告把窄頻紅色轉換材料列為主要槓桿：減少落在深紅區的能量可提升光譜效率；若以量子點取代紅粉光效可再提升約 25%。同年 10 月，日亞與 Savant（GE Lighting）交互授權 PFS。", "region": "美國", "category": "政策", "entities": ["DOE", "Nichia", "Savant"], "src": "https://www.osti.gov/servlets/purl/1862626", "srcName": "DOE 2022 SSL R&D Opportunities"},
        {"year": "2023", "title": "歐盟淘汰含汞螢光燈管；AI 材料探索興起", "detail": "歐盟 RoHS 豁免到期，T8／T5 燈管與省電燈泡陸續禁售，螢光燈螢光粉需求快速萎縮，稀土（鋱、銪）需求結構改變。11 月 Google DeepMind 發表 GNoME，預測數十萬種新穩定晶體，影響螢光粉研究方法。", "region": "全球", "category": "政策", "entities": ["歐盟", "Google DeepMind"], "src": "https://www.iea.org/commentaries/the-next-wave-of-led-lighting-smarter-circular-and-more-efficient", "srcName": "IEA（LED 下一波）"},
        {"year": "2024", "title": "量子點電視出貨創新高；新型 α-SiAlON 與超窄青粉發表", "detail": "Omdia 統計含量子點的 LCD 電視出貨 2,440 萬台（2023 年 1,550 萬台），KSF 與量子點在 Mini LED 背光上持續競合。NIMS 與廈門大學合成富鍶 α-SiAlON；華南理工等團隊發表半高寬僅 18 nm 的青色 Na₅K₃(Li₃SiO₄)₈:Eu²⁺。", "region": "全球", "category": "市場", "entities": ["Omdia", "NIMS", "廈門大學"], "src": "https://www.nanosys.com/blog-newsroom/omdia-shipments-of-qd-miniled-tvs-to-surpass-oled-tvs-by-2025", "srcName": "Nanosys／Omdia 2024"},
        {"year": "2025", "title": "機器學習找到 44 nm 窄頻綠粉；UCr₄C₄ 家族十年綜述", "detail": "Chemical Engineering Journal 報告以機器學習發現的 CsRbKNa(Li₃SiO₄)₄:Eu²⁺（530 nm、半高寬 44 nm）；Laser & Photonics Reviews 綜述總結 UCr₄C₄ 型窄頻材料的優點與怕水弱點。12 月 25 日中國最高人民法院撤銷 NIMS CASN 中國專利的部分無效裁定。", "region": "中國", "category": "科學", "entities": ["華南理工大學", "NIMS"], "src": "https://www.sciencedirect.com/science/article/abs/pii/S138589472506557X", "srcName": "Chemical Engineering Journal 2025"},
        {"year": "2026", "title": "KSF「稱霸十年」、大舉授權台灣廠；NIMS 中國專利全數維持", "detail": "SID Information Display 刊出〈KSF Phosphor: A Decade of Dominance〉，累計出貨逾 1,000 億顆。5 月 NIMS 宣布 CASN 中國專利在六年無效訴訟後全數維持有效。8 月專利持有方 Edison Innovations 把 KSF 授權給億光、富采、木林森、Bridgelux 等廠，鎖定車用 Mini LED 顯示。", "region": "全球", "category": "專利", "entities": ["Edison Innovations", "億光", "富采", "NIMS"], "src": "https://www.ledinside.com/interview/2026/8/2026_08_31_01", "srcName": "LEDinside 2026-08；NIMS 2026-05"},
    ],
}
